### ISSUE TITLE
new array methods...

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#513] opened 2015-08-10 14:24 UTC
http://csound.1045644.n5.nabble.com/new-array-methods-td5742850.html

**Comment by vlazzarini** [comment] 2015-09-16 12:13
Not quite sure where we're at with this. The thinking was to make arrays dynamic, but we need to develop the idea a bit more. Not quite sure it's ready for 6.6.0. More like 7.0.0

**Comment by kunstmusik** [comment] 2015-09-16 12:59
I checked that link and yes, it seems like there is too much work there to get this in by 6.06. (I removed the milestone here.) We could maybe look to do this for a 6.07.0, which would give time to implement and test.  I don't think there'd be anything in particular for this that would require changes from CS7.

**Comment by rorywalsh** [comment] 2015-09-16 13:14
As the one who brought it up to begin with, I would love to see them
introduced in 6.07, even if they are snuck in under the radar just for
testing purposes :)

**Comment by vlazzarini** [comment] 2015-09-16 14:38
The problem is more of defining the semantics and behaviour of these properly; implementation should be one afternoon's work or thereabouts.

**Comment by hlolli** [comment] 2022-12-28 15:35
can you dig this thread from somewhere @rorywalsh ?

**Comment by jpffitch** [comment] 2022-12-31 14:05
There is a list in arrays.c

⁣Get TypeApp for Android ​

**Comment by kunstmusik** [comment] 2023-11-04 22:08
Closing: the nabble message link is dead and I'm not sure what this story is about now.

**Closed by kunstmusik** 2023-11-04 22:08 UTC
Labels: enhancement
