### ISSUE TITLE
Compile csound for android

### ISSUE THREAD

**Issue by KyoSherlock** [csound/csound#557] opened 2015-11-20 09:11 UTC
There some error when compile project for android as bellow:
Generating wrappers...
../../interfaces/CppSound.hpp:37: Warning 453: Can't apply (std::vector< double > *INPUT). No typemaps are defined.
../../interfaces/CppSound.hpp:53: Warning 813: Warning for CppSound proxy: Base CsoundFile ignored. Multiple inheritance is not supported in Java.

ALL:
jianghuis-MacBook-Pro:android jianghui$ ls
BUILDING_ON_ANDROID.txt		downloadDependencies.sh
CHANGELOG			fluidsynth-android
COPYING				liblo-android
CSDPlayer			libsndfile-android
CsoundAndroid			luajit-2.0
CsoundAndroidExamples		pluginlibs
CsoundForAndroid		release-android-studio.sh
build-all-mkg.sh		release.sh
build-all.sh			update-android-studio.sh
docs
jianghuis-MacBook-Pro:android jianghui$ export NDK_MODULE_PATH=/Users/jianghui/Downloads/source/git/csound-develop/android
jianghuis-MacBook-Pro:android jianghui$ sh build-all.sh
Building in  LuaCsound
Android NDK: ERROR:/Users/jianghui/Downloads/source/git/csound-develop/android/luajit-2.0/jni/Android.mk:luajit: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/jianghui/Downloads/source/git/csound-develop/android/luajit-2.0/jni/../src/libluajit.a exists  or that its path is correct   
/Users/jianghui/work/android/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
Building in  doppler
[armeabi] Install        : libdoppler.so => libs/armeabi/libdoppler.so
[armeabi] Install        : libgnustl_shared.so => libs/armeabi/libgnustl_shared.so
[armeabi-v7a] Install        : libdoppler.so => libs/armeabi-v7a/libdoppler.so
[armeabi-v7a] Install        : libgnustl_shared.so => libs/armeabi-v7a/libgnustl_shared.so
Building in  libOSC
Android NDK: WARNING:/Users/jianghui/Downloads/source/git/csound-develop/android/liblo-android/jni/Android.mk:lo: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING:/Users/jianghui/Downloads/source/git/csound-develop/android/liblo-android/jni/Android.mk:lo: LOCAL_LDLIBS is always ignored for static libraries    
[armeabi] Install        : libOSC.so => libs/armeabi/libOSC.so
[armeabi-v7a] Install        : libOSC.so => libs/armeabi-v7a/libOSC.so
Building in  libfluidsynth
[armeabi] Install        : libfluidOpcodes.so => libs/armeabi/libfluidOpcodes.so
[armeabi] Install        : libgnustl_shared.so => libs/armeabi/libgnustl_shared.so
[armeabi-v7a] Install        : libfluidOpcodes.so => libs/armeabi-v7a/libfluidOpcodes.so
[armeabi-v7a] Install        : libgnustl_shared.so => libs/armeabi-v7a/libgnustl_shared.so
Building in  libscansyn
[armeabi] Install        : libscansyn.so => libs/armeabi/libscansyn.so
[armeabi-v7a] Install        : libscansyn.so => libs/armeabi-v7a/libscansyn.so
Building in  libstdutil
[armeabi] Install        : libstdutil.so => libs/armeabi/libstdutil.so
[armeabi] Install        : libsndfile.so => libs/armeabi/libsndfile.so
[armeabi-v7a] Install        : libstdutil.so => libs/armeabi-v7a/libstdutil.so
[armeabi-v7a] Install        : libsndfile.so => libs/armeabi-v7a/libsndfile.so
Building in  patches
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/Users/jianghui/work/android/android-ndk-r10e/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.
Building in  signalflowgraph
[armeabi] Install        : libsignalflowgraph.so => libs/armeabi/libsignalflowgraph.so
[armeabi] Install        : libgnustl_shared.so => libs/armeabi/libgnustl_shared.so
[armeabi-v7a] Install        : libsignalflowgraph.so => libs/armeabi-v7a/libsignalflowgraph.so
[armeabi-v7a] Install        : libgnustl_shared.so => libs/armeabi-v7a/libgnustl_shared.so
../../Engine/csound_orc.y: conflicts: 4 shift/reduce, 18 reduce/reduce
Language subdirectory: java
Search paths:
   ./
   /usr/local/include/
   ../../H/
   ../../include/
   ../../Engine/
   ../../
   ../../interfaces/
   /System/Library/Frameworks/Python.framework/Headers/
   /System/Library/Frameworks/JavaVM.framework/Headers/
   ./jni/
   ./swig_lib/java/
   /usr/local/Cellar/swig/3.0.7/share/swig/3.0.7/java/
   ./swig_lib/
   /usr/local/Cellar/swig/3.0.7/share/swig/3.0.7/
Preprocessing...
Starting language-specific parse...
Processing types...
C++ analysis...
Processing nested classes...
Generating wrappers...
../../interfaces/CppSound.hpp:37: Warning 453: Can't apply (std::vector< double > *INPUT). No typemaps are defined.
../../interfaces/CppSound.hpp:53: Warning 813: Warning for CppSound proxy: Base CsoundFile ignored. Multiple inheritance is not supported in Java.
./build.sh: line 18: /ndk-build: No such file or directory
jianghuis-MacBook-Pro:android jianghui$

**Comment by kunstmusik** [comment] 2015-11-20 11:43
@KyoSherlock Did you read the build instructions?  It doesn't look like you ran downloadDependencies.sh. Also, it doesn't look like you setup environment variables (i.e. $ANDROID_NDK_ROOT), which is explained in the build instructions. 

I'm closing this as not a bug. If you have further questions after reading the instructions, please send an email to the csound mailing list.

**Closed by kunstmusik** 2015-11-20 11:43 UTC
