### ISSUE TITLE
Isn't compatible with FluidSynth 2.x

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1078] opened 2018-11-25 17:46 UTC
See log here: https://ptpb.pw/-t-8

**Comment by vlazzarini** [comment] 2018-11-25 18:05
It's known that the fluidsynth opcodes are written for 1.x

**Comment by yurivict** [comment] 2018-11-25 18:17
You should remove the dependency on FluidSynth then is you can't support the new version.

**Comment by rorywalsh** [comment] 2018-11-25 18:33
Is it possible to have both versions installed? Sorry, I know nothing of fluidsynth.

**Comment by yurivict** [comment] 2018-11-25 18:37
@rorywalsh Currently FluidSynth isn't designed to be concurrently installed. It installs ```/usr/local/bin/fluidsynth```, ```/usr/local/include/fluidsynth/*``` and ```/usr/local/lib/libfluidsynth.so```.

FluidSynth project could easily uniquify these file names and allow concurrent version installations.

You should contact them and request this since you are the interested party.

**Comment by kunstmusik** [comment] 2018-11-25 18:40
Reopening: let's leave this as a todo to support Fluidsynth 2.x as the problem is coming up often enough that it needs a fix. One path would be to have CMake detect Fluidsynth version and enable build only for 1.x, or other path to conditionally build for either 1.x or 2.x.

**Comment by yurivict** [comment] 2018-11-25 18:49
Following up on what I said, FluidSynth could rename all files with ```-2``` suffix opening the way to concurrent installations. They can do this even now with the next update. This way you could remain on 1.x for a long time. But this needs to be done only with FluidSynths's upstream consent.

**Comment by vlazzarini** [comment] 2018-11-25 18:59
That's a very good idea. Maybe a ticket should be open there.

As for Csound, the fluidsynth opcodes are scheduled to move to their own separate repo.

**Comment by vlazzarini** [comment] 2018-11-25 19:00
I would prefer that this issue is closed as far as Csound is concerned as we have to take these opcodes out of the main repo.

**Comment by yurivict** [comment] 2018-11-26 17:20
FluidSynth rejected the idea of having the ability to install versions concurrently. Consequently, you should either convert to 2.x or abandon FluidSynth entirely, as far as most users go.

**Comment by kunstmusik** [comment] 2018-12-01 16:50
@yurivict Does develop branch now work for you with Fluidsynth 2.x?  We merged a PR (https://github.com/csound/csound/pull/1046) that seems to address it, but I don't have a system with 2.x at the moment to test on.

**Comment by yurivict** [comment] 2018-12-01 18:19
It doesn't build: https://github.com/csound/csound/issues/1081

**Comment by yurivict** [comment] 2018-12-01 18:37
Yes, but I can't build it to verify because of this.

**Comment by dvzrv** [comment] 2019-01-08 17:59
Also, this is a dup of #1036

**Comment by kunstmusik** [comment] 2019-01-28 10:36
Fixed as part of #1036.

**Closed by kunstmusik** 2019-01-28 10:36 UTC
Labels: enhancement
