### ISSUE TITLE
PADsynth opcode

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#368] opened 2014-08-19 12:43 UTC
this is a request for a new opcode with code from http://zynaddsubfx.sourceforge.net/doc/PADsynth/PADsynth.htm from Paul Nasca. This code is used in other commercial and non-commercial applications.
I think there should be no problem regarding the license.

I think the algorithm can be applied to whatever soundfile

**Comment by gogins** [comment] 2015-02-23 14:06
I have implemented some enhancements to the padsynth fgen. However, I have only just now understood that the "base function" in the ZynAddSubFX  plugin and its code can refer not only to the profile of each partial, but also to the waveform that is used to create the spectrum before the profile is applied. It is true that these oscillator base functions have a big impact on the sound, so I am going to try to modify my code to enable either these, or the use of a pre-defined Csound function table for the spectrum.

**Comment by gogins** [comment] 2015-02-24 02:45
I have cleaned up the padsynth_gen.cpp code. Three profiles are now supported, as in the ZynAddSubFX code: Gaussian, square, and expontential. Each takes a shaping parameter. I have not implemented the crazy base functions for generating the waveform that will receive bandwidth enhancement. I think this will be worth doing in the future, as the sounds of some of these waveforms are quite original. I also have finished the Csound reference manual page for the padsynth GEN routine. This code has been pushed to GIT develop.

**Comment by gogins** [comment] 2015-04-03 18:53
Right.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment] 2015-04-04 20:32
I have fixed the aliasing reported by Menno. It was caused by my using Csound's complex inverse FFT routine instead of the real inverse FFT. The code now uses Csound's real inverse FFT routine.
The question of using a function table containing a sound sample, or the FFT of a sound sample, in place of partials input by the user requires more consideration. I am closing this issue and will enter a new issue as an enhancement. The current state of the opcode and documentation should go into release 6.05.

**Closed by gogins** 2015-04-04 20:32 UTC
Labels: enhancement
