### ISSUE TITLE
Envelope generator problems

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#601] opened 2016-02-19 12:09 UTC
A number of envelope generators has problems if the note duration is not long enough to complete the described segments. This relates mainly to the -r family of opcodes (release segment). For completeness, I've also included some comments about the regular generators (non-extending, e.g. linseg), and the classic envelope generators (adsr, linen).

** Preferred behaviour: if not enough time to complete line segment:
- regular line segment generators: just stop processing when the note is turned off (this is already ok, just mentioning for context with the sibling -r opcodes)
- segment genereators with -r segment: apply release segment from the value reached when the instrument is turned off
- envelopes that do not extend (adsr, xadsr, linen, envlpx): I think they are just strange and should be deprecated. No sane solution exist for determining how they should complete the decribed segments if the note duration is shorter than the segments. 

Here is a list of the tested opcodes:
A csd is provided, uncomment the relevent

* linenr
- works well

* linsegr
- behaves oddly if iz is not present (but compiles without warning)
- works as preferred with shorter note durations

* madsr
- extends note duration, but show oddities with truncation of segment lengths if attack+decay+release time does not fit within the note duration
- note that release time extends note duration, but this still influence truncation of segments if note duration is shorter than specified attack+decay+release time 

* mxadsr
- works well regarding segment durations

* expsegr
- if ia is zero the printed error is "ival3 is zero", could this be changed to "ia is zero" ?
- works well regarding segment durations

* transegr
- works well

* cossegr
- works well

* envlpxr
- manual mentions that iatss is dependent on duration. It is unclear what this means. It seems it was written to explain how evlpx works, but this does not apply to envlpxr, since the duration is not known.
- if the opcode is used with a rise shape that does not have an extended guard point, the error message is "rise func ends with zero". Could the error message mention the possibility that this was caused by a missing guard point?
- behaves oddly if the duration of the attack segment does not fit within the note duration (skips release stage). It should ideally produce the release stage from the value reached by the attack segment (even if attack segment does not complete during event duration).

* xtratim and relase flag handling
- works well

* adsr, xadsr
- behaves oddly if the duration of segments does not fit within the note duration
- the length of the decay and attack segments are truncated

* linen
- like adsr, truncates attack segment (irise) if idur is not sufficient to complete both rise and decay time. The manual states that rise and decay should be in effect at the same time if rise and decay times overlap.

* envlpx
- if the duration of segments does not fit within the note duration, the release segment is truncated. The release segment should ideally be in effect at the same time as the rise segment if duration is not sufficient to perform each separately. This to avoid discontinuities. 

**** TEST CSD***
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

	sr = 48000
	ksmps = 64
	0dbfs = 1

	giSine  ftgen	0, 0, 65536, 10, 1		; sine wave
	giRise  ftgen   0, 0, 4097, 7, 0, 4096, 1       ; rising line

	instr 1
        iamp    = ampdbfs(p4)
	icps    = cpsmidinn(p5)
        iattack = 0.5
        idecay  = 0.5
        isust   = 0.5
        irel    = 0.5
	
	;amp	linenr 1, iattack, irel, 0.01
	amp	linsegr 0, iattack, 1, idecay, isust, irel, 0
	;amp	madsr iattack, idecay, isust, irel
        ;amp	mxadsr iattack, idecay, isust, irel
        ;amp	expsegr 0.01, iattack, 1, idecay, isust, irel, 0.01
        ;amp	transegr 0, iattack, 3, 1, idecay, -3, isust, irel, -3, 0
        ;amp	cossegr 0, iattack, 1, idecay, isust, irel, 0
        ;amp	envlpxr 1, iattack, irel, giRise, 0.9, 0.01
        
	;amp	adsr iattack, idecay, isust, irel
	;amp	xadsr iattack, idecay, isust, irel
	;amp	linen 1, iattack, p3, irel
        ;amp	envlpx 1, iattack, p3, irel, giRise, 0.9, 0.01

/* xtratim example just to compare
                xtratim irel
        kflag   release
        arel    init 1
        arise   init 1
        if kflag > 0 then
        arel    line 1, irel, 0
        else
        arise   linseg 0, iattack, 1, idecay, isust
        endif
        amp     = arise*arel 
*/

	a1	oscili amp*iamp, icps, giSine
		out a1
	endin

</CsInstruments>
<CsScore>
;	start	dur	amp     note
i1	0	0.2     -10     72
i1	1	0.7     .       .
i1	3	1.2     .       .
i1	5	2.2     .       .
f0 8
e
</CsScore>
</CsoundSynthesizer>

**Comment by vlazzarini** [comment] 2016-02-19 12:34
Can you make a quick list of the ones that need fixing?

**Comment by Oeyvind** [comment] 2016-02-19 12:52
The list is already in the original post, but I can sum it up:

** serious errors:
- madsr
- envlpxr

** minor oddities:
- linsegr
- expsegr

**serious errors, but suggest deprecating the opcodes:
- adsr
- xadsr
- linen
- envlpx

**Comment by vlazzarini** [comment] 2016-02-19 13:21
Ok. adsr and xadsr use linseg and expseg internally, so they should be easy to fix. madsr uses linsegr, so the same there. The others should be made to work as per the manual. It is possible that the sample accurate changes caused the problem.

**Comment by vlazzarini** [comment] 2016-02-20 10:07
I've fixed linen: it was only the audio rate version that did not match what the manual said. In GIT now

**Comment by vlazzarini** [comment] 2016-02-20 10:30
With regards to envlpx, there is a problem. I see that the manual says that if rise and decay phases overlap, they will be active at the same time. However, it appears to me that the code is far away from enabling that. It can do it, but we will need to modify it. 

This means that the opcode probably never behaved like what it says on the manual. So the problem is this: do we modify the behaviour and break backward compatibility or do we correct the manual to make it fit reality.

Note that this is different to linen, where the a-rate was clearly broken with regards to the k-rate version (which followed the manual).

So, I need to have John's (@jpffitch) input at this stage. Also given that adsr etc are his opcodes, maybe he should have a say on how they behave.

**Comment by vlazzarini** [comment] 2016-02-20 11:25
Fixed expsegr messages and linsegr now gives an init error if release segment is not there.

**Comment by vlazzarini** [comment] 2016-02-20 11:32
So in summary issues remain in envlpx, envlpxr, adsr, madsr, and xadsr.

**Comment by jpffitch** [comment] 2016-02-20 19:26
A couple of thoughts

1:  For envlpx the code is right and the manual should reflect reality -- that is a generic statement actually

2:  adsr and madsr were written for beginners and are shorthand for linseg/linsegr so fixing the later pair should be sufficient.

Cannot remember what xadsr is at present but I think it should be like adsr

**Comment by vlazzarini** [comment] 2016-02-20 20:19
I don't think linseg/r are broken, at least according to Oeyvind.

**Comment by jpffitch** [comment] 2016-02-20 20:31
But adsr was said to be.  So function adsrset1 is at fault.  I wasstarting with the closest to one I understand

**Comment by vlazzarini** [comment] 2016-02-20 20:36
I thought you meant linseg/r as the "latter pair"

**Comment by jpffitch** [comment] 2016-02-20 21:17
I have rewritten adsr/madsr with simpler code and an error if the sustain length is negative
adsr tested but not adsr (ak of midi here)

**Comment by kunstmusik** [comment] 2016-02-20 23:53
@jpffitch rather than an error, could we have it implemented as Oeyvind mentioned:

"segment generators with -r segment: apply release segment from the value reached when the instrument is turned off"

This is the behavior I always expected myself and would prefer this over reporting an error if p3 is too short. More specifically, I could see an error with adsr, but I would imagine madsr to use the above behavior. 

To me, the above would more closely match what I expect for electronic synthesizers, and it would be noticeable especially with pad sounds with long attack times. I could imagine here writing notes that may expect to be shorter than the total of segment durations.

**Comment by vlazzarini** [comment] 2016-02-21 09:28
But adsr is not an r envelope. I think an error is appropriate in this case. For all the r envelopes, the logical thing is to have release on note off, and that is the way they work anyway, except for any bugs.

**Comment by kunstmusik** [comment] 2016-02-21 11:02
Yes but my comment is in regards to madsr which is an -r opcode.

**Comment by Oeyvind** [comment] 2016-02-22 23:14
Maybe I should have created a separate issue for each opcode with a
problem, they just seemed releated and there was many errors. Lets see how
it works out, I can create separate issues for remaining cases if we don't
manage to solve all in one round.
John, the test case is in the csd pasted when I created the issue.
Uncomment the line with the opcode that should be tested.

I still think the older (non-r-stage) envelope opcodes can be difficult to
understand for a beginner in situations where note duration is shorter than
the specified segment lengths. I would not mind it of they created an
envelope as specified *up to the point where the note stops* but this is
not what they do. They commonly truncate the attack segment. I see that it
may be a problem changing this behaviour due to backwards compatibility,
hence the suggestion of deprecating them so as to minimize the risk of
problems for new users. For this I am talking about adsr, xadsr, linen, and
envlpx. With adsr it is even more confusing since it has a name ending with
-r.


2016-02-20 20:45 GMT+01:00 John ffitch <notifications@github.com>:

**Comment by vlazzarini** [comment] 2016-02-23 06:29
The issues are now restricted to envlpx, envlpxr, adsr,xadsr, and madsr. The others have been fixed.

**Comment by rorywalsh** [comment] 2016-03-03 09:27
> Fixed expsegr messages and linsegr now gives an init error if release segment is not there

This change breaks older instruments. A lot of Iain's Cabbage synths no longer work.

**Comment by Oeyvind** [comment] 2016-03-03 09:52
That is a tough one,
and has happened to me before too. It is an actual error in the instrument
code (Iain's), unless I am completely mistaken. Then it used to work (by
luck), and now that the implementation is fixed, it stops working. In my
opinion, the best would be to fix the instruments. Second best would be to
replace the init error with a very visible warning printed to the console.



2016-03-03 10:27 GMT+01:00 Rory Walsh <notifications@github.com>:

**Comment by vlazzarini** [comment] 2016-03-03 09:56
if you give me a couple of simple examples of linsegr and expsegr where it breaks, I can try to turn the error into a warning.

**Comment by rorywalsh** [comment] 2016-03-03 10:00
Here's what Iain reported to me on the matter:

> Here's what seems to be the problem. The following envelope will trigger the problem:
>  aenv  linsegr 1,0.2,0
> Whereas this one will not:
>  aenv  linsegr 0,0.01,1,0.2,0

**Comment by vlazzarini** [comment] 2016-03-03 10:03
yes, I know the change. It was made in response to this ticket.

**Comment by rorywalsh** [comment] 2016-03-03 10:05
That was an example of where it breaks?

**Comment by vlazzarini** [comment] 2016-03-03 10:06
I'll see what I can do.

**Comment by Oeyvind** [comment] 2016-03-03 10:23
Just my 2c:
The example (from Iain) that breaks now:

aenv linsegr 1,0.2,0

is not impemented correctly according to the linsegr manual:

ares *linsegr* ia, idur1, ib [, idur2] [, ic] [...], irel, iz

... where clearly at least 5 arguments must be present. So it is the
instrument that contains the error,, not the opcode (now that it has
been fixed).



2016-03-03 11:06 GMT+01:00 vlazzarini <notifications@github.com>:

**Comment by rorywalsh** [comment] 2016-03-03 10:42
For what it's worth I don't think Iain would have any problems with changing his code. I just find these changes a little abrupt. I would rather see them phased in over time. So for this release a user will receive a warning and be instructed to update their code as it will result in an init-error in future releases. This would give developers and those maintaining packages/instruments/etc a least one release cycle to get their shit together.

**Comment by Oeyvind** [comment] 2016-03-03 10:58
That is a nice solution. Good thinking.

2016-03-03 11:42 GMT+01:00 Rory Walsh <notifications@github.com>:

**Comment by iainmccurdy** [comment] 2016-03-03 11:12
While I appreciate that the single segment r-envelope method was never advocated in the manual, is there a reason why this behaviour cannot be implemented and continued? It seems to me like a useful way of being able to use linsegr etc. and does not affect backwards compatibility. The way around this is to write a lot of envelopes with short horizontal segments before the release which just seems needlessly fussy:
aenv  linsegr  1, 0.01, 1, 0.2, 0

**Comment by Oeyvind** [comment] 2016-03-03 11:41
Actually, the issue I reported with linsegr is triggered if only iz is
missing (and irel is present). So, using linsegr with an even number of
arguments triggers the unwanted behaviour (release stage cuts off
unexpectedly).
Iain's use (3 arguments) can actually be allowed with no problems. We can
trigger the init error only if the number of arguments is even.

2016-03-03 12:12 GMT+01:00 iainmccurdy <notifications@github.com>:

**Comment by iainmccurdy** [comment] 2016-03-03 11:53
That makes sense that 2 arguments will be a problem. I was experiencing the error with 3 arguments (with Cabbage).

**Comment by vlazzarini** [comment] 2016-03-03 12:38
well, it looks like checking for odd arg number is broken. I'll see what I can do.

**Comment by vlazzarini** [comment] 2016-03-03 12:48
btw, the error check was only in linsegr, and I have removed it now. But the odd arg checking still needs
to be fixed.

**Comment by vlazzarini** [comment] 2016-03-03 14:12
Now the odd arg check is back in place causing an init error if an even number is given.

**Comment by Oeyvind** [comment] 2016-03-03 22:21
Excellent. linsegr now fulfills our collected wishes.
Since there has been a lot of developments on this issue, I will now sum up
the remaining unsolved issues. Tested with a build from develop branch
March 3 at 23:00 hours

* madsr - init error: length of ADSR note too short, even if p3 >
atttack+decay - would it perhaps be even better if it gracefully performed
release from the value reached (by partial
attack or decay stage) when p3 expires?
* mxadsr does this (graceful release from value reached) * envlpxr, still
untouched, repeating original report: - manual mentions that iatss is
dependent on duration. It is unclear what this means. It seems it was
written to explain how evlpx works, but this does not apply to envlpxr,
since the duration is not known. - if the opcode is used with a rise shape
that does not have an extended guard point, the error message is "rise func
ends with zero". Could the error message mention the possibility that this
was caused by a missing guard point? - behaves oddly if the duration of the
attack segment does not fit within the note duration (skips release stage).
It should ideally produce the release stage from the value reached by the
attack segment
(even if attack segment does not complete during event duration).
* adsr - adsr prints an error if note duration is too short, this may be
ok, but see the comments on xadsr
* xadsr
- xadsr gracefully provides release segment from value reached *if* attack
segment has time to
complete (this is good) - xadsr skips attack stage if note duration too
short to complete it (no printed warning)

* linen shows similar behaviour to what is reported here on xadsr
* envlpx shows similar behaviour to xadsr and linen, but will also truncate
release



2016-03-03 15:12 GMT+01:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment] 2016-03-03 23:02
I thought I had fixed linen to do what it says on the manual. Is that still
not right?

**Comment by Oeyvind** [comment] 2016-03-04 08:09
Sorry, it still skips the decay stage if note duration is less than the
attack time.
See the audio file created by this example (the first note has fade in but
no fade out).
<CsoundSynthesizer> <CsOptions> </CsOptions> <CsInstruments> sr = 48000
ksmps = 64 0dbfs = 1 giSine ftgen 0, 0, 65536, 10, 1 ; sine wave instr 1
iamp = ampdbfs(p4) icps = cpsmidinn(p5) iattack = 0.5 irel = 0.5 amp linen
1, iattack, p3, irel a1 oscili amp*iamp, icps, giSine out a1 endin
</CsInstruments> <CsScore> ; start dur amp note i1 0 0.2 -10 72 i1 1 0.7 .
. i1 3 1.2 . . i1 5 2.2 . . f0 8 e </CsScore> </CsoundSynthesizer>



2016-03-04 0:02 GMT+01:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment] 2016-03-04 08:29
but afaik that had always been the behaviour, changing it might break other code. Unless it is shown that this is not the case, I don't think it can be changed. But I might be mistaken and the behaviour could have been as you described.

**Comment by Oeyvind** [comment] 2016-03-04 08:40
I'm not 100% sure what would be the best way to handle it. I see the point
in backwards compatibility even for errors. Still, the envelope produced by
the first note in the example produce very prominent clicks, which by any
judgement must be considered a glitch or an artifact that a composer in
most circumstances will want to have very specific control over. As it
works now, it is quite random (depending on note duration relative to
attack time) if we get a  click at the *end* of the note. I have
experienced these artifacts myself, in algorithmically generated passages,
which is one of the reasons I wanted to do a proper round-up of all the
envelope generators.
In any case, if we should go by the manual, it says
"If *linen* rise and decay periods overlap then both modifications will be
in effect for that time"
and this is not what happens with the current implementation (on note
durations shorter than the attack time).
The optimal solution can be debated, but I think there are strong reasons
to update the opcode to work in accordance with the manual.

2016-03-04 9:29 GMT+01:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment] 2016-03-04 09:44
I looked at the code, and the situation is this:

1) if attack and decay overlap, then they get added together
2) if decay is longer than the duration, it gets skipped.

So it is not the attack time that makes the difference, but the decay, which has to be always less than the total duration. The manual says "an idec > idur will cause a truncated decay", which is not what happens here. Attack = 0 and idec > idur causes no envelope shaping. I need to fix this.

**Comment by vlazzarini** [comment] 2016-03-04 09:55
I've push a version that truncates the decay as per the manual.

**Comment by Oeyvind** [comment] 2016-03-04 10:53
Tested here, and agree that this is a good solution. Should we also print a
warning when idec>idur ?

2016-03-04 10:55 GMT+01:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment] 2016-03-04 11:22
Maybe. I'd like to hear more opinions on this.

**Comment by vlazzarini** [comment] 2016-03-10 08:47
We need to close this ticket before we prepare the release. So:

1) for ADSR - XADSR, should we just have a warning?
2) envlpx should stay as it is or not? 
3) Is madsr broken?
4) Is envlpxr broken?

Anything else?

**Comment by Oeyvind** [comment] 2016-03-11 08:49
Here's a summary of what needs to be done, based on recent discussion, and
my testing if the current implementation (with a Csound build of March 7,
on windows).

1. linen:
We should print a warning when idec>idur

2. adsr:
We could print a warning instead of the init error if p3 < envelope_dur (it
seems some users are in favor of this option)

3. xadsr:
currently works differently than adsr regarding what happens on short notes
It skips the attack stage if note dur < iatt+irel, but otherwise performs
the envelope gracefully.

4. envlpx:
Currently cuts off the decay stage if duration is shorter than rise+decay.
The manual states:
'''Rise modifications are applied for the first irise seconds, and decay
from time idur - idec. (...) If rise and decay periods overlap then both
modifications will be in effect for that time.'''
It seems like the decay stage is truncated if attack and decay stages
overlap (or rather, the do not overlap, so there is not enough time to
finish the decay stage).
It also seems like the decay stage is skipped altogether if duration is
shorter than decay time.

5. envlpxr:
Note duration is not extended (no release stage) if note duration is
shorter than decay duration. This effectively also skips the decay stage of
the envelope.

6. madsr
Currently has an init error if p3 < envelope_dur. This probably comes from
the adsr implementation. The manual states that madsr is using the linsegr
mechanism, and this would be a better solution than the current one (as it
would gracefully allow shorter notes).

7. linenr, linsegr, mxadsr, expsegr, transegr, cossegr: ALL OK.

2016-03-10 9:47 GMT+01:00 vlazzarini <notifications@github.com>:

**Comment by kunstmusik** [comment] 2016-03-12 17:36
I went to compose today for the first time in a while and got:

INIT ERROR in instr 1 (opcode yi_env_orch): length of ADSR note too short

This is for calls to madsr and has broken my piece.  I suspect it will have broken older pieces of mine too. I have disabled the duration check when madsr is called, restoring the older behavior.

**Comment by Oeyvind** [comment] 2016-03-14 19:34
I see this issue has created a mess of opposing opinions and actions. I am
sorry for this. Still it *was* a mess the way it worked with the old
behaviour. The artifacts created with too short notes were different for
different envelope opcodes, and in many cases would create undesirable
artifacts with no indication as to why/how they originated. As this can be
a great pain with complex orchestras, where the artifact couls have
originated in many places, I found it appropriate to report and try to fix.
Please, if restoring the old behaviour, *do* print a warning when note
duration is too short to complete the full envelope. This way, at least the
composer can have an option to fix the root of the problem (his or her
specification of shorter notes than his or her specified envelope duration).

2016-03-12 18:36 GMT+01:00 Steven Yi <notifications@github.com>:

**Comment by kunstmusik** [comment] 2016-03-14 20:00
For madsr, I do not think there should be a warning in the scenarios for the notes I was using.  The note times were greater than attack_time + decay_time, but less than a + d + release, which the adsr check was doing.  This should be a valid scenario, as release is extra time beyond the note duration.  The old behavior worked fine for madsr, as any it uses a more real-time model for envelope generation dependent upon a turn-on/turn-off of a note.  An analog envelope generator would also behave similarly even if the duration between note on and note off is less than the attack + decay times.  I would rather not see warnings printed for madsr for my scores as it would occur on many notes, as I am using long release times.

**Comment by Oeyvind** [comment] 2016-03-14 22:15
I do agree that note duration longer than attack+decay time should not
produce an error and not even a warning. I just reacted to your statement
that you restored the older behaviour, as it was not entirely clear for me
what you meant. So now it will give an init error only if p3 is less than
attack+decay? This would be fine.
As it is I can not test because I can not build (windows mingw64 build
requirements has become a quite messy in comparision to just a week ago
when I last built).

2016-03-14 21:01 GMT+01:00 Steven Yi <notifications@github.com>:

**Comment by kunstmusik** [comment] 2016-03-15 16:05
The old behavior was restored only for madsr.  I have not touched any other
changes, nor have I added any checks at all for madsr.  So it will not give
any errors or warnings at all for madsr.

**Comment by rorywalsh** [comment] 2016-04-04 16:20
Where are we on this problem? A lot of Iain's instruments are still broken which is a pity as they represent a huge number of the examples that ship with both CsoundQT and Cabbage. Can we remove all new INIT errors that resulted from these code changes and replace them with a warnings instead? Or in the case of there being no release segments(which is what I'm seeing most often), can Csound simply add one to make it valid? A note could be put in the manual to that effect: 

"Failure to add a valid release segment will result in Csound adding one for you, which may result in unexpected behaviour"

I know much of the offending code is not semantically correct, but we are talking about some opcodes that have been in Csound since the very start. There is no telling how many instruments may be broken as a result.

**Comment by rorywalsh** [comment] 2016-04-09 20:30
Iain's instrument now seem to be working without issue. I've only checked a few, but it looks good.

**Comment by Oeyvind** [comment] 2016-04-10 17:51
I'm ok with the current behaviour except one thing:
envlpxr does not extend the note duration with the r-segment *if p3<irise*,


2016-04-09 22:30 GMT+02:00 Rory Walsh <notifications@github.com>:

**Comment by jpffitch** [comment] 2016-04-22 14:26
I am still confused.  i understand only xdsr and envlpx have problems now?  Is tat the case and please, an example on which to work

**Comment by jpffitch** [comment] 2016-04-26 16:34
xadsr now gives a warning.  envlpx is original code.

So that leaves envlpxr?

**Comment by Oeyvind** [comment] 2016-04-26 21:05
Yes, envlpxr is missing the release segment when note duration is less than
iattack.
See example below.

Also, it would be nice to also print warnings when note duration is too
short for linen and envlpx (like for xadsr etc)

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 64
0dbfs = 1

giSine  ftgen 0, 0, 65536, 10, 1 ; sine wave
giRise  ftgen   0, 0, 4097, 7, 0, 4096, 1       ; rising line

instr 1
        iamp    = ampdbfs(p4)
icps    = cpsmidinn(p5)
        iattack = 0.5
        irel    = 0.5
; missing release segment when note duration is less than  iattack
        amp envlpxr 1, iattack, irel, giRise, 0.9, 0.01

a1 oscili amp*iamp, icps, giSine
out a1
endin


</CsInstruments>
<CsScore>
; start dur amp     note
i1 0 0.2     -10     72
i1 1 0.7     .       .
i1 3 1.2     .       .
i1 5 2.2     .       .
f0 8
e
</CsScore>
</CsoundSynthesizer>


2016-04-26 18:34 GMT+02:00 John ffitch <notifications@github.com>:

**Comment by jpffitch** [comment] 2016-04-28 14:28
i think I have fixed it -- treat with care

**Comment by Oeyvind** [comment] 2016-04-28 20:06
Excellent. This solution works nicely.

Now the only thing missing is a warning for linen and envlpx, like the one
we have for adsr.
Then we are all good with envelopes.

2016-04-28 16:28 GMT+02:00 John ffitch <notifications@github.com>:

**Comment by jpffitch** [comment] 2016-04-29 14:31
Not sure about this but I have added warnings to linen and envlpx -- not sure they check what you want though

**Comment by Oeyvind** [comment] 2016-05-02 11:27
I tested now and could see no warnings for linen and envlpx.

For linen, there should be a warning if p3 < irise (or idec, whichever is
greatest)

For envlpx there should be a warning if p3 < (irise+idec) from how I can
see it is working now.
Actually, the manual says both the rise and decay segments should be in
effect simultaneously if they overlay, but this seems not to be the case.
See the second event in the attached csd, where the output amplitude does
not end in zero. If the decay segment was indeeed in effect during the last
idec seconds, then the amplitude should have dropped to zero by the end of
the event. The behaviour has been like this earlier, so it should probably
not be changed(?) but then the manual should be changed (the sentence " If
rise and decay periods overlap then both modifications will be in effect
for that time.") and we should print a warning when p3 < (irise+idec)

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 64
0dbfs = 1

giSine  ftgen 0, 0, 65536, 10, 1 ; sine wave
giRise  ftgen   0, 0, 4097, 7, 0, 4096, 1       ; rising line

instr 1
        iamp    = ampdbfs(p4)
icps    = cpsmidinn(p5)
        iattack = 0.5
        idecay  = 0.5
        isust   = 0.5
        irel    = 0.5

;amp adsr iattack, idecay, isust, irel
;amp xadsr iattack, idecay, isust, irel
;amp linen 1, iattack, p3, irel
        amp envlpx 1, iattack, p3, irel, giRise, 0.9, 0.01

a1 oscili amp*iamp, icps, giSine
out a1
endin


</CsInstruments>
<CsScore>
; start dur amp     note
i1 0 0.2     -10     72
i1 1 0.7     .       .
i1 3 1.2     .       .
i1 5 2.2     .       .
f0 8
e
</CsScore>
</CsoundSynthesizer>



2016-04-29 16:31 GMT+02:00 John ffitch <notifications@github.com>:

**Comment by vlazzarini** [comment] 2016-05-02 11:52
I agree. The manual does not correspond to the code as originally designed. It might have been that the intention was to have it working like linen, but the implementation was wrong. Since it's been like that for 30 years (or longer, it might go back to MUSIC 11), we should change the manual.

**Comment by jpffitch** [comment] 2016-05-09 12:12
I have changed the checks in linen and envlpx; please check.

**Comment by Oeyvind** [comment] 2016-05-12 20:41
I checked just now, and can't see any new warnings.
I pulled from develop an built here. Strange. Does it produce warnings on
your system John?

The following csd should provoke a warning about too short note for the
first note in the score.

If you uncomment the envlpx line instead of the linen line, then we should
have a warning for the two first note instances in the score, since we lso
want a warning if p3 < (irise+idec).


<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 64
0dbfs = 1

giSine  ftgen 0, 0, 65536, 10, 1 ; sine wave
giRise  ftgen   0, 0, 4097, 7, 0, 4096, 1       ; rising line

instr 1
        iamp    = ampdbfs(p4)
icps    = cpsmidinn(p5)
        iattack = 0.5
        idecay  = 0.5
        isust   = 0.5
        irel    = 0.5

;amp adsr iattack, idecay, isust, irel
;amp xadsr iattack, idecay, isust, irel
amp linen 1, iattack, p3, irel
        ;amp envlpx 1, iattack, p3, irel, giRise, 0.9, 0.01

a1 oscili amp*iamp, icps, giSine
out a1
endin


</CsInstruments>
<CsScore>
; start dur amp     note
i1 0 0.2     -10     72
i1 1 0.7     .       .
i1 3 1.2     .       .
i1 5 2.2     .       .
f0 8
e
</CsScore>
</CsoundSynthesizer>


2016-05-09 14:12 GMT+02:00 John ffitch <notifications@github.com>:

**Comment by jpffitch** [comment] 2016-05-13 10:15
For linen you asked tar the ceck was p3 against max(rise,decat).  Your 
exampes has

**Comment by jpffitch** [comment] 2016-05-13 10:28
I had only chaged te k-rate envelopes -- arate added now

**Comment by Oeyvind** [comment] 2016-05-13 11:09
Excellent. All good now. Thank you, John.

2016-05-13 12:28 GMT+02:00 John ffitch <notifications@github.com>:

**Closed** 2016-05-13 11:14 UTC
Labels: bug
