### ISSUE TITLE
faust opcodes fail with 'Illegal Instruction' error followed by segfault

### ISSUE THREAD

**Issue by ranch-verdin** [csound/csound#1137] opened 2019-04-14 13:11 UTC
I am trying to use csound and faust to create a minimal OSC-controlled synthesizer host for embedded linux (raspberry pi based platform).

However I'm having trouble getting a working example demonstrating use of the faust opcodes.  I have read all the documentation and examples I could find and produced an example file: https://gist.github.com/ranch-verdin/e0d1f13032efecc4f93e94430265f450.  However, when I try to run this I get the following error messages:

csound command: Illegal instruction

csound command: Segmentation fault

Would anyone be so kind as to help me establish if this is a bug with the opcodes or with my example code?

Really hope to get this up and running, csound looks like the perfect companion to faust for my application!

**Comment by vlazzarini** [comment] 2019-04-14 13:25
can you copy here all messages from
Csound so we can have a look?

Did you build the faust opcodes yourself?

**Comment by ranch-verdin** [comment] 2019-04-14 13:37
System where this is observed:

OS: arch linux x86_64.  Just ran pacman -Syu this afternoon.

csound and faust are installed via pacman -S, not from source.

Here is a gist showing full cmdline output (both with and without -v flag) and also have thrown in there the version numbers for all relevant packages (llvm, faust, csound)

https://gist.github.com/ranch-verdin/3385d22cdc432c0a922e0e9d1c6eee79

**Comment by vlazzarini** [comment] 2019-04-14 15:15
Thanks. Not sure what the problem is, but maybe there is something wrong with the faust opcodes build in your version. Maybe you could comment out the "faustaudio" line and see if that is what is crashing
the code.

In any case, your code is fine and it runs OK in OSX:

```
MacBook-Pro:~ victor$ csound src/csound/debug/faustop.csd 
0dBFS level = 32768.0
--Csound version 6.12 (double samples) Nov  3 2018
[commit: bc81dfb2877c7302d7f4849c098a1f88cf3f60d7]
libsndfile-1.0.28
UnifiedCSD:  src/csound/debug/faustop.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.005s, CPU: 0.003s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.005s, CPU: 0.003s
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Feb 12 2010 09:42:54)
   0: dac0 (Built-in Output [Core Audio])
   1: dac1 (Soundflower (2ch) [Core Audio])
   2: dac2 (Soundflower (64ch) [Core Audio])
   3: dac3 (Aggregate Device [Core Audio])
PortAudio: selected output device 'Built-in Output'
writing 2048 sample blks of 64-bit floats to dac
SECTION 1:
ftable 1:
ftable 1:	1024 points, scalemax 1.000
               .-''''''-._
            _-'           '.
          _-                '.
         -                    '_
       .'                       -
      -                          '_
    _'                             .
   .                                -
  -                                  '_
_'_____________________________________._______________________________________
                                        -                                     .
                                         -                                   -
                                          '_                               _'
                                            .                             .
                                             -                           -
                                              '.                       _'
                                                -_                    -
                                                  -_                .'
                                                    -_           _.'
                                                      '-._____..'
new alloc for instr 1:
B  0.000 ..  2.000 T  2.000 TT  2.000 M:  0.59988  0.59988
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  0.59988  0.59988
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 2.190s, CPU: 0.292s
closing device
87 2048 sample blks of 64-bit floats written to dac
```

**Comment by ranch-verdin** [comment] 2019-04-15 08:14
thanks for testing on your setup.  I can confirm the line which crashes the program is the one containing "faustaudio". What llvm version and faust version are you using?

Planning to create a minimal testcase for libfaust, isolated from csound and jack in order to further debug the issue.

I assumed the instructions in BUILD.md are out of date as regards the faust opcodes.  In particular, assumed that the requirement to use llvm 3.0 - 3.4 is no longer correct.  Has anyone tested with llvm 8.0?  The current build instructions for libfaust say llvm 3.8 or higher required.  https://github.com/grame-cncm/faust/blob/master-dev/build/README.md

**Comment by vlazzarini** [comment] 2019-04-15 10:17
My version of faust here is 2.4.13 (I don't update it very often), llvm-config says 3.7.1. That is what the version of the opcodes as packaged for MacOS uses in the latest release (6.12).

The BUILD.md is quite possibly out of date. Faust is a bit of a moving target as they don't do releases and often there are changes that break our build.

I suppose I ought to try this on Linux. I have Debian here on a VM and I can try it later.

**Comment by vlazzarini** [comment] 2019-04-15 11:38
I've updated my llvm and faust, and your code runs OK. MacOS with the latest Csound (6.13 beta).

**Comment by ranch-verdin** [comment] 2019-04-15 12:12
I also tried the faust Chuck support on my system and also seems broken. So best guess at the moment libfaust is basically broken on arch Linux.

Somewhere in the Faust docs it says llvm5 is known-working on all platforms, but Arch no longer provides this from official repos.

Don't suppose you might already have a simple libfaust example program already lying around for a minimal test case before posting an issue on Faust's GitHub?

**Comment by ranch-verdin** [comment] 2019-04-16 12:34
OK I have root-caused the issue.  Think what is happening is that faust's default llvm target is generating machine code instructions which are incompatible my cpu (celeron 2995u - I'm travelling with a linux chromebook).  I was able to get csound faust opcode working with the following patch:
```
diff --git a/Opcodes/faustgen.cpp b/Opcodes/faustgen.cpp
index 724529f33..f9367ecdd 100644
--- a/Opcodes/faustgen.cpp
+++ b/Opcodes/faustgen.cpp
@@ -292,7 +292,7 @@ void *init_faustcompile_thread(void *pp) {
   csound->LockMutex(p->lock);
   // csound->Message(csound, "lock %p\n", p->lock);
   factory = createDSPFactoryFromString("faustop", (const char *) ccode,
-                                       argc, argv, "", err_msg, 3);
+                                       argc, argv, "x86_64:generic", err_msg, 3);
   // csound->Message(csound, "unlock %p\n", p->lock);
   csound->UnlockMutex(p->lock);
 ```
Not sure how to condense this into a pull-request for faust maintainers - I leave it up to you whether you want to handle this as an edgecase in csound.  Seems like something that should be taken care of by libfaust tbh...  Quite the landmine!

**Comment by vlazzarini** [comment] 2019-04-16 14:14
maybe I can look into an extra optional parameter to handle this. Thanks for the detective work.

**Comment by ranch-verdin** [comment] 2019-04-20 08:29
FWIW, this problem is not reproducible on Xeon workstation.  Explains why faust maintainers closed the issue without comment.

**Comment by vlazzarini** [comment] 2019-04-20 08:41
Closing the issue without comment is not good form imho

**Comment by vlazzarini** [comment] 2019-04-23 15:57
So I've added an extra optional parameter to faustcompile

```
ihandle faustcompile Scode, Sargs[,iasync, istacksize, Starget]
```

to solve your issue. Is there any chance you can try this?

**Comment by jpffitch** [comment] 2019-07-06 20:34
Is this issue OK now?

**Comment by ranch-verdin** [comment] 2019-07-06 23:18
Ah, sorry @vlazzarini, somehow missed your comment on the extra parameter workaround. Will have a look when I'm back at home tomorrow.

**Comment by kunstmusik** [comment] 2019-09-15 03:43
Assuming this issue is fixed due to any reply.  Closing now, though if this is still an issue please request to reopen, thanks.

**Closed by kunstmusik** 2019-09-15 03:43 UTC
