### ISSUE TITLE
Sometimes very poor sound quality with v6.09.1

### ISSUE THREAD

**Issue by pdrezet** [csound/csound#850] opened 2017-09-13 10:55 UTC
After upgrading from csound v5.12 to v6.09.1, which I have built for linux (debian Jessie), some scores now play with substantial distortion (more precisely a high frequency drone sound that is modulated by instrument's volume).

The build variant is for 32bit (single precision) float. When built for double the issue does not occur.The score uses 22.05KHz sample rate and sounds are played from wav file, which are formatted at 22.05KHz

I require 32bit float and lower sample rates for real-time playout (using alsa) on memory limited x86 devices.

This issues seems specific to only some scores, which are not substantially different to others that play fine.

What has changed in csound since v5.12 that may cause this?

**Comment by kunstmusik** [comment] 2017-09-13 11:13
There's been many changes since Csound 5, literally years worth, so this
may take some investigation to determine if the problem is specific to
certain opcodes or is a system issur. Do you have a test CSD that
demonstrates the problem?

**Comment by pdrezet** [comment] 2017-09-13 13:11
I will try to find a smaller (in MBs) example to reproduce this issue. 
I'v just tested with the prebuilt Debian v6.09.1 with double float and the same issue occurs, hence I've changed the title.

**Comment by jpffitch** [comment] 2017-10-15 19:29
Is this still a problem with 6.10?

**Comment by kunstmusik** [comment] 2017-12-28 20:46
Closing: Issue seems out of date and no tests available.  Assume that this may be related to loscil or other issue fixed in 6.10.  If not fixed in 6.10, please reopen or file new issue.

**Closed by kunstmusik** 2017-12-28 20:46 UTC
