### ISSUE TITLE
Inaccurate calculation of duration in sequ when ksmps != 1

### ISSUE THREAD

**Issue by TetsuyaMiwa** [csound/csound#1692] opened 2023-02-14 11:25 UTC
When the note duration is modified with _irhythm_, the actual duration is not accurate when ksmps != 1.
The code attached below shows this issue.
Checked with Csound ver 6.18 on MacOS(Intel MacBook Pro).

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32 ;Out of sync
;ksmps = 1 ;Sync
nchnls = 2
0dbfs = 1

instr 1 
kenv madsr 0.01, 0.1, 0.2, 0.1
asig oscili kenv, cpspch(8+p4/100)
outall asig*0.3
endin

instr 2
irhythm1[] fillarray 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
iinstr1[]  fillarray 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
inote1[]   fillarray 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

irhythm2[] fillarray 1,1,1,1,1,1,1,1,2,2,2,2
iinstr2[]  fillarray 1,1,1,1,1,1,1,1,1,1,1,1
inote2[]   fillarray 0,1,2,3,4,5,6,7,8,10,12,14

kSeq1 sequ irhythm1, iinstr1, inote1, 480, 16
kSeq2 sequ irhythm2, iinstr2, inote2, 480, 12
endin
</CsInstruments>
<CsScore>
i2 0 40
</CsScore>
</CsoundSynthesizer>
```

**Comment by kunstmusik** [comment] 2024-01-02 20:55
(Requesting @jpffitch to evaluate.)

**Comment by jpffitch** [comment] 2024-01-18 15:04
Part of the problem is that your instr2 runs after any instr1 cases in any kcycle.  If you changed your numbering to swap 1 and 2 that problem would be less.

That is not the only problem and I am still pursuing leads

**Comment by jpffitch** [comment] 2024-02-02 19:37
I think I hve it fixed.  Vlassc fencepost problem

**Comment by jpffitch** [comment] 2024-02-03 20:51
Committed to develop and csound6

**Closed by jpffitch** 2024-02-03 20:51 UTC

**Comment by TetsuyaMiwa** [comment] 2024-02-04 06:40
Thank you so much!
