### ISSUE TITLE
[bug] 6.10 crash when recompiling named instrument

### ISSUE THREAD

**Issue by boonier** [csound/csound#963] opened 2018-05-25 14:35 UTC
I seem to get consistent crashes when re-evaluating the `instr 6, Bink` instrument in the following code. When removing the names from the instr all is well. 

I'm on macOS 10.12.6, Csound 6.10, CsoundQT 0.9.5.1

```<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1.0

giDist1	ftgen 0, 0, 257,  9, 1,3,0, 3,1,0, 9,0.333,180

schedule 3, 0, -1

instr 3, Seq
	kTrig metro 120/60
	if kTrig == 1 then
		kCntLoop = 0
		while kCntLoop < 3 do				
				
			event "i", 6, 0, 12, random:k(36,48) + 24
			kCntLoop += 1	
		od
	endif
endin

instr 6, Bink
	idur 		= p3
	ifrq 		= cpsmidinn(p4)

	kDistAmp	= .9
	kDistAmp 	port kDistAmp, 0.25
	kdist 	linen kDistAmp, idur*.1, idur, idur*.9
	
	asin 		poscil .1, ifrq

	aout 		distort asin, kdist, giDist1
	aenv 		expon 1, idur, 0.0001
	amix 		= aout * aenv
	
		outs amix, amix
		
endin

</CsInstruments>
<CsScore>

</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment] 2018-05-25 14:44
Works for me on latest version from git, apart from the out-of-range 
outputs.

Or do I not know what you mean by "re-evaluating the instr 6, Bink" ?

**Comment by vlazzarini** [comment] 2018-05-25 14:45
He means re-compiling the instrument while Csound  is running.

**Comment by boonier** [comment] 2018-05-25 16:25
> He means re-compiling the instrument while Csound is running.

yes that exactly, sorry if I wasn't clear @jpffitch 

thanks

**Comment by jpffitch** [comment] 2018-05-25 17:22
I can reproduce and under gdb

#0  insprep (csound=csound@entry=0x8b24a0, tp=tp@entry=0xb8d830,
     engineState=engineState@entry=0x8b2de0)
     at /home/jpff/csound6/Engine/csound_orc_compile.c:1877
#1  0x00000000004cc92f in engineState_merge (csound=csound@entry=0x8b24a0,
     engineState=engineState@entry=0xb856c0)
     at /home/jpff/csound6/Engine/csound_orc_compile.c:1410
#2  0x00000000004ccc72 in merge_state (csound=0x8b24a0, 
engineState=0xb856c0,
     typetable=0xb68f40, ids=0x0)
     at /home/jpff/csound6/Engine/csound_orc_compile.c:1474
#3  0x00000000004cef9c in csoundCompileTreeInternal (
     csound=csound@entry=0x8b24a0, root=root@entry=0xb85590,
     async=async@entry=0) at 
/home/jpff/csound6/Engine/csound_orc_compile.c:1744
#4  0x00000000004cf8c6 in csoundCompileOrcInternal (csound=0x8b24a0,
     str=0x60a700 "instr 6, Bink\n        idur", ' ' <repeats 12 times>, "= 
p3\n        ifrq", ' ' <repeats 12 times>, "= cpsmidinn(p4)\n 
kDistAmp        = .9\n        kDistAmp        port kDistAmp, 0.25\n 
kdist   linen kDistAmp, idur*.1, idu"..., async=0)
     at /home/jpff/csound6/Engine/csound_orc_compile.c:1839



1872        OENTRY* pset = find_opcode(csound, "pset");
1873
1874        optxt = (OPTXT *)tp;
1875        while ((optxt = optxt->nxtop) != NULL) {    /* for each op in 
instr */
1876          TEXT *ttp = &optxt->t;
1877          ep = ttp->oentry;
1878
1879          if (strcmp(ep->opname, "endin") == 0      /*    (until 
ENDIN)     */
1880              || strcmp(ep->opname, "endop") == 0) break;
1881          if (strcmp(ep->opname, "$label") == 0) {
(gdb)
1882            continue;
1883          }
1884
1885          if (UNLIKELY(O->odebug))
1886            csound->Message(csound, "%s args:", ep->opname);
1887          if ((outlist = ttp->outlist) == NULL || !outlist->count)
1888            ttp->outArgs = NULL;
1889          else {
1890            n = outlist->count;
1891            argp = outlist->arg;                    /* get outarg 
indices */

(gdb) print ttp
$1 = (TEXT *) 0xd

(gdb) print optxt
$2 = (OPTXT *) 0x5

**Comment by jpffitch** [comment] 2018-05-25 17:26
Suspicion falls on it is allocating a new number for bink -- as 4 
but on recompilation is 5

**Comment by vlazzarini** [comment] 2018-05-26 00:07
This is now fixed in git develop. Tested in CsoundQT as well.

**Closed by vlazzarini** 2018-05-26 00:07 UTC

**Comment by boonier** [comment] 2018-05-26 15:03
Awesome thanks!
