### ISSUE TITLE
interp and a() from starts != 0

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#558] opened 2015-11-22 17:29 UTC
i want to use interp from start indices different from zero and get strange results for the first ksmps values. (the same for a().)
this is an example:

ksmps = 32
giTab ftgen 0, 0, 256, 10, 1
giInterp ftgen 0, 0, 256, 2, 0

instr 4
 /* interp with different start values */
 ;write to giInterp
 kIndxIpW init p4
 while kIndxIpW < ftlen(giTab) do
  kIndxIpW += ksmps
  aPnter interp kIndxIpW
  aSig table aPnter, giTab
  ;fout "/home/jh/Desktop/interp.wav", 18, aSig
  tablew aSig, aPnter, giInterp
 od
 ;read from giInterp / compare with giTab
 kIndxIpR init p4
 while kIndxIpR < ftlen(giTab) do
  kTabVal table kIndxIpR, giTab
  kInterpVal table kIndxIpR, giInterp
   printf "Index = %d: kTabVal = %f, kIntpVal = %f, kDiff = %f\n", 
     kIndxIpR+1, kIndxIpR, kTabVal, kInterpVal, kTabVal-kInterpVal
  kIndxIpR += 1
 od
 turnoff
endin
;schedule(4,0,.1,0) ;fine
schedule(4,0,.1,128) ;wrong for the first ksmps values

the output is:
Index = 128: kTabVal = 0.000000, kIntpVal = 0.000000, kDiff = 0.000000
Index = 129: kTabVal = -0.024541, kIntpVal = 0.000000, kDiff = -0.024541
Index = 130: kTabVal = -0.049068, kIntpVal = -0.049068, kDiff = 0.000000
Index = 131: kTabVal = -0.073565, kIntpVal = 0.000000, kDiff = -0.073565
Index = 132: kTabVal = -0.098017, kIntpVal = 0.000000, kDiff = -0.098017
Index = 133: kTabVal = -0.122411, kIntpVal = 0.000000, kDiff = -0.122411
Index = 134: kTabVal = -0.146730, kIntpVal = 0.000000, kDiff = -0.146730
Index = 135: kTabVal = -0.170962, kIntpVal = -0.170962, kDiff = 0.000000
Index = 136: kTabVal = -0.195090, kIntpVal = 0.000000, kDiff = -0.195090
Index = 137: kTabVal = -0.219101, kIntpVal = 0.000000, kDiff = -0.219101
Index = 138: kTabVal = -0.242980, kIntpVal = 0.000000, kDiff = -0.242980
Index = 139: kTabVal = -0.266713, kIntpVal = 0.000000, kDiff = -0.266713
Index = 140: kTabVal = -0.290285, kIntpVal = -0.290285, kDiff = 0.000000
Index = 141: kTabVal = -0.313682, kIntpVal = 0.000000, kDiff = -0.313682
Index = 142: kTabVal = -0.336890, kIntpVal = 0.000000, kDiff = -0.336890
Index = 143: kTabVal = -0.359895, kIntpVal = 0.000000, kDiff = -0.359895
Index = 144: kTabVal = -0.382683, kIntpVal = 0.000000, kDiff = -0.382683
Index = 145: kTabVal = -0.405241, kIntpVal = -0.405241, kDiff = 0.000000
Index = 146: kTabVal = -0.427555, kIntpVal = 0.000000, kDiff = -0.427555
Index = 147: kTabVal = -0.449611, kIntpVal = 0.000000, kDiff = -0.449611
Index = 148: kTabVal = -0.471397, kIntpVal = 0.000000, kDiff = -0.471397
Index = 149: kTabVal = -0.492898, kIntpVal = 0.000000, kDiff = -0.492898
Index = 150: kTabVal = -0.514103, kIntpVal = -0.514103, kDiff = 0.000000
Index = 151: kTabVal = -0.534998, kIntpVal = 0.000000, kDiff = -0.534998
Index = 152: kTabVal = -0.555570, kIntpVal = 0.000000, kDiff = -0.555570
Index = 153: kTabVal = -0.575808, kIntpVal = 0.000000, kDiff = -0.575808
Index = 154: kTabVal = -0.595699, kIntpVal = 0.000000, kDiff = -0.595699
Index = 155: kTabVal = -0.615232, kIntpVal = -0.615232, kDiff = 0.000000
Index = 156: kTabVal = -0.634393, kIntpVal = 0.000000, kDiff = -0.634393
Index = 157: kTabVal = -0.653173, kIntpVal = 0.000000, kDiff = -0.653173
Index = 158: kTabVal = -0.671559, kIntpVal = 0.000000, kDiff = -0.671559
Index = 159: kTabVal = -0.689541, kIntpVal = 0.000000, kDiff = -0.689541
(the rest is ok then)

is this a bug or can't i expect interp to start interpolation from anywhere?

**Comment by vlazzarini** [comment] 2015-11-22 17:50
this might need a new parameter, or you can check whethet iskip works to set a start value. I have not looked at the code.

**Comment by joachimheintz** [comment] 2015-11-22 18:11
i have tested various combinations of iskip and imode but get no correct 
result.

**Comment by joachimheintz** [comment] 2015-11-23 23:24
i think this example shows the problem better:

instr 5 ;ksmps=8
 kIndx init p4
 while kIndx < 33 do
  kIndx += ksmps
  aIndx interp kIndx
  k1 vaget 0, aIndx
  k2 vaget 1, aIndx
  k3 vaget 2, aIndx
  k4 vaget 3, aIndx
  k5 vaget 4, aIndx
  k6 vaget 5, aIndx
  k7 vaget 6, aIndx
  k8 vaget 7, aIndx
  printf "kIndx = %d\n  aIndx = [%f, %f, %f, %f, %f, %f, %f, %f]\n", kIndx, kIndx, k1, k2, k3, k4, k5, k6, k7, k8
 od
 turnoff
endin
schedule(5,0,.1,16)

which returns for the first audio vector:
kIndx = 24
  aIndx = [3.000000, 6.000000, 9.000000, 12.000000, 15.000000, 18.000000, 21.000000, 24.000000]

so it starts always interpolation from zero, and not from the first kIndx value which is set (here as p4).

i think you are right that iskip (in imode=0) should have the effect i expect. but it does not (i tried 1 or 16 for iskip but always get the same result).

so maybe the bug is that iskip is not working as it should?

**Comment by vlazzarini** [comment] 2015-11-24 09:11
iskip does not do what you are thinking. It just prevents the state of interp being cleared, which means
that it would start from the last value in the previous performance of an instance. In the first alloc of
an instance, it does not do anything. 

interp works by interpolating the current value of the previous value and the current one (since it cannot
predict the future). The problem is what to do when we first start it, because we do not have a previous value. There are four options:

1) iskip=0, imode=0: we always start from zero (previous value is set 0)
2) iskip=1, imode=0: we start from the value held in the instance memory, after a new alloc this is 0,
but in subsequent performances reusing the instance, it will be whatever it was left at the end of the 
previous performance.
3) iskip=0, imode=1: we start from the current value, which means that the first block will be constant (no interpolation).
3) iskip=1, imode=1: we start from the current value, which means that the first block will be constant in the the first time we run the instance, but will interpolate from the last value held in memory to the current kvar value, then go on from there.

Here's the printouts with the four options. I am running two performances of the same instance so we can see the effect of iskip:

1) iskip=0,imode=0
```
new alloc for instr 5:
kIndx = 24
 aIndx = [3.000000, 6.000000, 9.000000, 12.000000, 15.000000, 18.000000, 21.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
  rtevent:	   T  0.100 TT  0.100 M:      0.0
kIndx = 24
 aIndx = [3.000000, 6.000000, 9.000000, 12.000000, 15.000000, 18.000000, 21.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
```

2) iskip=1, imode=0

```
new alloc for instr 5:
kIndx = 24
 aIndx = [3.000000, 6.000000, 9.000000, 12.000000, 15.000000, 18.000000, 21.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
  rtevent:	   T  0.100 TT  0.100 M:      0.0
kIndx = 24
 aIndx = [38.000000, 36.000000, 34.000000, 32.000000, 30.000000, 28.000000, 26.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
```
3)iskip=0, imode=1
```
new alloc for instr 5:
kIndx = 24
 aIndx = [24.000000, 24.000000, 24.000000, 24.000000, 24.000000, 24.000000, 24.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
  rtevent:	   T  0.100 TT  0.100 M:      0.0
kIndx = 24
 aIndx = [24.000000, 24.000000, 24.000000, 24.000000, 24.000000, 24.000000, 24.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
```

4)iskip=1,imode=1

```
new alloc for instr 5:
kIndx = 24
 aIndx = [3.000000, 6.000000, 9.000000, 12.000000, 15.000000, 18.000000, 21.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
  rtevent:	   T  0.100 TT  0.100 M:      0.0
kIndx = 24
 aIndx = [38.000000, 36.000000, 34.000000, 32.000000, 30.000000, 28.000000, 26.000000, 24.000000]
kIndx = 32
 aIndx = [25.000000, 26.000000, 27.000000, 28.000000, 29.000000, 30.000000, 31.000000, 32.000000]
kIndx = 40
 aIndx = [33.000000, 34.000000, 35.000000, 36.000000, 37.000000, 38.000000, 39.000000, 40.000000]
```

This behaviour is exactly as documented in the manual.

**Comment by joachimheintz** [comment] 2015-11-24 09:26
thanks for the detailed explanation!

so there is no way for what i wanted to do?  this is:
1. setting the first ("previous") k-value.
2. interp or a() would start the interpolation from here in the same way 
as they do from zero.

following your explanation this would go back to your first comment: to 
require an additional optional parameter.

if this is difficult to implement, i could go with setksmps=1.

**Comment by vlazzarini** [comment] 2015-11-24 09:31
I guess we could add a third optional i-time parameter to set a starting point for when iskip and imode are both 0.

**Comment by jpffitch** [comment] 2015-11-24 14:18
I have added a third optional arg as you suggest; not tested

**Comment by joachimheintz** [comment] 2015-11-25 22:44
i have tested the third optional input and it works perfectly in my example.
thanks john (and victor)!

**Comment by vlazzarini** [comment] 2015-11-26 08:09
OK closing this then.

**Closed by vlazzarini** 2015-11-26 08:09 UTC

**Comment by jpffitch** [comment] 2015-11-26 12:19
I will adjust the manual
