### ISSUE TITLE
MIDI CC Data Not Received by Widgets When Playing MIDI File with -F Option

### ISSUE THREAD

**Issue by sonochord** [csound/csound#1817] opened 2024-01-26 14:31 UTC
Hi 
I had this problem when I was doing a project for Victor Lazzarini's Csound module and he suggested I report the issue here.

I arranged the midi for my CsoundQT project in Pro Tools via IAC driver. CC was modulating lots of widgets and adjusting Instrument levels, etc..

CsoundQT fails to properly process MIDI CC data sent to widgets when playing a MIDI file using the -F option. This results in incorrect mixing and automation behaviour.

Widgets do not receive MIDI CC data when the MIDI file is played using the -F option in CsoundQT. This results in incorrect mixing and automation, differing from the output when sequenced directly via IAC Driver from Pro Tools or Reaper using -M.

I'm using a Macbook Pro M3, Operating System: Sonoma 14.1.2 (23B2091)

**Comment by vlazzarini** [comment] 2024-01-26 15:32
I now see the issue. Are you using the MIDI cc opcodes to intercept the MIDI data from the file or just widgets? I think if the latter is the case, then it's expected behaviour, it will not work.

CsoundQT has its own MIDI implementation that drives the widgets. It also sends the MIDI data to Csound. Csound can take that control from a Widget (via channel) or from MIDI CC directly.

The control you are getting from -M goes to the widgets via the CsoundQT backend, but data from -F comes from a file directly into Csound. You then need to use MIDI CC opcodes to pick that. This will work.  You can't use the midi data from a midi file to drive widgets directly because CsoundQT does not handle that. If you want to do this, you will need to code it with channels.

Can you try using MIDI CC opcodes instead of channels for that? If it doesn't work then we'll diagnose, if it does, then it is your answer there.

**Comment by sonochord** [comment] 2024-01-27 17:08
Thanks, Victor.
Yes. I had set it up in a way that the midi cc from IAC driver originating in Pro Tools or Reaper was driving the widgets and then the widgets were what was then sending the values to the csd using channels, chn_k, chnset for initialising the values and chnget to pass the value to instrument parameters.
Example:
`<CsInstruments>

sr = 44100
ksmps = 20
nchnls = 2
0dbfs = 1

;;channels
chn_k "Phaser",3
chn_k "AprsMod2",3
chn_k "ArpsMod1",3
//rest of channels etc.


;;INITIALISE CONTROLLERS
chnset		0.0001,	"Phaser"
chnset		300,		"ArpsMod1"
chnset		300,		"AprsMod2"
// rest of initialisation


;; Arpeggiator Synth
ga_fmod init 0
gisine ftgen	 0, 0, 65537, 10, 1  ;sine
instr	Arp
kLvl	chnget "ArpLevel"
inum	notnum
kfr   cpsmidib  
iamp ampmidi 0dbfs
iamp2 = iamp*0.7


//that kind of thing`
I'll try rewriting using MIDI CC opcodes and report back.

Fergal

**Comment by vlazzarini** [comment] 2024-01-27 18:40
Thanks. If the MIDI CC opcodes then we have the answer.

**Comment by sonochord** [comment] 2024-01-28 12:54
Hey.
It took a while to track down all of the midi channels, cc numbers, min and max values that were being looked after by the widgets but ctrl7 did the trick of bypassing the widgets.
Example:
"""
;; GRANULAR ORGAN INSTRUMENT 
instr Organ ; Stereo Partikkel with my Rap.wav
iamp ampmidi 0dbfs        // MIDI velocity to amp
kLvl init	1
kmod init 100

//kLvl chnget "OrganLvlcc9"
kLvl ctrl7 1,9,0.35,1    ; instead of chnget

//kmod chnget "OrganModcc11"
kmod ctrl7	1, 11, 0.35, 5   ; instead of chnget

kfr   cpsmidib     
kgrainfreq	= kfr	etc.

"""		
So that's fine. 

This is probably a big ask but wouldn't it be useful to have some way of piping the MIDI the csd reads from a MIDI file ( -F) directly into the Widgets in the same way the IAC seems to route directly to them?

I suppose the widgets are designed for live MIDI control but I liked being able to sequence in the DAW and visually see that the widgets were receiving the MIDI CC at least. 
I've created a diagram of what I think was my problem. 
![CsoundQT Midi Routing](https://github.com/csound/csound/assets/118268773/1aa7575c-8559-4a69-869f-9342d1ac61b2)

It's probably a major pain to have some master setting to turn off and on a MIDI pipe from the midi file playback to the widgets. It'd have to be the output of whatever part of CsoundQT actually plays the midi file.
Probably too much to ask:)

**Comment by vlazzarini** [comment] 2024-01-29 11:47
I agree it would be desirable. The situation is that MIDI device input comes into Csound via a backend and hosts like CsoundQT can implement their own backends instead of just relying on what Csound offers (with portmidi etc).
CsoundQT does that and adds (as a complement) control to their own widgets.

Now -F goes directly into Csound, hosts do not get involved in that. So the solution would be for a host to implement their own MIDI file reading so they can merge that with the device input, and instead of -F you just pass the MIDI file input to the host. You could ask this in the CsoundQT issue tracker: 
https://github.com/CsoundQt/CsoundQt/issues

I'll close this now, thanks for the report.

**Closed as completed by vlazzarini** 2024-01-29 11:47 UTC

**Comment by sonochord** [comment] 2024-01-29 11:54
Cheers Victor
