### ISSUE TITLE
pycall2 and above error in 6.08

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#730] opened 2016-12-16 01:17 UTC
pycall2 fails to return a value, complaining that the callable must return 2 values.
The callable does indeed return 2 values.

The same error happens with pycall3,4,5,6...

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

	pyinit
        pyruni {{
def get1(not_in_use):
    return float(123)
    
def get2(not_in_use):
    return float(1),float(2)
}}

instr 1
kndx init 0
ktrig metro 1
if ktrig > 0 then
k0 pycall1 "get1", kndx
k1,k2 pycall2 "get2", kndx
endif
printk2 ktrig
printk2 k0
printk2 k1,11
printk2 k2,12
endin

</CsInstruments>  
<CsScore>
i1 0 3
</CsScore>
</CsoundSynthesizer>
```

(fsateler: edited to format code)

**Comment by Oeyvind** [comment] 2016-12-16 01:17
The error happens in 6.08, but not in Csound 6.07

**Comment by vlazzarini** [comment] 2016-12-16 06:35
we nevet touched this code as far as I can remember,  so I don't really know what is the problem. I will try and look.

**Comment by vlazzarini** [comment] 2016-12-16 08:26
It works here on OSX:

```
new alloc for instr 1:
 i1     1.00000
 i1     123.00000
 i1     1.00000
 i1     2.00000
 i1     0.00000
 i1     1.00000
 i1     0.00000
 i1     1.00000
 i1     0.00000
```

at first I got errors, but they were because I had not indented the Python code properly.
Once I did that, it worked fine. But that's a different matter.

**Comment by fsateler** [comment] 2016-12-16 13:30
Maybe the opcodes got linked to python 3 in 6.08 and the API changed?

**Comment by vlazzarini** [comment] 2016-12-16 13:47
I wouldn't think that is the case here.

**Comment by fggp** [comment] 2016-12-16 13:55
I think that when building a release one has to be sure that Python 2.7 is
the default python interpreter. That's what I do on my system where Python
2.7 and Python 3.5 are installed.

François


Le 16 déc. 2016 14:47, "vlazzarini" <notifications@github.com> a écrit :

I wouldn't think that is the case here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/csound/csound/issues/730#issuecomment-267597326>, or mute
the thread

**Comment by vlazzarini** [comment] 2016-12-16 14:02
Ok, so we need to know how @Oeyvind has got his binaries built and if Python3 was present in the system.

**Comment by Oeyvind** [comment] 2016-12-16 16:46
I might be an issue with Rory's build then (?),
I discovered it with Cabbage,
and I also had this one
https://github.com/csound/csound/releases/download/6.08.0/Csound6.08_Win64_minimal.zip
as the active version when testing on the command line

Tested several different versions,
but switching has become a pain since windows locks any file that has been
run for several minutes, so I can't quickly rename it after running.

Now tested with
https://github.com/csound/csound/releases/download/6.08.0/Setup_Csound6_x64_6.08.0.exe
and that does not provoke the error.

I have Python 2.7 (64 bit) installed,
no Python 3 version installed.






2016-12-16 6:02 GMT-08:00 vlazzarini <notifications@github.com>:

**Comment by rorywalsh** [comment] 2016-12-16 16:49
I'll take a look. I don't use python, can't imagine how I would have
version 3 on my system.

**Comment by Oeyvind** [comment] 2016-12-16 18:19
I don't really think it relates to Python 3, since I can run pyinit, and
pycall works fine. It is just something odd with pycall opcodes that has
more than one output (pycall2 and up).

2016-12-16 8:49 GMT-08:00 Rory Walsh <notifications@github.com>:

> I'll take a look. I don't use python, can't imagine how I would have
> version 3 on my system.
>

**Comment by rorywalsh** [comment] 2016-12-16 18:44
I can confirm that I don't have Python 3 on my PC. Just 2.7.

**Comment by Oeyvind** [comment] 2016-12-16 18:47
Can you reproduce the error?

2016-12-16 10:44 GMT-08:00 Rory Walsh <notifications@github.com>:

> I can confirm that I don't have Python 3 on my PC. Just 2.7.
>
>

**Comment by rorywalsh** [comment] 2016-12-16 19:04
It's crashing Cabbage for me here, but I don't have time to look into further for now. We're travelling from tomorrow onwards. I'll hopefully get a chance to look over things in a few days or so.

**Comment by Oeyvind** [comment] 2016-12-16 19:10
all good,
happy to hear the problem shows on your system...

2016-12-16 11:04 GMT-08:00 Rory Walsh <notifications@github.com>:

**Comment by gogins** [comment] 2016-12-16 20:41
This works fine for me on Csound commit on Ubuntu 16.04 and Python 2.7.12.
I modified the test to print more information:

<CsoundSynthesizer>
<CsInstruments>
pyinit
pyruni {{

import sys
import platform
print 'sys.version:         ', sys.version
print 'platform.platform:   ', platform.platform()
print 'platform.architecure:', platform.architecture()
print

def get1(not_in_use):
    print 'get1()...'
    return float(1023)

def get2(not_in_use):
    print 'get2()...'
    # Also works:
    return (float(101),float(102))
    # return float(101),float(102)
}}

instr 1
kndx init 0
ktrig metro 1
if ktrig > 0 then
k0 pycall1 "get1", kndx
k1,k2 pycall2 "get2", kndx
endif
printk2 ktrig
printk2 k0
printk2 k1,11
printk2 k2,12
endin

</CsInstruments>
<CsScore>
i1 0 3
</CsScore>
</CsoundSynthesizer>


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment] 2016-12-16 20:41
Oops, that's commit d9798f6cff95bdb7d21eb1b940b2808cd0044a78.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2016-12-16 21:59
the problem might be elsewhere. As I said, we never touched any of the py opcode sources.

**Comment by kunstmusik** [comment] 2017-05-09 15:55
@rorywalsh @Oeyvind  is this still an issue? We're reviewing issues to see what should go into 6.09.

**Comment by Oeyvind** [comment] 2017-05-10 00:27
I will test, but all of this week is completely full.

**Comment by Oeyvind** [comment] 2017-05-10 07:28
Got a chance to test it and it looks ok here, tested CLI Csound, Cabbage, and Cabbage2

**Comment by kunstmusik** [comment] 2017-05-10 10:36
@Oeyvind  thanks for testing. I assume this was an issue with Rory's build then. Closing out the issue.

**Closed by kunstmusik** 2017-05-10 10:36 UTC
Labels: windows
