### ISSUE TITLE
csound~ for Max 64bit on Windows

### ISSUE THREAD

**Issue by alfonso73** [csound/csound#346] opened 2014-06-18 15:13 UTC
Hi guys,
for integration sake ( mostly M4Live on Ableton Live 64 bit ), a 64 bit version of the csound~ external for Windows is needed.

thanks and all the best

**Comment by gogins** [comment] 2016-03-25 11:53
See #501

**Comment by alfonso73** [comment] 2016-07-13 12:29
Hi,
seems that https://github.com/csound/csound/issues/628
has been closed.
The issues is solved but we don't know how to solve it because @unriginal has not replied recently.
Should the issue be open again until we get some info from unriginal?
best
a.

**Comment by rorywalsh** [comment] 2016-07-13 13:36
I think you're right. We can't really close it until we have clear
instructions on how to build it ourselves. Otherwise we will have to file
the same issue with every release.

**Comment by alfonso73** [comment] 2016-07-13 13:51
Who's as permissions to open the issue?
Should we open a new one and delete the old ones?

**Comment by rorywalsh** [comment] 2016-07-13 14:03
I reopened this but then reverted as the issue is technically resolved. The
issue titled "csound~ for Max 64bit on Windows" remains open.

**Comment by kunstmusik** [comment] 2023-11-04 21:35
Closing this issue as stale. Any requests for csound~ should now go to the repo that was setup for it at https://github.com/csound/csound_tilde.

**Closed by kunstmusik** 2023-11-04 21:35 UTC
Labels: enhancement, windows, csound~ (MaxMSP)
