### ISSUE TITLE
Android: Look at using Oboe for "high-performance" audio 

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#887] opened 2017-12-08 16:35 UTC
As mentioned by Jacques Leplat on the mailing list, Google is developing a "high-performance" audio library for Android that will use AAudio if available and OpenSL otherwise:

> I tried to run on an Android Pixel (64 bit). Like you the examples produce sound OK, but fail to get audio input.
> 
> The Csound Android examples manifest has the correct permission to record audio. I tried using the wavemaker sample from google, and recording works, it has the same manifest permissions as the Csound Android examples. The wavemaker sample does not use open SL. Android has launched another audio API (https://developer.android.com/ndk/guides/audio/aaudio/aaudio.html), the sample uses aaudio. It is only good for Orio or later though. 
> 
> There is a github project run by Google people, which is meant to wrap OpenSL and AAudio (OpenSL ES on API 16+ or AAudio on API 26+), but audio input is still being developed. https://github.com/google/oboe

We should track the development of Oboe and consider using it with Csound.

**Comment by gogins** [comment] 2017-12-28 02:04
I'm looking at Oboe. The readme says version 1 doesn't support input.

I've built the Csound for Android app with android studio 3.0.1 and NDK r16
and should be updating the play store with this soon.

Best,
Mike

On Dec 8, 2017 11:35, "Steven Yi" <notifications@github.com> wrote:

As mentioned by Jacques Leplat on the mailing list, Google is developing a
"high-performance" audio library for Android that will use AAudio if
available and OpenSL otherwise:

I tried to run on an Android Pixel (64 bit). Like you the examples produce
sound OK, but fail to get audio input.

The Csound Android examples manifest has the correct permission to record
audio. I tried using the wavemaker sample from google, and recording works,
it has the same manifest permissions as the Csound Android examples. The
wavemaker sample does not use open SL. Android has launched another audio
API (https://developer.android.com/ndk/guides/audio/aaudio/aaudio.html),
the sample uses aaudio. It is only good for Orio or later though.

There is a github project run by Google people, which is meant to wrap
OpenSL and AAudio (OpenSL ES on API 16+ or AAudio on API 26+), but audio
input is still being developed. https://github.com/google/oboe

We should track the development of Oboe and consider using it with Csound.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/csound/csound/issues/887>, or mute the thread

**Comment by gogins** [comment] 2018-01-04 22:09
I have implemented an Oboe-enabled version of the Csound API in the form of a CsoundOboe C++ class, which has both Java and JavaScript proxies generated by SWIG. CsoundOboe is added to the CsoundAndroid project, but does not replace or modify CsoundAndroid or CsoundObj.

The Csound for Android app does, however, now use CsoundOboe. It should be easy to retrofit CsoundObj to use CsoundOboe, but I leave this for somebody with more understanding of the design decisions behind CsoundObj. I will push these changes soon for #902.

Currently my development and test devices are a Samsung Tab 8 and Samsung Galaxy Note 8. These are not yet on Android Oreo and so do not currently provide AAudio. I think that will change at some point at least for the Note 8.

I haven't yet tested audio input or duplex audio, but my experience with Oboe so far has been very good,  seems to work fine, no surprises.

**Comment by gogins** [comment] 2018-01-05 15:54
Some more compute intensive pieces play noisily with Oboe. I am looking into this.

**Comment by gogins** [comment] 2018-01-05 16:14
There were no C++ optimizations in the Oboe library project. I added my usual `-O2 -g`.

**Comment by stekyne** [comment] 2018-01-05 17:25
Looks like from the changes that it had -O3 already?

**Comment by gogins** [comment] 2018-01-05 18:05
Not that I saw.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment] 2018-01-05 18:51
Enabled scripted build of Oboe, which is now integrated into the CsoundAndroid and CsoundApplication projects.

**Comment by kunstmusik** [comment] 2018-01-15 15:03
(Reopening this as Oboe branch is still up for review and not integrated into develop.)

The build in feature/oboe uses ANDROID_STUDIO_ROOT.  This is odd, considering there's a gradlew wrapper included in the android-audio-high-performance/oboe folder. gradlew should download gradle--and a specific version of gradle known to work with that particular projects' build--and build the project.  Beyond that, I think there's a better way. 

A few things:

1. Google's oboe project has a build_all_android.sh file but it doesn't work here for me. 
2. There is an oboe-android JNI project in our android/pluginsLibs folder that refers to the generated .a from calling gradle.  This is very circuitous and makes building harder (adds additional steps to define variables, etc.)  
3. oboe-android/jni/Android.mk can be modified to refer to oboe git repo source code files rather than a generated .a. (download-dependencies.sh would download oboe rather than android-audio-high-performance).  

Option 3 has a few benefits:

1. It integrates better with our current build
2. Requires no additional variables to be a set, nor assume Android Studio is installed. (It'd probably make it easier to setup a CI build on Travis for Android as well.)
3. Makes the dependency directly on oboe rather than circuitously through 3rd party project. 

I have commented elsewhere that using android-audio-high-performance to build oboe doesn't make sense.  I repeat that here as I still think it has no business in our codebase.

**Comment by vlazzarini** [comment] 2018-01-16 12:00
I agree with option 3 and that we should not have any extraneous code in our repo. We should attempt to use upstream sources as much as possible (as we do with other dependencies in fact).

**Comment by vlazzarini** [comment] 2018-01-16 12:04
I tried build-all.sh and got a fail here:
```
MacBook-Pro:android victor$ git checkout feature/oboe
Switched to branch 'feature/oboe'
Your branch is up-to-date with 'origin/feature/oboe'.
MacBook-Pro:android victor$ sh build-all.sh 

Beginning NDK build for Csound for Android...

ERROR: NDK is not set. Please set this variable to point to the root directory of your Android Native Development Kit installation to continue.
```
Same build command I have always used and that works at the moment on the develop branch.

**Comment by gogins** [comment] 2018-01-16 14:21
If you prefer setting ANDROID_NDK_ROOT in place of NDK, I will change the script.

You both refer to "standard variables" but do not say what they are. This puts me in a bind. What variables should be defined?

I will modify the downloadDependencies.sh to download just oboe and modify the Android.mk file as you suggest, that's fine with me. It will live in the patches directory and be copied out like the others that we have created or modified.

**Comment by vlazzarini** [comment] 2018-01-16 14:43
ANDROID_NDK_ROOT seems to me the only variable needed at the moment.

**Comment by vlazzarini** [comment] 2018-01-16 15:18
Well, I see that it is still using ANDROID_STUDIO_ROOT to find gradle, so I set it on the Mac ("/Applications/Android Studio.app/Contents/") 

```
MacBook-Pro:android victor$ echo $ANDROID_STUDIO_ROOT
/Applications/Android Studio.app/Contents/
```

But that does not help:

```
Beginning NDK build for Csound for Android...

CSOUND_ROOT:       /Users/victor/src/csound6
NDK_MODULE_PATH:   /Users/victor/src/csound6/android/pluginlibs
ANDROID_HOME:      
NDK_BUILD_COMMAND: /Users/victor/bin/android-ndk-r11c/ndk-build -j6

Building the Oboe audio driver library...
build-all.sh: line 47: cd: /Users/victor/src/csound6/android/pluginlibs/android-audio-high-performance/oboe: No such file or directory
bash: /Applications/Android: No such file or directory
FAIL
```

**Comment by vlazzarini** [comment] 2018-01-16 15:22
OK. Fixing the script to protect the variable with " " gets me further
```
Beginning NDK build for Csound for Android...

CSOUND_ROOT:       /Users/victor/src/csound6
NDK_MODULE_PATH:   /Users/victor/src/csound6/android/pluginlibs
ANDROID_HOME:      
NDK_BUILD_COMMAND: /Users/victor/bin/android-ndk-r11c/ndk-build -j6

Building the Oboe audio driver library...
build-all.sh: line 47: cd: /Users/victor/src/csound6/android/pluginlibs/android-audio-high-performance/oboe: No such file or directory
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assemble' not found in root project 'android'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
FAIL
```
Looks like there are directories/files missing from the repo.

**Comment by kunstmusik** [comment] 2018-01-16 15:59
As mentioned, just change the build so that gradle isn't necessary, and don't waste any more time on this until it is done so.  CsoundAndroid has one dependency now on libsndfile, and that does not use gradle. The same can be done, and therefore should be done, for Oboe so that we don't complicate our build any further.

**Comment by gogins** [comment] 2018-01-16 16:14
I have changed the build so that gradle is not necessary. The oboe library now uses ndk-build like everything else. I am committing this now.

**Comment by vlazzarini** [comment] 2018-01-16 18:08
Ok, thanks, I think that is a good idea. Build fails here however, looks like some files are not being found

```
MacBook-Pro:android victor$ sh build-all.sh 

Beginning NDK build for Csound for Android...

CSOUND_ROOT:       /Users/victor/src/csound6
NDK_MODULE_PATH:   /Users/victor/src/csound6/android/pluginlibs
ANDROID_HOME:      
NDK_BUILD_COMMAND: /Users/victor/bin/android-ndk-r11c/ndk-build -j6

Building Oboe audio driver library...
make: *** No rule to make target `jni/../../oboe/src/aaudio/AAudioLoader.cpp', needed by `obj/local/armeabi-v7a/objs/oboe/__/__/oboe/src/aaudio/AAudioLoader.o'.  Stop.
make: *** Waiting for unfinished jobs....
FAIL
```

**Comment by gogins** [comment] 2018-01-16 18:17
The downloadDependencies.sh script may first have to be run...

**Comment by vlazzarini** [comment] 2018-01-16 18:47
I did that, and at the end of running this script, I got
```
downloadDependencies.sh: line 102: cd: patches: No such file or directory
cp: adb: No such file or directory
cp: cannot overwrite directory ../csound with non-directory csound
```

then I tried running the build-all.sh and got the same error as above (files not found). Note that
the dependencies script said this:

```
Cloning android-audio-high-performance...
Cloning into 'oboe'...
remote: Counting objects: 577, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 577 (delta 15), reused 26 (delta 10), pack-reused 539
Receiving objects: 100% (577/577), 305.81 KiB | 767.00 KiB/s, done.
Resolving deltas: 100% (320/320), done.
```
which I thought were the missing sources.

**Comment by gogins** [comment] 2018-01-16 18:49
Ok, I'll check that.

**Comment by gogins** [comment] 2018-01-16 19:00
These are the missing sources.

The pluginlibs/patches directory and contents are in Git also, so I don't
understand that error. It works for me. You could put in a pwd and ls -ll
just before that statement, perhaps on OS X for some reason you end up in a
different place.

The downloadDependencies.sh in Git does not download android-audio-high-
performance, just oboe, but there was a misleading message which I have
fixed. Can you do a fresh pull and try again?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2018-01-16 19:18
The problem is that the script assumes that the NDK_MODULE_PATH is in the top-level android
dir. Mine is not 
```
Using NDK_MODULE_PATH: /Users/victor/bin
```
if we are using that, we need to make sure we can go back to the android dir

**Comment by gogins** [comment] 2018-01-16 19:22
I thought I had this set up the way Steven did.

**Comment by vlazzarini** [comment] 2018-01-16 19:25
Possibly , I don't know. I've pushed a fix. See if it works for you as well.

**Comment by vlazzarini** [comment] 2018-01-16 19:29
In the other script, this line is wrong
```
export NDK_MODULE_PATH=$CSOUND_ROOT/android/pluginlibs
```
it needs to be removed

**Comment by vlazzarini** [comment] 2018-01-16 19:33
However, while all the code, is there, build-all.sh does not find it. The older build-all.sh found everything.

**Comment by gogins** [comment] 2018-01-16 19:37
Do you want the user to set this explicitly or for the script to infer it?

**Comment by vlazzarini** [comment] 2018-01-16 19:39
The original build-all.sh is pretty simple and could be re-used
```
#!/bin/sh

MACHINE="$(uname -s)"
case "${MACHINE}" in 
  MINGW*) NDK_BUILD_CMD=$ANDROID_NDK_ROOT/ndk-build.cmd;;
  *) NDK_BUILD_CMD=$ANDROID_NDK_ROOT/ndk-build
esac

echo "NDK_BUILD_COMMAND = $NDK_BUILD_CMD"

if [[ $1 == "clean" ]]
then
    echo "Cleaning up shared libraries..."
    find . -name "*.so" -delete  
fi

cd pluginlibs

for plugin in *
do
    echo "Building in " ${plugin}
    cd $plugin $1
    $NDK_BUILD_CMD $1
    cd ..
done

cd ../CsoundAndroid
./build.sh $1
```

By adding the oboe build into it.

**Comment by gogins** [comment] 2018-01-16 19:50
I have explained why it should not be reused. It builds directories that
should not be built. It fails harmlessly but it is messy and misleading.

On Jan 16, 2018 14:39, "vlazzarini" <notifications@github.com> wrote:

The original build-all.sh is pretty simple and could be re-used

#!/bin/sh

MACHINE="$(uname -s)"
case "${MACHINE}" in
  MINGW*) NDK_BUILD_CMD=$ANDROID_NDK_ROOT/ndk-build.cmd;;
  *) NDK_BUILD_CMD=$ANDROID_NDK_ROOT/ndk-build
esac

echo "NDK_BUILD_COMMAND = $NDK_BUILD_CMD"

if [[ $1 == "clean" ]]
then
    echo "Cleaning up shared libraries..."
    find . -name "*.so" -delete
fi

cd pluginlibs

for plugin in *
do
    echo "Building in " ${plugin}
    cd $plugin $1
    $NDK_BUILD_CMD $1
    cd ..
done

cd ../CsoundAndroid
./build.sh $1

By adding the oboe build into it.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/csound/csound/issues/887#issuecomment-358080011>, or mute
the thread

**Comment by gogins** [comment] 2018-01-16 19:54
And it fails to build the LuaJIT dependency. However, I will fix the
directories.




-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2018-01-16 20:01
Well, the build-all.sh in the branch does not work. The one in develop does.

**Comment by vlazzarini** [comment] 2018-01-16 20:11
Another problem and the reason it does not build the oboe here is that the Android.mk for the csound-oboe lib does not take account of NDK_MODULE_PATH as the other plugin libs do (see the corresponding file for libOSC)

**Comment by gogins** [comment] 2018-01-16 20:17
So as I asked before, should the user set NDK_MODULE_PATH or is it set by
the script?




-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2018-01-16 20:21
It is a user-set path. It should be used in the Android.mk files to find the sources/libs for Android-built library (see the other plugin examples). 

There seems to be another problem with oboe build:

```
[armeabi-v7a] Compile++ thumb: oboe <= AAudioLoader.cpp
In file included from /Users/victor/bin/oboe/src/aaudio/AAudioLoader.cpp:19:
In file included from /Users/victor/bin/oboe/src/aaudio/AAudioLoader.h:21:
/Users/victor/bin/oboe/include/oboe/Definitions.h:22:10: fatal error: 'aaudio/AAudio.h' file not found
#include <aaudio/AAudio.h>
```

is `aaudio` an oboe dependency we need to  get?

**Comment by vlazzarini** [comment] 2018-01-16 20:22
this is the Android.mk I am using:

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

CSOUND_SRC_ROOT := ../../../..

LOCAL_MODULE   := liboboe

LOCAL_C_INCLUDES := $(NDK_MODULE_PATH)/oboe/include $(NDK_MODULE_PATH)/oboe/src

LOCAL_SRC_FILES := $(NDK_MODULE_PATH)/oboe/src/aaudio/AAudioLoader.cpp \
        $(NDK_MODULE_PATH)/oboe/src/aaudio/AudioStreamAAudio.cpp \
        $(NDK_MODULE_PATH)/oboe/src/common/LatencyTuner.cpp \
        $(NDK_MODULE_PATH)/oboe/src/common/AudioStream.cpp \
        $(NDK_MODULE_PATH)/oboe/src/common/AudioStreamBuilder.cpp \
        $(NDK_MODULE_PATH)/oboe/src/common/Utilities.cpp \
        $(NDK_MODULE_PATH)/oboe/src/fifo/FifoBuffer.cpp \
        $(NDK_MODULE_PATH)/oboe/src/fifo/FifoController.cpp \
        $(NDK_MODULE_PATH)/oboe/src/fifo/FifoControllerBase.cpp \
        $(NDK_MODULE_PATH)/oboe/src/fifo/FifoControllerIndirect.cpp \
        $(NDK_MODULE_PATH)/oboe/src/opensles/AudioInputStreamOpenSLES.cpp \
        $(NDK_MODULE_PATH)/oboe/src/opensles/AudioOutputStreamOpenSLES.cpp \
        $(NDK_MODULE_PATH)/oboe/src/opensles/AudioStreamBuffered.cpp \
        $(NDK_MODULE_PATH)/oboe/src/opensles/AudioStreamOpenSLES.cpp \
        $(NDK_MODULE_PATH)/oboe/src/opensles/EngineOpenSLES.cpp \
        $(NDK_MODULE_PATH)/oboe/src/opensles/OpenSLESUtilities.cpp \
        $(NDK_MODULE_PATH)/oboe/src/opensles/OutputMixerOpenSLES.cpp
        
LOCAL_LDLIBS += -llog -lOpenSLES 

include $(BUILD_SHARED_LIBRARY)
```

**Comment by vlazzarini** [comment] 2018-01-16 20:33
Ok, with the latest NDK, it builds. So see if you can incorporate the NDK_MODULE_PATH in your Android.mk, then the build-all.sh should not overwrite it as it is doing at the moment.

**Comment by gogins** [comment] 2018-01-16 20:38
AAudio is part of NDK r16b. This is a dependency. I did mention this.

I have changed the script to assume that NDK_MODULE_PATH exists in the
environment and to complain if not.




-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2018-01-16 21:05
the Oboe lib is building here but I had to fix the Android.mk (see above). You need to check if this is correct and see if all the other Android.mk files you added do a similar thing.

**Comment by gogins** [comment] 2018-01-16 21:20
NDK_MODULE_PATH is set globally in the user's environment, then overriden
by the some of .mk files, sometimes to a different value. Is this correct?


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment] 2018-01-16 21:26
Anyway, without further monkeying with NDK_MODULE_PATH, I can wipe out the
external repos, run ./downloadDependencies.sh, do ./build-all.sh clean, and
./build-all.sh and everything builds.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2018-01-16 21:40
No, there's more trouble. 

1) The current dependencies (libsndfile, liblo, fluidsynth) are built in the NDK_MODULE_PATH. The 2) Android.mk in the plugins that use these, refers to NDK_MODULE_PATH and builds these correctly.
3) More importantly, the CsoundAndroid Android.mk refers to NDK_MODULE_PATH to find the libsndfile (static) library.
4) -loboe is not found because it is not being built in the NDK_MODULE_PATH, unless we hardwire the NDK_MODULE_PATH to ./android/pluginlibs

This is not right. It is not guaranteed to work more generally. The correct way to do this is to 
either 1) patch up the original oboe sources to add the /jni/*.mk and then build it there;
2) copy the built oboe-csound to the NDK_MODULE_PATH

**Comment by vlazzarini** [comment] 2018-01-16 21:49
I have fixed the build for MacOS, but it still needs the changes in Android.mk for oboe-android, which I am not committing because I don't know if they break your build. Can you check them?

**Comment by vlazzarini** [comment] 2018-01-16 22:00
Besides the problem of NDK_MODULE_PATH there are two other problems with build-all.sh:

1) it forces everyone to build the LuaJNI-based code. This requires a cross-compilation toolchain that is different to the NDK. It is unfair to make it a dependency for everyone working on Android.
I had to disable that on MacOS, otherwise I could not build the other components.

2) it builds the Csound Android App, which is not what everyone might want to do. 

This is not likely to work well for everyone. The advantage of the previous script is that even if the one or more plugins failed to build, we would have the CsoundAndroid library built. Now if one of them fails, nothing else builds. I don't think that is right.

**Comment by gogins** [comment] 2018-01-16 22:38
I wrote the .mk for Oboe. It works for me. Should this be changed, or does
CsoundAndroid need an import module statement? Or a different one?

**Comment by vlazzarini** [comment] 2018-01-16 22:39
yes it should be changed as outline above.

**Comment by vlazzarini** [comment] 2018-01-16 22:39
I'll commit it and you can check it.

**Comment by kunstmusik** [comment] 2018-01-16 23:55
I would point out that most of the comments on this issue have to do with just fixing/building things that used to work, rather than testing new Oboe-related code. (We should evaluate removing plugins libs from core build since they are wasting time and resources.)

CsoundAndroid/build.sh is working here.  ableton link and lua opcodes do not compile.  (I've previously reported the former in #886, so this is not new). CsoundApp can not compile for anyone else but Michael due to signing key stuff in gradle config (something I fixed and was rebroken, and something I have pointed out a few times now) and I see no test code in CsoundAndroidExamples. I do see a CsoundOboe class generated; how is one expected to test this? 

Oboe-related code wasn't integrated into AndroidCsound.cpp like rtopensl.c was done.  This means anyone using Csound for Android SDK who wants to use Oboe backend has to rewrite their code to use a whole separate object.  That would affect users using AndroidCsound.cpp directly--as some do via native applications via QT--and it also does not integrate with CsoundObj's design or implementation in any way. I'm assuming that lack of integration is why it was reported that Oboe didn't work on the Csound user's list. (Also, seems like csound_oboe.hpp repeats a lot of what is in Csound class; why would it not subclass Csound as AndroidCsound does?)

**Comment by gogins** [comment] 2018-01-17 02:05
Just now commit 52329ce489712a99c3b19b9f3f34b583355942c7 built from scratch
for me.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2018-01-17 09:37
@kunstmusik yes I agree, we're trying to ascertain first that it can be built on all platforms and for all users. We're possibly close to fixing this at least for CsoundAndroid. If we can achieve that, it is one step towards getting this issue resolved.
The other, as you pointed out, is to add documentation and tests.

**Comment by gogins** [comment] 2018-01-25 18:11
Might want to use this for duplex audio: https://github.com/cameron314/readerwriterqueue

**Comment by vlazzarini** [comment] 2018-01-25 18:31
Csound has a circular buffer that you could use instead. It is used in rtopensl.c

**Comment by gogins** [comment] 2018-01-25 18:39
I will look at that, thanks. Is this a lock-free buffer?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2018-01-25 18:45
yep, lock-free and used elsewhere in Csound. It’s there for that purpose.

**Comment by vlazzarini** [comment] 2018-01-25 18:46
It’s part of the API.

**Comment by gogins** [comment] 2018-03-26 14:19
I am unassigning myself from this issue as I have implemented an Oboe driver for the Csound for Android app, which is now maintained in the cound-extended repository.

**Comment by kunstmusik** [comment] 2023-11-06 01:17
@vlazzarini @gogins What is the status of this issue? Is there anything that needs to be brought into develop repo for CS7?

**Comment by vlazzarini** [comment] 2023-11-06 06:37
as far as I can see we did not incorporate oboe in Csound because it looked like a better fit for frontends. I have not touched Android for maybe eight years so I am not the best person to have an opinion in this.

**Comment by gogins** [comment] 2023-11-06 12:35
The Csound for Android app that I maintain uses Oboe, which switches
automatically or manually between audio drivers and does seem good.

Best,
Mike

**Comment by vlazzarini** [comment] 2023-11-06 12:47
Ok, that sounds ideal thanks for that.

**Comment by kunstmusik** [comment] 2023-11-06 14:51
The problem is that Oboe is the recommended library for audio now and Csound for Android SDK users should be able to get that out of the box. Great that it's in @gogins app but that doesn't do much for people using CsoundUnity on Android for example. 

I'm going to add this to 7.0.0. Whomever takes up Android maintenance should look at Michael's code and look to port that over to the Csound for Android core.

**Comment by rorywalsh** [comment] 2024-06-11 18:07
While I agree this would be nice to have out of the box, I also think it's something that can be handled on the host side.

**Comment by vlazzarini** [comment] 2024-06-11 18:44
I agree, let's close this issue. I don't think we can give attention to this.

**Closed by vlazzarini** 2024-06-11 18:44 UTC
Labels: android
