### ISSUE TITLE
UDP not working on Csound for Android app 6.11.0

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#927] opened 2018-02-09 05:45 UTC
The Csound for Android 6.11.0 app (currently in the Play Store) doesn't respond to UDP messages. No error message: It just doesn't listen. 
This following test works in the previous app: Csound for Android 6.09.0beta2
To test: Run UDPlisten.csd in the app.
```
<CsoundSynthesizer>
<CsOptions>
-odac --port=8099 --nchnls=2 --0dbfs=1 --sample-rate=48000 --ksmps=64 --messagelevel=128
</CsOptions>
<CsInstruments>
prints "started UDP csd\n"
</CsInstruments>
<CsScore>
f0 300
</CsScore>
</CsoundSynthesizer>
```

Save a a bit of orc code in a file called udptest.txt
[udptest.txt](https://github.com/csound/csound/files/1709875/udptest.txt)

Then in a terminal enter
nc -u 127.0.0.1 8099 < udptest.txt

**Comment by vlazzarini** [comment] 2018-02-09 07:57
I think this has been fixed in git. I noticed that pthreads had not bern switched on for android, which would have caused
that. I’ve put them back on.

**Comment by vlazzarini** [comment] 2018-04-08 13:57
These releases are not coming from the Csound project, so I cannot say anything about them. All I can say is that threads were enabled back again in the build scripts. Perhaps @kunstmusik can check it ?

**Comment by kunstmusik** [comment] 2018-04-10 20:10
I spent a while trying to get UDP to work without much luck.

I built a test application that just starts a CSD and attempts to use --port=10000.  I was not able to hit it from my desktop computer using "nc -u 192.168.0.101 10000 < test.orc" (which does work hitting a Csound UDP test process on the same localhost).  I tried adding:
`
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"></uses-permission>
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"></uses-permission>
    <uses-permission android:name="android.permission.INTERNET"></uses-permission>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"></uses-permission>
`

To the manifest too. I did add a test note to the CSD so it does play a sound when the program starts.  

I also tried acquiring a MultiCastLock using the WifiManager to see if that would open it up but no change. 

Not really sure what next to try.  I did try out a UDP testing application:

https://play.google.com/store/apps/details?id=jp.gr.java_conf.tcp_udp_testtool

and did receive UDP messages on my Android device from my desktop with the nc tool and a separate python script, so I know at least that works.

**Comment by vlazzarini** [comment] 2018-04-10 20:13
Can you check in the consoler messages if the server is actually running?

**Comment by kunstmusik** [comment] 2018-04-10 20:15
I had checked and I don't get early messages from Csound in general. Not sure what message callback situation is that causes that.

**Comment by vlazzarini** [comment] 2018-04-10 20:18
So we're not certain that the server thread is actually running. I think that is the first thing we need to check, if there is a way to do it.

**Comment by vlazzarini** [comment] 2018-04-10 20:24
I guess the callback to logcat is not installed until later. I really can't remember what the situation was when I used to work here with android.

**Comment by vlazzarini** [comment] 2018-04-10 20:25
Maybe you need to stick in an csoundMessage call inside the server thread loop to check.

**Comment by kunstmusik** [comment] 2018-04-10 21:40
I put in a test message call and did not receive any messages. After
looking a bit, I think the problem is that the build was not updated
correctly for pthreads and need to have -DHAVE_PTHREAD defined.  I am doing
another build and will retest when that's complete.

**Comment by vlazzarini** [comment] 2018-04-10 21:50
That makes sense, since that was the original problem. I thought I had added -DHAVE_PTHREAD to the build scripts, as I said in my first comment. But maybe with all the confusion earlier when we re-organised the repo it disappeared again.

**Comment by kunstmusik** [comment] 2018-04-10 22:00
With -DHAVE_PTHREAD I saw my message printed in the udp_recv loop, but I did not get any UDP packets. I took the message back out in case that was flooding the system or something like that but no change.  (Pushed the change for HAVE_PTHREAD to git at least.)  Will take another look tomorrow.

**Comment by vlazzarini** [comment] 2018-04-10 22:10
another thing is to try and see if the UDP opcodes (sockrecv) work. But having the server running is a good start. 
Also if the OSC opcodes are present, that is another thing to try.

**Comment by ErrorThink** [comment] 2018-04-14 13:30
I couldn't get socksend/recv to work. It runs, but there's a message that the bind failed, which is something at least.
I could get the OSC opcodes to work, but only on the first run. Re-running the same CSD causes the app to crash.
I also discovered a strange oddity with outputting audio files, but this might be unrelated. Will file a separate issue.

**Comment by gogins** [comment] 2018-04-14 13:33
There was an issue in the Csound for Android app 6.11 where file output was
not working all. I believe I have fixed this in the current release in the
Play Store.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment] 2018-04-14 13:34
@ErrorThink I've been looking at this issue and isolated the problem yesterday. UDP is working at the moment but the issue has to do with code for async and spinlocks, which look to not be natively present in Android < ANDROID_N.   I am only looking at UDP server in this issue; a separate task for OSC should be filed as it is in a plugin library.

**Comment by kunstmusik** [comment] 2018-04-14 18:48
I found that we needed to add HAVE_PTHREAD, HAVE_BUILTIN_ATOMIC, and HAVE_ATOMIC_BUILTIN to get all of the necessary parts working.  Tested using @ErrorThink 's UPDListen.csd in a test Android application as well as using udptest.txt with nc from desktop sending over UDP port 8099.  

This will be in the 6.11.0 Csound for Android SDK release.  (Contact @gogins for Csound Android Playstore App release schedule of this fix.)

**Closed by kunstmusik** 2018-04-14 18:48 UTC

**Comment by gogins** [comment] 2018-04-14 19:13
Thanks, I will add these definitions to my build. What can I use to test
this?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment] 2018-04-14 19:47
You can use the test CSD and .txt file that was submitted at the beginning of this issue.

**Comment by gogins** [comment] 2018-04-16 01:00
I fixed the Csound for Android build files as advised, and tested with the
example files. It did not work for me in the Csound for Android app. It
worked fine for my desktop Linux build. Is there some additional manifest
permission or other code change that I missed?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment] 2018-04-16 02:26
I replied in the other issue that you had a typo in your changes and also to double check UDP is working in general by using a UDP testing application first.  If UDP is confirmed to work, it might be a permissions issue but I'd note that the app worked previously with the same permissions and older UDP server implementation.

**Comment by gogins** [comment] 2018-04-16 02:55
I will remove the typo.

**Comment by gogins** [comment] 2018-04-16 15:19
New release of Csound for Android app in the Google Play Store, fixes
soundfile output and UDP server bugs. May support fewer devices.

Thanks to ErrorThink and @kunstmusik for helpful information.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
