### ISSUE TITLE
ctcsound issue on Mac OS 11.4 w/6.16.2

### ISSUE THREAD

**Issue by benmca** [csound/csound#1506] opened 2021-07-22 23:14 UTC
Traceback (most recent call last):
  File "/Users/ben/src/csound-pieces/thuja-ep/books-style/1.py", line 8, in <module>
    import thuja.csound_utils as cs_utils
  File "/Users/ben/src/thuja/thuja/csound_utils.py", line 1, in <module>
    import ctcsound
  File "/Users/ben/.virtualenvs/thuja/lib/python3.9/site-packages/ctcsound.py", line 2705, in <module>
    libcspt.NewCsoundPT.restype = ct.c_void_p
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, NewCsoundPT): symbol not found

I've validated that /Users/ben/.virtualenvs/thuja/lib/python3.9/site-packages/ctcsound.py is the version that shipped w/6.16.2 i.e. the same as /Library/Frameworks/CsoundLib64.framework/Resources/Python/Current/ctcsound.py

**Comment by vlazzarini** [comment] 2021-07-23 07:26
Are you running on some sort of virtual environment? That could be the problem.
It runs OK on the normal Python3.9 (from python.org)

```
victor@MacBook-Pro ~ % ls -l /Library/Python/3.9/site-packages/ctcsound.py   
lrwxr-xr-x  1 root  wheel  78 23 Jul 08:23 /Library/Python/3.9/site-packages/ctcsound.py -> /Library/Frameworks/CsoundLib64.framework/Resources/Python/Current/ctcsound.py
victor@MacBook-Pro ~ % python3.9
Python 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctcsound
>>> 
victor@MacBook-Pro ~ % ls -l /Library/Python/3.9/site-packages/ctcsound.py   
lrwxr-xr-x  1 root  wheel  78 23 Jul 08:23 /Library/Python/3.9/site-packages/ctcsound.py -> /Library/Frameworks/CsoundLib64.framework/Resources/Python/Current/ctcsound.py
victor@MacBook-Pro ~ % python3.9
Python 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctcsound
```

**Comment by vlazzarini** [comment] 2021-07-23 07:57
I also tested with 3.9.6 to be sure, and run it on a virtual env created with `venv`

```
victor@MacBook-Pro ~ % source venv/bin/activate
(venv) victor@MacBook-Pro ~ % python3.9                    
Python 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctcsound
>>> 
```

so I am not sure what the issue is. I would have thought the error messages indicate that the Csound library wasn't loaded properly because the lib symbol was not found by ctypes. @fggp do you have a suggestion?

**Comment by vlazzarini** [comment] 2021-07-23 08:10
I found the issue. You can fix it by changing line 2705 to

```
    libcspt = ct.CDLL(ctypes.util.find_library('csnd6.6.0'))
```

**Comment by fggp** [comment] 2021-07-23 12:23
Thank you Victor. Seems the problem came from my last commit. Unfortunately
I don't have MacOs for testing...

François

Le ven. 23 juil. 2021 à 10:10, vlazzarini ***@***.***> a
écrit :

**Comment by vlazzarini** [comment] 2021-07-23 12:43
Not a problem, I overlooked it because I had an old symlink in my system called libcsnd6.dylib and that was a match. The problem was that the installer did not make that, so in other people's computers that would fail, but it never did on mine. I got rid of the symlink so that in the future I can catch these things.

**Comment by benmca** [comment] 2021-07-23 16:30
thx!

**Comment by benmca** [comment] 2021-07-23 16:31
I'll close after I test the next the 6.16.3 installer...

**Comment by vlazzarini** [comment] 2021-07-23 16:37
There is no 6.16.3 installer. I replaced 6.12.2 since this was a minor link fix in the script.

**Comment by vlazzarini** [comment] 2021-08-14 20:06
I'm closing this now as it has been confirmed fixed on the Csound list.

**Closed by vlazzarini** 2021-08-14 20:06 UTC

**Comment by Leofltt** [comment] 2021-09-02 18:31
Hi everyone, I am still seeing this error with python 3.8.12 and ctcsound-6.17. For python 3.8.12 only up to ctcsound-6.14 works correctly

**Comment by vlazzarini** [comment] 2021-09-02 18:44
Make sure you don't have more than one ctcsound.py lying around in your python path.

**Comment by vlazzarini** [comment] 2021-09-02 19:35
Tested here just now with latest 6.17

```
victor@MacBook-Pro interfaces % DYLD_LIBRARY_PATH=/usr/local/lib python3.8
Python 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctcsound
>>> 
``` 

Because the CsoundLib64 built from sources has a link to libsndfile.1.dylib you may need to supply the path to it, which is what I was doing. That is not necessary in the binary releases because all the links are edited to be correct.

**Comment by Leofltt** [comment] 2021-09-02 21:11
I'm still confused. I unlinked and uninstalled the homebrew version of csound and installed csound from the release pkg version, and then copied that ctcsound.py file to my site-packages, but I'm still getting the same error with ctcsound-6.17 . 
ctcsound-6.16.2 works for me though. There is only one ctcsound.py in my python path.
I still don't understand what I'm doing wrong

**Comment by vlazzarini** [comment] 2021-09-02 21:40
don't mix up versions. Copy here the error messages, probably dylibs that are not found

**Comment by Leofltt** [comment] 2021-09-02 22:03
This is the error I get when importing ctcsound-6.17

`Python 3.8.12 (default, Aug 31 2021, 04:08:54) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctcsound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/ctcsound.py", line 423, in <module>
    libcsound.csoundCreateThread2.restype = ct.c_void_p
  File "/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fee93c47bc0, csoundCreateThread2): symbol not found
>>> `

**Comment by vlazzarini** [comment] 2021-09-02 22:39
That's a different error. I introduced a new function to the API called csoundCreateThread2(), and François added it to ctcsound. It looks line there is a version mismatch. You need to build the library with this new function to use this version of ctcsound

**Comment by Leofltt** [comment] 2021-09-02 22:57
Oh well, that makes sense! Yeah that solved it, thanks Victor
