### ISSUE TITLE
Turnoff clicks in trigger instruments

### ISSUE THREAD

**Issue by docb** [csound/csound#1490] opened 2021-06-18 12:06 UTC
--Csound version 6.17 (double samples) Jun 17 2021
[commit: f1f1aaeee3b9afef95ff2711a366580baaaf00bf]
linux ubuntu

here is a csd which demonstrates that probably turnoff causes clicks in trigger instruments.
for demonstration there is a midi trigger instrument "miditrig" which is connected via massign.
this instrument schedules the trig instrument for noteon and noteoff events -

if 3 parallel notes a played on the midi keybord it starts clicking on every subsequent noteoff.

in my real case these triggers come from the browser in csoundweb via csoundObj.readScore (where the problem
was not there with CsoundObj.js 6.15)

the trig instrument is ended by turnoff. if i comment out the turnoff and use 2/kr time for schedulek in the miditrig instrument
the problem dissappers. 

```
<CsoundSynthesizer>
<CsOptions>
-odac -Ma
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

massign 0,2

opcode freqtrigger,0,iiii
  insno,ion,ifreq,ivel xin
  print insno,ion,ifreq,ivel
  if ion == 1 then
    event "i",insno+(ifreq*0.00001),0,-1,ifreq,ivel
  else
    turnoff2 insno+(ifreq*0.00001),4,1
  endif
endop

opcode notetrigger,0,iiii
  insno,ion,ikey,ivel xin
  ifreq = cpsmidinn(ikey)
  freqtrigger insno,ion,ifreq,ivel
endop

instr trig
  insno = nstrnum("trigtest")
  notetrigger insno,p4,p5,p6
  turnoff
endin

instr miditrig
  midinoteonkey p4,p5
  itime = 0.1
  //itime = 2/kr
  xtratim 1/kr
  schedule "trig",0,itime,1,p4,p5
  if lastcycle() == 1 then
    schedulek "trig",0,itime,0,p4,p5
  endif
endin

instr trigtest
  ifreq = p4
  ivel = p5/127
  print ifreq,ivel
  aout vco2 ivel,ifreq
  aout moogladder aout,6000,0.1
  aenv madsr 0.01,0.01,1,0.1
  aout *= (aenv*.3)
  outs aout,aout
endin

</CsInstruments>
<CsScore>
</CsScore>
<CsoundSynthesizer>
```

**Comment by vlazzarini** [comment] 2021-06-18 12:25
Ok, I can confirm it is related to the changes we made to fix a similar click issue. It will take time to debug this, but in the meanwhile, changing the order of the instruments will fix it for you

```
<CsoundSynthesizer>
<CsOptions>
-odac -Ma
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

massign 0,1

opcode freqtrigger,0,iiii
  insno,ion,ifreq,ivel xin
  print insno,ion,ifreq,ivel
  if ion == 1 then
    event "i",insno+(ifreq*0.00001),0,-1,ifreq,ivel
  else
    turnoff2 insno+(ifreq*0.00001),4,1
  endif
endop

opcode notetrigger,0,iiii
  insno,ion,ikey,ivel xin
  ifreq = cpsmidinn(ikey)
  freqtrigger insno,ion,ifreq,ivel
endop




instr miditrig
  midinoteonkey p4,p5
  itime = 0.1
  //itime = 2/kr
  xtratim 1/kr
  schedule "trig",0,itime,1,p4,p5
  if lastcycle() == 1 then
    schedulek "trig",0,itime,0,p4,p5
  endif
endin

instr trigtest
  ifreq = p4
  ivel = p5/127
  print ifreq,ivel
  aout vco2 ivel,ifreq
  aout moogladder aout,6000,0.1
  aenv madsr 0.01,0.01,1,0.1
  aout *= (aenv*.3)
  outs aout,aout
endin

instr trig
  insno = nstrnum("trigtest")
  notetrigger insno,p4,p5,p6
  turnoff
endin





</CsInstruments>
<CsScore>
</CsScore>
<CsoundSynthesizer>
```

**Comment by docb** [comment] 2021-06-18 12:35
ok this solves the problem in my web csound instrument, thanks!

**Comment by vlazzarini** [comment] 2021-06-18 12:38
another thing: if you comment out "turnoff" in your original code, instr trig, it seems that you have the same functionality, and it looks like the clicks are gone too.

**Comment by docb** [comment] 2021-06-18 12:42
yes as i mentioned, but then i have to set the time in schedulek to a minimum - i figured out that 2/kr seems to work (while 1/kr does not) to prevent the trig instrument for triggering more than once.

**Comment by vlazzarini** [comment] 2021-06-18 12:53
I didn't notice the instrument triggering more than once with itime = 0.1. Anyway, another interesting thing, if I don't use MIDI, there are no clicks

```
<CsoundSynthesizer>
<CsOptions>
-odac -Ma
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

massign 0,2

opcode freqtrigger,0,iiii
  insno,ion,ifreq,ivel xin
  print insno,ion,ifreq,ivel
  if ion == 1 then
    event "i",insno+(ifreq*0.00001),0,-1,ifreq,ivel
  else
    turnoff2 insno+(ifreq*0.00001),4,1
  endif
endop

opcode notetrigger,0,iiii
  insno,ion,ikey,ivel xin
  ifreq = cpsmidinn(ikey)
  freqtrigger insno,ion,ifreq,ivel
endop

instr trig
  insno = nstrnum("trigtest")
  notetrigger insno,p4,p5,p6
  turnoff
endin


instr miditrig
  midinoteonkey p4,p5
  itime = 0.1
  //itime = 2/kr
  xtratim 1/kr
  schedule "trig",0,itime,1,p4,p5
  if lastcycle() == 1 then
    schedulek "trig",0,itime,0,p4,p5
  endif
endin

instr trigtest
  ifreq = p4
  ivel = p5/127
  print ifreq,ivel
  aout vco2 ivel,ifreq
  aout moogladder aout,6000,0.1
  aenv madsr 0.01,0.01,1,0.1
  aout *= (aenv*.3)
  outs aout,aout
endin

</CsInstruments>
<CsScore>
f 0 10
i3 0 1 440 64
i3 0 1 550 64
i3 0 1 660 64
i3 2 1 480 64
</CsScore>
<CsoundSynthesizer>
```
which makes it hard to debug, but there you go.

**Comment by docb** [comment] 2021-06-18 14:07
without midi you can get this with
```
i1 0 0.1 1 60 64
i1 0 0.1 1 63 64
i1 0 0.1 1 67 64
i1 1 0.1 0 60 64
i1 1 0.1 0 63 64
i1 1 0.1 0 67 64

i1 1 0.1 1 60 64
i1 1 0.1 1 63 64
i1 2 0.1 0 60 64
i1 2 0.1 0 63 64

i1 2 0.1 1 60 64
i1 3 0.1 0 60 64

```
and more clear with setting the release of the masdr to 0.5
in the last note it is good to hear, as the click occurs before the release phase starts

**Comment by vlazzarini** [comment] 2021-06-18 14:38
yes, I figure that out. What is happening is that turnoff is causing the next instruments on the list to skip a processing cycle.

**Comment by vlazzarini** [comment] 2021-06-18 16:47
This is now fixed in git develop branch

**Closed by vlazzarini** 2021-06-18 16:47 UTC

**Comment by johannphilippe** [comment] 2022-05-14 14:54
I could reproduce the same issue with turnoff2 with a homemade build : 
--Csound version 6.18 (double samples) Feb 19 2022
On Linux Mint 20. 
Moving the turnoff2 to instr 999 solved it, and the click didn't happen anymore. 

The instrument I turnoff is a scheduler instrument (so, no audio coming out of it, only control signals and schedulek).
