### ISSUE TITLE
csound~ 1.1.3 error (Error 193 loading external csound~) in Max 7.0.4 32bit  on Win 7 64bit

### ISSUE THREAD

**Issue by alfonso73** [csound/csound#500] opened 2015-07-03 13:05 UTC
Hi,
when instantiating a csound~ instance in Max 7.0.4 32bit on Win7 64 bit the Max window reports

Error 193 loading external csound~

I've run dependency walker and the error report is too long to be pasted here and unfortunately isn't possible to attach txt files here.
But basically what you see in the image are the errors

![csound _dependencies](https://cloud.githubusercontent.com/assets/3230434/8499610/f16cbc66-2194-11e5-8679-2a32de993476.jpg)

**Comment by gogins** [comment] 2015-07-03 14:47
It looks like this program is trying to run code that is built for 32 bit
CPU architecture with code that is built for 64 bit CPU architecture. That
will never work without some sort of thunking adapter, does Max have such
an adapter?

Regards,
Mike

**Comment by kunstmusik** [comment] 2015-07-03 16:00
It looks like the problem is that something is pulling in a 64-bit version of pthreadGC2.dll.  Need to check what are the dependencies of the csound~.mxe.

**Comment by alfonso73** [comment] 2015-07-03 16:39
well i'm on Win7 64bit so prpbably other installations installed 64 bit
versions of .dlls

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by kunstmusik** [comment] 2015-07-03 16:53
Sure, I think there can be an expectation of that.  The issue is what is
pulling in that version of pthreadGC2.dll.  If it's csound~, then the code
could be changed to use Csound's thread functions.  Another option is to
copy in a 32-bit version of pthreadGC2.dll into the folder where the
csound~.mxe is and see if that affects things.

On Fri, Jul 3, 2015 at 12:39 PM, Alfonso Santimone <notifications@github.com

**Comment by gogins** [comment] 2015-07-03 20:14
Windows knows how to sort out DLL versions, usually. If this is indeed a
problem it is likely due to:

(1) A DLL in the application's own directory that is the wrong CPU
architecure.

(2) The application or something in the application is trying to
DYNAMICALLY (given a filename, config file, directory name, environment
variable, etc) load a DLL that is the wrong CPU architecture.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

On Fri, Jul 3, 2015 at 12:39 PM, Alfonso Santimone <notifications@github.com

**Comment by alfonso73** [comment] 2015-07-03 23:13
i have to check if my PthreadGC2.dll is 64 or 32 bit arch.
i'll let ya know tomorrow.

bests
Il 03/lug/2015 22:14, "gogins" <notifications@github.com> ha scritto:

**Comment by alfonso73** [comment] 2015-07-04 09:07
hi all,
copying a pthreadGC2.dll 32 bit version in the csound~.mxe folder does not
solve the problem.
i still have

Error 193 loading external csound~

in the Max window

a.


www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by kunstmusik** [comment] 2015-07-14 02:31
@alfonso73 Could you try this build:

http://kunstmusik.com/csound~_1.1.3.exe

I've modified the build to no longer link to pthreads and use Csound's threading routines instead.

**Comment by alfonso73** [comment] 2015-07-14 11:45
Hi Steven!
Thanks it works!

But still the installer put the files in the wrong paths.
Paths for the csound~ folder should be
C:\Users\$USER NAME$\Documents\Max 7\Packages

and path for csound~.mxe should be

C:\Users\$USER NAME$\Documents\Max 7\Packages\

C:\Users\$USER NAME$\Documents\Max 7\Packages\csound~_v1.1.3\externals


Hope for a 64bit architecture version very soon!!

bests

a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by kunstmusik** [comment] 2015-07-14 16:47
Yes, the install location will be addressed by #491 and having zips.  64-bit is tracked in #501. 

Thanks for confirming this worked. I will close this issue now.

**Closed by kunstmusik** 2015-07-14 16:47 UTC
Labels: bug, windows
