### ISSUE TITLE
#ifndef fails if no newline after #endif at EOF

### ISSUE THREAD

**Issue by tgrey1** [csound/csound#1337] opened 2020-06-14 03:15 UTC
I made this example that has a MainTest.csd and 3 include files, each include exhibits a different behavior and is commented to how it behaves (two are commented out... switch which is active to test).

[include_ifndef_debug.zip](https://github.com/csound/csound/files/4775808/include_ifndef_debug.zip)

One fails with the message "Unmatched #ifdef" due to a missing newline, one passes by just adding a newline to the first file, and the last shows that missing newline is ok after define, but not endif.

This definitely seems like a bug to me!  First, it's an unmatched ifndef, not ifdef.  Second, the missing newline shouldn't break parsing, should it?

Let me know if there are any questions about the test.

**Comment by jpffitch** [comment] 2020-06-14 19:39
Three comments:

1: I changed the error message to e more accurate but not very good

2: I think without the newline it is indeed an error, but I am usually out of step with the world

3: I committed a change that works for your example but i worry about what it breaks elsewhere.  Proceed with caution.

**Comment by tgrey1** [comment] 2020-06-14 22:03
I can't compile and test yet, but I'll see if I can get a build from Rory's setup asap.  Will report how it works in a more complex example once I can.

**Comment by tgrey1** [comment] 2020-06-15 21:42
Big thanks to Rory and his OSX dev pipeline... I got a new build and tested this in a **overly** complex example.  Everything appears to be working well and as expected, at least when used properly  Thanks John!

However now an unterminated #ifndef appears to be causing a segfault.  To test this, I commented out the last line of ifndef_nobr.csd and ran the test again.

**Comment by jpffitch** [comment] 2020-06-16 15:47
I cannot reproduce this latest error.  Please supply your example (as I may have not done the edit correctly).

**Comment by tgrey1** [comment] 2020-06-16 20:35
Sorry, here are complete changes:

ifndef_nobr.csd should now read:

``` csd
#ifndef ALREADY_INCLUDED
	#define ALREADY_INCLUDED ##
; #endif
```

And MainTest.csd should be including that file (the first of the three include statements), so the entire file is:
``` csd
<CsoundSynthesizer>
<CsOptions>
-n -d
</CsOptions>
<CsInstruments>
ksmps = 32
nchnls = 2
0dbfs = 1

; this include will fail due to lack of blank new line after #endif
#include "ifndef_nobr.csd"

; this include will pass because it has a new line after #endif
; #include "ifndef_br.csd"

; this include shows that lack of newline works ok after define
 ; #include "define_nobr.csd"

instr 1
	aSig vco2 .5, 440
	outs aSig, aSig
endin

</CsInstruments>
<CsScore>
i1 0 1
</CsScore>
</CsoundSynthesizer>
```

My output is:
```
$ csound -Wdo dac MainTest.csd
0dBFS level = 32768.0
--Csound version 6.14 (double samples) Jun 15 2020
[commit: 7eebbc5982a303713a3bba9cb03ed14d4cafe2af]
libsndfile-1.0.28
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libfluidOpcodes.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libwidgets.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libvirtual.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtpa.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libosc.dylib' (-1)
UnifiedCSD:  MainTest.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtmidi: PortMIDI module enabled
using path .

csound command: Segmentation fault
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.261s, CPU: 0.002s
```

**Comment by jpffitch** [comment] 2020-06-17 15:48
That agrees with my code which runs

--Csound version 6.14 beta (double samples) Jun  1 2020
[commit: 95ad9f3bd87d0a356a8cb3e09433afec4758e565]
libsndfile-1.0.29pre1
Reading options from $HOME/.csound6rc
UnifiedCSD:  MainTest.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
using path .
Unmatched #ifdef or #ifndef
cannot compile orchestra
end of score.              overall amps:      0.0
            overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
no sound written to disk


S # repeat, cannot reproduce (on GNU/Linux)

==John ff

**Comment by jpffitch** [comment] 2020-06-17 15:54
OK; My editor adds the final newline autoatically and your revised code 
did not make it clear tat a newline was missing

I can now gie the crash
(gdb) where
#0  0x00007ffff6fd6ffa in fread () from /lib64/libc.so.6
#1  0x00007ffff7affa8b in yy_get_next_buffer (yyscanner=0x7e5fd0)
     at Engine/csound_prelex.c:2506
#2  input (yyscanner=0x7e5fd0) at Engine/csound_prelex.c:2681
#3  comment (yyscanner=yyscanner@entry=0x7e5fd0)
     at /home/jpff/csound6/Engine/csound_pre.lex:682
#4  0x00007ffff7b01e3d in csound_prelex (csound=csound@entry=0x626040,
     yyscanner=0x7e5fd0) at /home/jpff/csound6/Engine/csound_pre.lex:191
#5  0x00007ffff7b1b852 in csoundParseOrc (csound=csound@entry=0x626040,
     str=str@entry=0x0) at /home/jpff/csound6/Engine/new_orc_parser.c:197
#6  0x00007ffff7b1b344 in csoundCompileOrcInternal (
     csound=csound@entry=0x626040, str=str@entry=0x0, async=async@entry=0)
     at /home/jpff/csound6/Engine/csound_orc_compile.c:1932
#7  0x00007ffff7a3f4d8 in csoundCompileArgs (csound=csound@entry=0x626040,
     argc=<optimized out>, argc@entry=2, argv=argv@entry=0x7fffffffde98)
     at /home/jpff/csound6/Top/main.c:313
#8  0x00007ffff7a40699 in csoundCompile (csound=csound@entry=0x626040,
     argc=argc@entry=2, argv=argv@entry=0x7fffffffde98)
     at /home/jpff/csound6/Top/main.c:562
#9  0x0000000000401435 in main (argc=2, argv=0x7fffffffde98)
     at /home/jpff/csound6/Frontends/csound/csound_main.c:326
(gdb)

**Comment by jpffitch** [comment] 2020-07-01 15:51
Three comments:

1: I changed the error message to e more accurate but not very good

2: I think without the newline it is indeed an error, but I am usually out of step with the world

3: I committed a change that works for your example but i worry about what it breaks elsewhere.  Proceed with caution.

**Closed by jpffitch** 2020-07-01 15:51 UTC
