### ISSUE TITLE
The alwayson opcode does not work in CsoundVST [sf cs6other #2]

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#175] opened 2014-03-24 01:27 UTC
**Originally reported by Sourceforge User: gogins**

The examples/CsoundVST.csd orchestra, which uses alwayson for effects and audio routing, will run in VSTHost, but will not produce audio. This seems to be because the alwayson instruments go right off in VST performance. If an instrument is changed to use outs, the audio is heard normally.

**Comment by vlazzarini** [comment] 2015-03-27 14:52
any update on this. We'd like to clear this for the upcoming release if possible

**Comment by gogins** [comment] 2015-03-27 15:04
Fixing this would require changes to the way that alwayson inserts events,
or maybe even to the way that the engine schedules events. I think Steven
should look at this as he is much more familiar with the parser and engine
code than I am.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-03-27 15:10
OK, I will assign this to him.

**Comment by gogins** [comment] 2015-04-03 18:14
I do not think this should have been reassigned to Rory. It has to do with how alwayson instances are scheduled in the Csound engine. When csoundRewindScore is called to rewind the score, the performance starts over from score time 0, but the alwayson instances are not restarted. If these instances are scheduled in the score starting at time 0 and going for duration -1, it should work.

I think the reason is that alwayson is usually called from the orchestra header. I think a hacky solution would be to modify the orchestra parser to stash these alwayson invocations somewhere and have them re-triggered when the score is rewound. But I don't like this idea. The way I implemented alwayson in the first place was a bit of a hack and now it is biting back.

**Comment by vlazzarini** [comment] 2015-04-03 18:22
That was not meant to be reassigned to rory. See my other email. I will tackle this (see it is assigned to me).

**Comment by gogins** [comment] 2015-04-03 18:26
Sorry about that! I appreciate your looking into this.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-07 12:44
I am trying to get round to understanding this. I have looked at the rewind code and could not find where
tables are discarded. So I prepared a simple test CSD
''' 
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

instr 1
i1 ftgenonce 1,0,16384,10,1
a1 oscili 0dbfs/4, 440, 1
   out a1
endin

instr 2
rewindscore
endin
</CsInstruments>
<CsScore>
i1 0 1 
i2 2 0.1
</CsScore>
</CsoundSynthesizer>
'''

and when I run it, ftgeonce just says it is reusing the existing table, which has not been discarded:

'''
ftgenonce: created new func: 1
B  0.000 ..  2.000 T  2.000 TT  2.000 M:   8192.0
new alloc for instr 2:
end of section 1	 sect peak amps:   8192.0
SECTION 1:
ftgenonce: re-using existing func: 1.000000
B  0.000 ..  2.000 T  2.000 TT  2.000 M:   8192.0
end of section 1	 sect peak amps:   8192.0
SECTION 1:
ftgenonce: re-using existing func: 1.000000
B  0.000 ..  2.000 T  2.000 TT  2.000 M:   8192.0
end of section 1	 sect peak amps:   8192.0
SECTION 1:
ftgenonce: re-using existing func: 1.000000
^C
csound command: Interrupt
csoundPerform(): stopped.
inactive allocs returned to freespace
end of score.		   overall amps:   8192.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 7.779s, CPU: 0.078s
closing device
330 1024 sample blks of 64-bit floats written to dac
'''

Maybe @gogins  can clarify how I could get a simple example demonstrating the issue.

**Comment by vlazzarini** [comment] 2015-04-07 13:45
I read the comments again and there appears to be two issues: 1) ftgenonce; 2) alwayson. Not sure which one is to be tackled, but 1) does not seem to be a problem (tables are not deleted).

With regards to 2), I think this is a more complex issue. What happens is this: there are two source
of score events for Csound: the compiled score and realtime events. The way the system works is that
the compiled score can be rewound, but not realtime events (they are not kept). Changing this is a major overhaul of the system. 

Alwayson (like everything else but the first score provided to Csound) uses realtime events. So, its
event is not recorded anywhere. On score rewind, Csound kills all instances before rewinding the
compiled score. When it does, alwayson will not start a new event. If however, rewind is accompanied by a compilation, then it will do, as instrument 0 gets evaluated and always on is called. If a restart of alwayson is what is requested, then I think that is the best solution, csoundCompileCsd() should do it.

On the other hand, if the intention is that instances created by always on never get killed, then I will have to look at marking these and making sure they are not affected. That might be possible with an extra field in INSDS.

**Comment by gogins** [comment] 2015-04-07 14:41
Thanks for your analysis. Sounds right to me. I will see if it makes sense
to recompile on rewind for CsoundVST. That might be an adequate workaround.

Regards,
Mike

**Comment by vlazzarini** [comment] 2015-04-07 15:29
Ok, here's a CSD that mimics what I am proposing

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>
alwayson 3
instr 1
i1 ftgenonce 1,0,16384,10,1
a1 oscili 0dbfs/4, 440, 1
   out a1
endin

instr 2
rewindscore
i1 compilestr {{ 

alwayson 3
instr 1
 i1 ftgenonce 1,0,16384,10,1
 a1 oscili 0dbfs/4, 440, 1
   out a1
endin

instr 3
 a1 rand 0dbfs/20
  out a1
endin

}}

endin

instr 3
a1 rand 0dbfs/20
  out a1
endin

</CsInstruments>
<CsScore>
i1 0 1 
i2 2 0.1
</CsScore>
</CsoundSynthesizer>
```

after rewindscore, I recompile the orchestra (minus instr 2). In your case, instr 2 is performed by your C++ code.

**Comment by vlazzarini** [comment] 2015-04-07 15:31
Would it be OK, if I close this? If it does not work for you, please reopen it.

**Comment by gogins** [comment] 2015-04-12 01:30
I tried the workaround of recompiling the orc immediately before or immdiately after repositioning the score pointer. This did not work. The problem is in alwayson.

**Comment by vlazzarini** [comment] 2015-04-12 09:30
I don't understand, with a new compilation, as in my example above, there is no reason why alwayson will not reinstantiate the instrument. 
Why is it different from that example? 

I will need some way of testing this, as I do not have CsoundVST. Can you provide a simple commandline C frontend and simple CSD?

**Comment by gogins** [comment] 2015-04-12 12:41
Please obtain CsoundVST. The issue is specific to CsoundVST. You can get it
in the windows installer that I host on michaelgogins.tumblr.com and run it
in vsthost.

Regards,
Mike

Regards,
Mike

**Comment by vlazzarini** [comment] 2015-04-12 12:46
does it run on OSX?

**Comment by vlazzarini** [comment] 2015-04-12 12:52
I cannot debug on Windows. Surely if this is a Csound issue, it can be demonstrated with a simpler frontend. If it a specific frontend issue, then it needs to be solved at that level.

**Comment by gogins** [comment] 2015-04-12 17:24
It is a Csound issue that appears because CsoundVST rewinds the score to
support looping in sequencers. I will write a python script to reproduce
the issue. Can you use that?  Or I could write a one file C++ console
program.

Regards,
Mike

**Comment by vlazzarini** [comment] 2015-04-12 17:45
either would do, with a simple CSD, thanks.

**Comment by gogins** [comment] 2015-04-14 01:23
I have mailed Victor a C++ program of one file with an embedded orc that reproduces the problem. Look at lines 110-114 or so to see my comments about the problem.

**Comment by gogins** [comment] 2015-04-14 01:26
I have attached a one file C++ program that reproduces the problem. Compile
for C++11. The orchestra is a string literal in the program code.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-14 06:17
Thanks, I will look at this now.

**Comment by vlazzarini** [comment] 2015-04-14 10:35
Ok; calling csoundCompileOrc() after csoundRewind() does work: the alwayson instruments get re-instantiated. However, there is something not quite right with the inlet code. It will occasionally crash under recompilation at this point: (signalflowgraph.cpp:409)

 ``if (sourceOutlet->opds.insdshead->actflg)``

the reason is that (for some reason), the memory pointed by sourceOutlet->opds is invalid (sometimes opds is empty, sometimes it has garbage). So I am not sure why this is the case, but it could be something to do with cleanup etc.

If I make the example only recompile the "always on" lines, it runs perfectly with no crashes. But it is important to fix the crash because users might want to be able to recompile instruments that use inlet opcodes.

Here is the relevant part of the code I changed to demonstrate this:

```
std::printf("Now looping with csoundRewindScore...\n");
    for (auto rewind = 1; ;rewind++) {
        std::printf("Loop %d\n", rewind);
	csoundRewindScore(csound);
	std::printf("compile %d\n", rewind);
	csoundCompileOrc(csound,orc);
	std::printf("run %d\n", rewind);
        for (tyme = 0, kperiods = 0; tyme < 20.0; tyme += ksmps_tyme, ++kperiods) {
            if ((kperiods % 80) == 0) {
                double key = double(std::rand()) / double(RAND_MAX) * 60.0 + 36.0;
                std::sprintf(buffer, "i %9.4f %9.4f %9.4f %9.4f %9.4f %9.4f\n", 1.0, 0.0, 4.0, key, 40.0, 0.5);
                csoundInputMessage(csound, buffer);
            }
            csoundPerformKsmps(csound);
        }
    }

```

changing the csoundCompileOrc() line to this will make it work with no crash:

```
csoundCompileOrc(csound, "alwayson                \"Reverberation\" \n"
                                  "alwayson                \"MasterOutput\" "
```

**Comment by vlazzarini** [comment] 2015-04-14 11:18
Looking at these opcodes, it strikes me that it appears that memory is never cleared until module_destroy(). This is going to cause growth on recompilation. To avoid that, memory needs to be allocated with AuxAlloc etc. The other alternative is to add destructors for the opcodes (but then there will be overheads on instantiation/deactivation).

**Comment by gogins** [comment] 2015-04-14 11:42
I had already tried recompiling the orc in CsoundVST as you have in the
example, and it did not work for me, which is why I reopened this issue. I
will do something about the inlet tests and try that again.

I am aware of the memory growth and consider it acceptable in my use cases,
compared with the cost of trying to fix this.

Regards,
Mike




-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-14 12:03
Ok; recompiling fixes this, as I demonstrated in the example you supplied. So we need to know why it does not work for CsoundVST, and get a closer test case. Let me know how you proceed.

However what is worrying me know is the memory management in these opcodes. It will clear go wrong if users attempt to employ them in a live-coding scenario or somewhere where recompilation is used. Also I am not sure how significant the growth will be in the case of thousands of opcode instances over a long period.

**Comment by gogins** [comment] 2015-04-14 12:33
Running with valgrind would tell us about the memory usage. I don't have
this on Windows, do you have it on OS X?

I do however have drmemory on Windows, and I will try that.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by jpffitch** [comment] 2015-04-14 13:15
Coverity defects 27356-27371 not marked as fixed are all resiurce/memory 
leaks from CsiunAC as far as I can tell.  Might be a place to start
==John ff

**Comment by gogins** [comment] 2015-04-15 00:54
I have found another wrinkle. I made the example program more like what
happens in CsoundVST where the score is turned off and on, and seeks to a
specific point in time.

Even with your changes and which recompiling only the alwayson statements,
which I have tested and which worked in the original form of the example,
the new example fails if csoundSetScoreOffsetSeconds is called (see lines
170-171).

I tried debugging this but didn't get very far. One thing I noticed is that
csoundRewindScore and csoundSetScoreOffsetSeconds call each other, although
this didn't seem to cause a stack blowout.

Also note that in the new example the orc is recompiled AFTER all these
other calls.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-15 06:15
Can you send me the program?

**Comment by gogins** [comment] 2015-04-15 11:46
I did send you the cpp file, did you not get it? Here it is again. At the
top of the program in a comment is the command I used to compile it, you
can change the paths to compile it yourself.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-15 11:52
I don't have the new program with csoundSetScoreOffsetSeconds(), can you mail to me again?

**Comment by gogins** [comment] 2015-04-15 12:40
Yes I did send it to you. It is an attachment to my email. Is your email
program not showing you attachments? Just in case, here is the text of the
cpp file.

Regards,
Mike

#include <csound.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>

/**
 * Something like this to build:
 *
 * g++ alwayson.cpp -o alwayson -O2 -g -mtune=native -std=c++0x
-ID:/msys/local/include -IC:/Program_Files_x86/Csound6/include/csoundac
-IC:/Program_Files_x86/Csound6/include/csound
-IC:/Program_Files_x86/Csound6/frontends/CsoundAC
-LC:/Program_Files_x86/Csound6/bin -lCsoundAC -lcsnd6 -lcsound64 -lpthread
-lm
 */

int main(int argc, const char ** argv)
{
    std::printf("DEMONSTRATE ISSUE WITH ALWAYSON AND REWIND\n");
    auto csound = csoundCreate(0);
    csoundInitialize(0);
    auto orc = R"(
sr                              =                       48000
ksmps                           =                       100
nchnls                          =                       2

iampdbfs                        init                    32768
                                prints                  "Default amplitude
at 0 dBFS:  %9.4f\n", iampdbfs
idbafs                          init                    dbamp(iampdbfs)
                                prints                  "dbA at 0 dBFS:
            %9.4f\n", idbafs
iheadroom                       init                    6
                                prints                  "Headroom (dB):
            %9.4f\n", iheadroom
idbaheadroom                    init                    idbafs - iheadroom
                                prints                  "dbA at headroom:
            %9.4f\n", idbaheadroom
iampheadroom                    init                    ampdb(idbaheadroom)
                                prints                  "Amplitude at
headroom:        %9.4f\n", iampheadroom
                                prints                  "Balance so the
overall amps at the end of performance -6 dbfs.\n"


giFlatQ                         init                    sqrt(0.5)
giseed            init                    0.5


gkReverberationEnabled          chnexport
"gkReverberationEnabled", 1
gkReverberationEnabled          init                    0
gkReverberationDelay            chnexport
"gkReverberationDelay", 1
gkReverberationDelay            init                    0.75
gkReverberationWet           chnexport               "gkReverberationWet", 1
gkReverberationWet           init                    0.25

gkMasterLevel                   chnexport               "gkMasterLevel", 1
gkMasterLevel                   init                    1.5

                                connect                 "FMWaterBell",
     "outleft", "Reverberation",        "inleft"
                                connect                 "FMWaterBell",
     "outright", "Reverberation",        "inright"
                                connect                 "Reverberation",
     "outleft", "MasterOutput",         "inleft"
                                connect                 "Reverberation",
     "outright", "MasterOutput",         "inright"

                                alwayson                "Reverberation"
                                alwayson                "MasterOutput"

                                instr                   FMWaterBell

//////////////////////////////////////////////
                                // Original by Steven Yi.
                                // Adapted by Michael Gogins.

//////////////////////////////////////////////
i_instrument                    =                       p1
i_time                          =                       p2
i_duration                      =                       p3
i_midikey                       =                       p4
i_midivelocity                  =                       p5
i_phase                         =                       p6
i_pan                           =                       p7
i_depth                         =                       p8
i_height                        =                       p9
i_pitchclassset                 =                       p10
i_homogeneity                   =                       p11
ipch                            =                       cpsmidinn(i_midikey)
iamplitude                      =
ampdb(i_midivelocity) * 2.0
ipch2                           =                       ipch
kpchline                     line                    ipch, i_duration, ipch2
iamp                         =                       2
ienvType                    =                       2
kenv                         init                 0
                                if ienvType == 0 kgoto env0  ; adsr
                                if ienvType == 1 kgoto env1  ; pyramid
                                if ienvType == 2 kgoto env2  ; ramp
env0:
kenv                        adsr                .3, .2, .9, .5
                                kgoto                   endEnvelope
env1:
kenv                         linseg                0, i_duration * .5, 1,
i_duration * .5, 0
                                kgoto                   endEnvelope
env2:
kenv                        linseg                 0, i_duration - .1, 1,
.1, 0
kgoto                           endEnvelope
endEnvelope:
kc1                             =                       5
kc2                             =                       5
kvdepth                         =                       0.005
kvrate                          =                       6
icosine                      ftgenonce               0, 0, 65536, 11, 1
ifn1                            =                       icosine
ifn2                            =                       icosine
ifn3                            =                       icosine
ifn4                            =                       icosine
ivfn                            =                       icosine
asignal                         fmbell                iamp, kpchline, kc1,
kc2, kvdepth, kvrate, ifn1, ifn2, ifn3, ifn4, ivfn
iattack                         =                       0.003
isustain                        =                       p3
irelease                        =                       0.06
p3                              =                       isustain + iattack
+ irelease
adeclick                        linsegr                 0.0, iattack, 1.0,
isustain, 1.0, irelease, 0.0
aoutleft, aoutright             pan2                    iamplitude *
asignal * adeclick, .75;i_pan
                                ; Loops created with csoundRewindScore make
sound with outs here:
                                ;outs                    aoutleft, aoutright
                                ; Loops created with csoundRewindScore do
not make sound with signal flow graph opcodes here:
                                ; but I think the problem is that the
alwayson instruments get turned off.
                                outleta                 "outleft",  aoutleft
                                outleta                 "outright",
aoutright
                                endin

                                instr                   Reverberation

//////////////////////////////////////////////
                                // By Michael Gogins.

//////////////////////////////////////////////
ainleft                         inleta                  "inleft"
ainright                        inleta                  "inright"
if (gkReverberationEnabled == 0) then
aoutleft                        =                       ainleft
aoutright                       =                       ainright
kdry            =            1.0 - gkReverberationWet
else
awetleft, awetright             reverbsc                ainleft, ainright,
gkReverberationDelay, 18000.0
aoutleft            =            ainleft *  kdry + awetleft  *
gkReverberationWet
aoutright            =            ainright * kdry + awetright *
gkReverberationWet
endif
                                outleta                 "outleft", aoutleft
                                outleta                 "outright",
aoutright
                                endin

                                instr                   MasterOutput

//////////////////////////////////////////////
                                // By Michael Gogins.

//////////////////////////////////////////////
ainleft                         inleta                  "inleft"
ainright                        inleta                  "inright"
aoutleft                        =                       gkMasterLevel *
ainleft
aoutright                       =                       gkMasterLevel *
ainright
                                outs                    aoutleft, aoutright
                                endin

    )";
    csoundSetOption(csound, (char *)"-odac");
    csoundCompileOrc(csound, orc);
    std::printf("We will play 20 seconds from the start, then we will loop
every 20 seconds indefinitely.\n");
    double ksmps_tyme = 100.0 / 48000.0;
    std::printf("Time per kperiod: %9.4f seconds.\n", ksmps_tyme);
    char buffer[0x500];
    csoundStart(csound);
    double tyme;
    int kperiods;
    for (tyme = 0, kperiods = 0; tyme < 10.0; tyme += ksmps_tyme,
++kperiods) {
        if ((kperiods % 80) == 0) {
            double key = double(std::rand()) / double(RAND_MAX) * 60.0 +
36.0;
            std::sprintf(buffer, "i %9.4f %9.4f %9.4f %9.4f %9.4f %9.4f
%9.4f\n", 1.0, 0.0, 4.0, key, 40.0, 0.5);
            csoundInputMessage(csound, buffer);
        }
        csoundPerformKsmps(csound);
    }
    std::printf("Now looping with csoundRewindScore...\n");
    for (auto rewind = 1; ;rewind++) {
        std::printf("Loop %d\n", rewind);
        //csoundRewindScore(csound);
        // Uncommenting the next line causes failure.
        csoundSetScoreOffsetSeconds(csound, 1.0);
        std::printf("Compile %d\n", rewind);
        // Recompiling the full orchestra causes failure.
        csoundCompileOrc(csound, "alwayson                \"Reverberation\"
\n"
                                  "alwayson                \"MasterOutput\"
");
        csoundSetScorePending(csound, 1);
       for (tyme = 0, kperiods = 0; tyme < 10.0; tyme += ksmps_tyme,
++kperiods) {
            if ((kperiods % 80) == 0) {
                double key = double(std::rand()) / double(RAND_MAX) * 60.0
+ 36.0;
                std::sprintf(buffer, "i %9.4f %9.4f %9.4f %9.4f %9.4f %9.4f
%9.4f\n", 1.0, 0.0, 4.0, key, 40.0, 0.5);
                csoundInputMessage(csound, buffer);
            }
            csoundPerformKsmps(csound);
        }
        csoundSetScorePending(csound, 0);
    }
    return 0;
}



-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-17 15:03
Ok, I figured out what is happening here. Since alwayson schedules from time 0.0, the fact that you have
advanced by 1 sec means its events are ignored. If I replace alwayson with schedule:

```
csoundCompileOrc(csound, 
"schedule \"Reverberation\", 1.0, -1 \n"
"schedule \"MasterOutput\", 1.0, -1 \n");
```

then I get sound.

**Comment by gogins** [comment] 2015-04-17 15:39
Thanks, that tells us what is really going on.

Unfortunately it doesn't help with the use case. The author of the orc and
sco should not have to change them so that moving the loop points in a
sequencer will continue to work.

To get things like this to work maybe we need a score opcode, or a new form
of the schedule opcode. Instead of starting at a given time, it would
always start when performance starts, even if that time has been advanced.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-17 21:54
There is a generally straightforward solution for this particular issue: if alwayson is made to start the instances at the offset time, then we have sound. I have tested this and it works. I get the offset with the csound->GetScoreOffsetSeconds() and use it to fill p2.

If you think this modification to alwayson is fair, then we can go with it.

**Comment by gogins** [comment] 2015-04-18 01:27
This does not suit the use case.

The way this is designed to be used is as follows.

The user writes a Csound orchestra that uses the signal flow graph opcodes
to chain together instrument definitions with effects, as in the example
cpp file. The effects in this chain are always supposed to be on during the
performance, no matter when starts, stops, and stops.

In CsoundVST, it may be the case that the instruments are instantiated to
play two different kinds of events: score events stored in the Csound
preset csd file, and real-time events from the sequencer. In either case,
in using the sequencer, in "tracking", the user will often set a loop point
where a segment of the music will repeat over and over while the user
overdubs music on top of it. I specifically created the csoundScoreRewind,
csoundSetScoreOffsetSeconds, and csoundSetScorePending API calls to support
exactly this use case.

The user sets a loop and presses the sequencer start button. The sequencer
needs to play starting at the loop beginning.

In the following, understand that the VST host keeps a running timestamp
going. Every time CsoundVST processes a block of samples, it compares the
Csound score timestamp with the VST host's timestamp to see if it is
necessary to rewind the Csound score to match the host time. In that case
csoundSetScoreOffsetSeconds is called by CsoundVST to advance the Csound
score to that point time. It is important that the alwayson opcodes have
started their instrument instances at this point without the user having to
edit any Csound code. That would be inconvenient and should be unnecessary.
The sequencer plays to the end of the loop and starts over at the
beginning. CsoundVst calls csoundSetScorePending(false) to turn off any
notes that might be hanging at the end of the loop, calls csoundRewindScore
to go back to the beginning of the score, calls csoundSetScoreOffsetSeconds
to advance the score time to the beginning of the loop, and calls
csoundSetScorePending(true) to turn the score back on.

It's OK for alwayson to do what its name literally means -- always be on.
The alwayson instruments in this use case are processing signals, not
generating them.

This is why I wanted you to debug with CsoundVST, I didn't think you would
understand the intention of the opcodes without using them as they are
intended to be used.

It would defeat the whole purpose of these opcodes if, after setting a loop
in the sequencer, the user had to stop play, edit the Csound orchestra to
manually match the loop points, and start play again. This is all supposed
to be smooth, automatic, and transparent. If you don't use the alwayson
opcodes, then it is smooth, automatic, and transparent, but then you can't
use the signal flow graph opcodes to connect the instrument definitions to
the effects. You could use global variables to do the same thing, but I
designed this whole system to make it simple to truly encapsulate the
instrument definitions and leanly separate them from each other and from
the rest of the orchestra using named inlets and outlets. In a non-VST
setting everything works as designed and I use this stuff for all my pieces.

So the question is, is there any way to code the alwayson opcode or set up
a schedule event (the C code of which is borrowed for the opcode) so that
when csoundStartm csoundRewindScore, csoundSetScoreOffsetSeconds, or
csoundSetScorePending(true) is called, the alwayson instrument always turns
on at that time and then just keeps playing without the user having to code
the time?

I hope this is clearer...

Regards,

Mike

**Comment by vlazzarini** [comment] 2015-04-18 06:41
There is no need to manually edit loop points, on recompilation alwayson starts immediately from whatever offset the score was given.

Also note that there is no need for the scorepending calls. On rewind all events are turned off regardless of where they come from. This is the normal operation, which has always been this way.

**Comment by gogins** [comment] 2015-04-18 10:37
On Apr 18, 2015 2:41 AM, "vlazzarini" <notifications@github.com> wrote:
>
> There is no need to manually edit loop points, on recompilation alwayson
starts immediately from whatever offset the score was given.

So you are saying CsoundVST should send a score offset event instead of
calling csoundSetScoreOffsetSeconds?

> Also note that there is no need for the scorepending calls. On rewind all
events are turned off regardless of where they come from. This is the
normal operation, which has always been this way

Got it.

Regards,
Mike

**Comment by vlazzarini** [comment] 2015-04-18 11:36
The only thing that CsoundVST would need to do in this case is recompile, to re-instantiate and run the alwayson opcodes. Inside alwayson we check for any existing offset and schedule the event accordingly.
The modification I am proposing is to add this check for offset in alwayson.

**Comment by gogins** [comment] 2015-04-18 12:36
That is clear now. I will try this or you can of you prefer.

Regards,
Mike

**Comment by vlazzarini** [comment] 2015-04-18 12:44
I tested this with your program and it works. I will commit the alwayson changes as soon as I have a chance today and you could test them thanks

**Comment by vlazzarini** [comment] 2015-04-18 13:17
Committed, ready for you to review & test.

**Comment by gogins** [comment] 2015-04-18 13:26
I will rebuild here now and test, should have a result in an hour or so.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment] 2015-04-18 22:47
I have rebuilt and am testing. I modified the test program. This now loops
as advertised with the signal flow graph opcodes and alwayson. I am now
going to try this in Reaper.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-18 22:50
Thanks. Just remember that recompiling the whole orchestra is still prone to crashes due to garbage in memory.

**Comment by gogins** [comment] 2015-04-18 22:57
I have debugged CsoundVST in reaper and found an access violation in line
409 of signalflowgraph.cpp:

                    if (sourceOutlet->opds.insdshead->actflg) {

I belive this is the same as or similar to what you saw. It seems to me
that stopping, rewinding, and continuing to play are not thread safe in VST
performance. I probably just need to quit processing audio until Csound is
done recompiling. I will try that soon.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-18 23:04
yes, that is the same. All of these operations are thread-safe, however the problem is this: the global sourceOutlet memory that is referred to by the inlet opcodes contains garbage after a new compilation, as it is not updated to reflect the old instances (INSDS) that have been removed from memory. Because of this, then we have crashes with these opcodes.

**Comment by gogins** [comment] 2015-04-19 01:22
So the inlets and other global collections need to be cleaned up before
re-compiling. I'll see what I can do about that.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2015-04-19 09:15
That's right. Maybe it will be sufficient to delete an outlet from this list when the opcode instance is destructed, by registering a DeInit callback that does it.

**Comment by gogins** [comment] 2015-04-21 12:46
I think I have fixed this. I made two changes in signalflowgraph.cpp, one in the inlet opcodes to clear the source outlet array every time before adding sources (this was a logic bug), the other in the outlet opcodes to remove the outlet opcode instance from the outlets map when the outlet opcode goes away. Reaper now loops with the CsoundVST.csd example which has many instruments using ftgenonce, alwayson, signal flow graph opcodes, etc. Other csds that use these opcodes in other environments still seem to be working.

**Closed by gogins** 2015-04-21 12:46 UTC
Labels: bug
