### ISSUE TITLE
GEN31 bug

### ISSUE THREAD

**Issue by iainmccurdy** [csound/csound#629] opened 2016-04-09 09:38 UTC
GEN31 seems to stop working properly if a partial limit is breached. For example:

```
gisine  ftgen  0,0,4096,10,1
gi31    ftgen  0,0,4096,31,gisine, 1,1,0, 2,1,0, 3,1,0, 4,1,0, 5,1,0

```
On Windows Csound ver. 6.07 beta, if a 6th partial is added to gi31, only a fundamental partial is created (PN=1) regardless of any values for partials that are supplied.

On Mac, 6.07 Apr. 1, when gi31 uses more than 2 partials, the same behaviour normally results, but I have found this not to be entirely consistent - occasionally more than 2 partials can be created.
On CsoundQt and Cabbage I have found variable inconsistent behaviour so I suggest testing from the command line.
I think this bug may not be entirely new, I recall encountering problems  some time ago, but only got around to investigating it now.
Iain

**Comment by vlazzarini** [comment] 2016-04-09 09:49
what would be the correct behaviour?

**Comment by iainmccurdy** [comment] 2016-04-09 10:18
GEN31 should function similarly to GEN09 (but allowing replacing sinusoidal partials with a user-defined partial function). The manual entry suggests there is no limitation on the number of partials that can be summed but practice indicates that limits of 5 and 2 seem to exist on Windows and Mac respectively.
On Windows, gi31 above generates the first 5 harmonic partials but adding a 6th causes it to only generate a fundamental (pn=1). On Mac the same thing happens when going beyond 2 partials.

**Comment by vlazzarini** [comment] 2016-04-09 12:06
I just ran your code here on OSX and got
```
table 102:	4096 points, scalemax 1.000
  _'
    _


 .
     '

          .'.
      '  _   .    --_     _
_________________'___.___'_'.___.-'.____.-._____..______.______________________
'              '      '-     '-'    '..'   '._.'   .  .'  .   .' -    _ -
                                                    ''     -.-    .
                                                                   ._'   -

                                                                              -
                                                                          .


                                                                           . -
                                                                            _

```
Five harmonics. Looks like it works on OSX. I tried more harmonics and
got them.

**Comment by iainmccurdy** [comment] 2016-04-09 14:12
On OSX there seems to be an interaction with using the -m0 flag - i.e. if it is not used, GEN31 works.

Using the following csd:

```
<CsoundSynthesizer>
<CsOptions>
-odac -m0
</CsOptions>
<CsInstruments>
0dbfs = 1
gisine  ftgen   0,0,4096,10,1
gi31    ftgen   0,0,4096,31,gisine, 1,1,0, 2,1,0, 3,1,0
instr 1
 a1 poscil  0.3,300,gi31
    out a1
endin
</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>
```

Behaviour is not consistent. Table 102 either comes out as:

`ftable 102:	4096 points, scalemax   nan`

or

```
ftable 102:	4096 points, scalemax 1.000
                                                      _.-'''''--_
                                                    .'           '-_
                                                  .'                -_
                                                .'                    .
                                              _-                       '_
                                             .                           .
                                            -                             -
                                          _'                               '_
                                         .                                   .
________________________________________._____________________________________-
 _                                     -
  .                                  _'
   -                                .
    '_                             -
      .                          _'
       -_                       .
         .                    _'
          '.                _-
            '._           _-
               -.______.-'

```
 When -m0 is removed, all works fine.

**Comment by vlazzarini** [comment] 2016-04-09 20:16
Can't reproduce it here. This is what I get with your CSD
```
ligeti:debug victor$ ./csound 31.csd
time resolution is 1000.000 ns
virtual_keyboard real time MIDI plugin for Csound
WARNING: STK opcodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
0dBFS level = 32768.0
Csound version 6.07 beta (double samples) Apr  6 2016
libsndfile-1.0.21
UnifiedCSD:  31.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: PortAudio module enabled ... 
using callback interface
rtmidi: PortMIDI module enabled
sorting score ...
	... done
--Csound version 6.07 beta (double samples) Apr  6 2016
graphics suppressed, ascii substituted
0dBFS level = 1.0
ftable 101:	4096 points, scalemax 1.000
               .-''''''-._
            _-'           '.
          _-                '.
         -                    '_
       .'                       -
      -                          '_
    _'                             .
   .                                -
  -                                  '_
_'_____________________________________._______________________________________
                                        -                                     .
                                         -                                   -
                                          '_                               _'
                                            .                             .
                                             -                           -
                                              '.                       _'
                                                -_                    -
                                                  -_                .'
                                                    -_           _.'
                                                      '-._____..'
ftable 102:	4096 points, scalemax 1.000
      _-''-
     _     '_
             _
    '
   .          '
               -
  -             -
                 .             _.-..
 '                .          .'     '.
___________________._______.'_________'_______________-'''-____________________
'                   '.___.'             -          _-       .
                                         '.      _-          .                -
                                           '-..-'             .
                                                               _             -
                                                                _
                                                                            '
                                                                 '         .
                                                                  -       _
                                                                   -     _
                                                                    '.__.
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Feb 12 2010 09:42:54)
   0: dac0 (AirPlay)
   1: dac1 (Built-in Output)
   2: dac2 (Soundflower (2ch))
   3: dac3 (Soundflower (64ch))
   4: dac4 (Aggregate Device)
PortAudio: selected output device 'Built-in Output'
writing 1024 sample blks of 64-bit floats to dac 
SECTION 1:
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  0.29979
	   overall samples out of range:        0
0 errors in performance
closing device
44 1024 sample blks of 64-bit floats written to dac
```

**Comment by iainmccurdy** [comment] 2016-04-09 20:39
Thanks for trying it out Victor. It's a bit mysterious that you can't reproduce it but as I am getting problems on two different machines with different OSs I can only assume that there is some sort of an issue. I'll do some more investigating and hopefully some others can take a look also.

**Comment by vlazzarini** [comment] 2016-04-09 20:51
yes, it is strange. We'll keep it open.

**Comment by vlazzarini** [comment] 2016-04-09 21:50
Just checking: if you define the tables in the score, do you get the same behaviour?

**Comment by iainmccurdy** [comment] 2016-04-10 09:29
Good suggestion. It works fine if the tables are in the score.

**Comment by jpffitch** [comment] 2016-04-11 14:33
Sounds suspiciously like memory overwriting; has it been tried with valgrind?
=7018== Use of uninitialised value of size 8
==7018==    at 0x58A5E6F: __GI_mempcpy (in /lib64/libc-2.19.so)
==7018==    by 0x589685D: _IO_default_xsputn (in /lib64/libc-2.19.so)
==7018==    by 0x5868E91: vfprintf (in /lib64/libc-2.19.so)
==7018==    by 0x586C310: buffered_vfprintf (in /lib64/libc-2.19.so)
==7018==    by 0x586739D: vfprintf (in /lib64/libc-2.19.so)
==7018==    by 0x4F9B073: csoundMessage (csound.c:2308)
==7018==    by 0x4EA601E: DrawAscii_ (winascii.c:72)
==7018==    by 0x4EA60D8: DrawAscii (winascii.c:83)
==7018==    by 0x4EA652E: display (window.c:180)
==7018==    by 0x4E7F0E9: ftresdisp.isra.4 (fgens.c:2273)
==7018==    by 0x4E815B0: hfgens (fgens.c:267)
==7018==    by 0x4FBEF02: ftgen_ (ftgen.c:155)
==7018==    by 0x4FBEF02: ftgen (ftgen.c:165)
==7018== 
 '         .       _-'-_
==7018== Use of uninitialised value of size 8
==7018==    at 0x58A5EF2: __GI_mempcpy (in /lib64/libc-2.19.so)
==7018==    by 0x589685D: _IO_default_xsputn (in /lib64/libc-2.19.so)
==7018==    by 0x5868E91: vfprintf (in /lib64/libc-2.19.so)
==7018==    by 0x586C310: buffered_vfprintf (in /lib64/libc-2.19.so)
==7018==    by 0x586739D: vfprintf (in /lib64/libc-2.19.so)
==7018==    by 0x4F9B073: csoundMessage (csound.c:2308)
==7018==    by 0x4EA601E: DrawAscii_ (winascii.c:72)
==7018==    by 0x4EA60D8: DrawAscii (winascii.c:83)
==7018==    by 0x4EA652E: display (window.c:180)
==7018==    by 0x4E7F0E9: ftresdisp.isra.4 (fgens.c:2273)
==7018==    by 0x4E815B0: hfgens (fgens.c:267)
==7018==    by 0x4FBEF02: ftgen_ (ftgen.c:155)
==7018==    by 0x4FBEF02: ftgen (ftgen.c:165)

Which looks like a different problem!
I see

**Comment by jpffitch** [comment] 2016-09-10 17:54
More importatly....

==5752== Conditional jump or move depends on uninitialised value(s)
==5752==    at 0x4E839BD: gen31 (fgens.c:1804)
==5752==    by 0x4E7D63F: hfgens (fgens.c:282)
==5752==    by 0x4FC3972: ftgen_ (ftgen.c:155)
==5752==    by 0x4FC3972: ftgen (ftgen.c:165)
==5752==    by 0x4E87368: init0 (insert.c:64)
==5752==    by 0x4E90111: musmon (musmon.c:228)
==5752==    by 0x4FA4B2B: csoundStart (main.c:508)
==5752==    by 0x40153A: main (csound_main.c:316)
==5752== 
==5752== Conditional jump or move depends on uninitialised value(s)
==5752==    at 0x554F769: sincos (in /lib64/libm-2.19.so)
==5752==    by 0x4E839DE: gen31 (fgens.c:1804)
==5752==    by 0x4E7D63F: hfgens (fgens.c:282)
==5752==    by 0x4FC3972: ftgen_ (ftgen.c:155)
==5752==    by 0x4FC3972: ftgen (ftgen.c:165)
==5752==    by 0x4E87368: init0 (insert.c:64)
==5752==    by 0x4E90111: musmon (musmon.c:228)
==5752==    by 0x4FA4B2B: csoundStart (main.c:508)
==5752==    by 0x40153A: main (csound_main.c:316)
==5752== 

which is odd as the line of code looks OK
      p -= (MYFLT) ((int) p); if (p < FL(0.0)) p += FL(1.0); p *= TWOPI_F;

**Comment by jpffitch** [comment] 2016-09-10 19:42
OK the code was wrong; the loop counted in 1s when should have been in 3s (for freq, amp, phase)

Fixed in git

**Closed by jpffitch** 2016-09-10 19:42 UTC
