### ISSUE TITLE
Issue with -Q flag (midi out device) on macOS

### ISSUE THREAD

**Issue by boonier** [csound/csound#1784] opened 2023-11-10 10:29 UTC
Issue found on M1 Macbook Pro (macOS Monterey 12.6, Csound 6.18.1)

No midi data is sent when running directly from the command line (or from vs code extension, which is essentially the same). I also ran with this flag `"--midioutfile=test.mid"` from vs code and indeed midi notes were written to the the output midi file. So midi data is being sent, just not from the PortMidi device. 

Weirdly in CsoundQT, using the _Csound Midi Module_ option 
![image](https://github.com/csound/csound/assets/6206789/f061390f-3f98-4fb7-b0f0-0cfa20565a80)

I can see midi data. 
![image](https://github.com/csound/csound/assets/6206789/563d0370-5f55-41d7-bef7-72282b186889)

But if I select the _Run In Terminal_ there is no midi out, so that doesn't make sense to me (is CsoundQT still using it's own internal midi interface still?)

---

*** However, tested on an Intel Macbook Pro (Mojave 10.14.6, Csound 6.18.1) and midi works as normal. So seems to be Silicon/Monterey specific?

**Comment by boonier** [comment] 2023-11-10 11:36
https://github.com/csound/csound/assets/6206789/3c6f403b-1f6a-4789-825c-75054cdcfc8e

**Comment by vlazzarini** [comment] 2023-11-10 11:40
I can't reproduce this. 

Here's my test code:

```
<CsoundSynthesizer>
<CsOptions>
-odac -Q0
</CsOptions>
<CsInstruments>
0dbfs = 1

instr 1
noteon 1,60,64
endin

instr 2
noteoff 1,60,64
endin

</CsInstruments>
<CsScore>
i1 0 0.001
i2 1 0.001
</CsScore>
</CsoundSynthesizer>
```


With Csound 6.18, I get

```
usr/local/bin/csound midinoteout.csd
UnifiedCSD:  midinoteout.csd
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 44100.0, kr = 4410.000, ksmps = 10
0dBFS level = 1.0, A4 tuning = 440.0
0: IAC Driver Bus 1 (portmidi)
PortMIDI: selected output device 0: 'IAC Driver Bus 1' (CoreMIDI)
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19.7.0-devel, revision 147dd722548358763a8b649b3e4b41dfffbcfbb6
   0: dac0 (BlackHole 2ch [Core Audio, 2 in, 2 out])
   1: dac1 (MacBook Pro Speakers [Core Audio, 0 in, 2 out])
   2: dac2 (Microsoft Teams Audio [Core Audio, 2 in, 2 out])
   3: dac3 (ZoomAudioDevice [Core Audio, 2 in, 2 out])
   4: dac4 (Multi-Output Device [Core Audio, 0 in, 2 out])
   5: dac5 (Aggregate Device [Core Audio, 3 in, 4 out])
PortAudio: selected output device 'MacBook Pro Speakers'
writing 1024 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:
B  0.000 ..  1.000 T  1.000 TT  1.000 M:  0.00000
new alloc for instr 2:
B  1.000 ..  1.001 T  1.001 TT  1.001 M:  0.00000
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 1.126s, CPU: 0.029s
closing device
44 1024 sample blks of 64-bit floats written to dac
```

and sound is played from the DAW plugin I have on.

**Comment by boonier** [comment] 2023-11-10 11:44
huh, ok your example works for me. 

Could I be mis-using `noteondur`?

```<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 64
nchnls = 2
0dbfs = 1

seed 0


instr MidiNote
	idur = p3
	ifrq  = p4
	iamp = p5
	prints "nn %d, amp %f, dur %f\n", ifrq, iamp, idur
	; send on chn 2 iac bus
	noteondur 1, ifrq, iamp, 0.25
endin

instr SeqScheduler
	if metro(4) == 1 then
		schedulek("MidiNote", 0, 0.25, random:k(48,72), floor(random:k(32,100)))
	endif
endin

schedule("SeqScheduler", 0 , -1)

</CsInstruments>
<CsScore>
 
 </CsScore>
</CsoundSynthesizer>```

**Comment by vlazzarini** [comment] 2023-11-10 11:55
I can't see a problem with your code, but you need to run it wih  -QN -odac for it work. I tested it here and it did run

```
/usr/local/bin/csound midinoteout.csd -odac -Q0
```

**Comment by boonier** [comment] 2023-11-10 12:16
yes that's what I've been using 

`csound -Q0 -odac1 notedur\ test.csd `

are you on similar specs to my machine?

thanks

**Comment by vlazzarini** [comment] 2023-11-10 12:43
yes, using M1, with the latest MacOS.

**Comment by boonier** [comment] 2023-11-10 13:03
just so odd...does this file work (it's basically the same as above, but with flags in CsOptions)

[notedur_test.csd.zip](https://github.com/csound/csound/files/13319389/notedur_test.csd.zip)

separately, is this unusual (last line - CoreMIDI bit)?:

```
0: IAC Driver Bus 1 (portmidi)
1: IAC Driver Bus 2 (portmidi)
2: UMC404HD 192k (portmidi)
3: Launch Control (portmidi)
4: Bidule  1 (portmidi)
5: Bidule  2 (portmidi)
6: Bidule  3 (portmidi)
7: Bidule  4 (portmidi)
PortMIDI: selected output device 0: 'IAC Driver Bus 1' (CoreMIDI) <-- this?
```

**Comment by vlazzarini** [comment] 2023-11-10 13:37
Works here. That message comes from portmidi, so it's just what it prints. It does it here too.

```
0: IAC Driver Bus 1 (portmidi)
PortMIDI: selected output device 0: 'IAC Driver Bus 1' (CoreMIDI)
```

**Comment by boonier** [comment] 2023-11-10 14:46
Could the PortMidi driver on my machine be frazzled? I guess it's linked to in compilation step, unless it's a dynamic lib used at runtime?

I honestly don't know what could be happening. The exact same tests on my intel mac are fine.

**Comment by vlazzarini** [comment] 2023-11-10 16:16
did you build it yourself?

Anyway, I don't think so. You said my example code ran for you. So it could be some option that you are not seeing.

If you add an instrument playing audio, can you hear it?

**Comment by boonier** [comment] 2023-11-10 16:24
No didn't build myself...it is from the latest installer on the csound.com download page.

Yes, your noteon/noteoff example did work for me. But the notedur example I provide doesn't. I get the first note-on event, and then a whole bunch of note-off events when terminating Csound. The video above shows what I mean.  

I can hear normal Csound generated output fine, it's just the midi output. Midi input works fine too.

Is it worth me building from source?

**Comment by boonier** [comment] 2023-11-10 16:26
The CsoundQT example I mentioned in the first post where it's working - it's using the api isn't it? Does that use a different midi interface to send data?

**Comment by vlazzarini** [comment] 2023-11-10 16:31
I don't think it is worth it. Did you try audio in the same code? Sounds like something may be blocking processing, or that there is some buffering going on. Maybe the IAC is choking? Try reducing the rate of generation.

Try also printing a message every time you send a note.

**Comment by vlazzarini** [comment] 2023-11-10 17:24
csounqt uses its own midi backend if you set it to "internal". Or portmidi etc if not.

**Comment by boonier** [comment] 2023-11-13 12:27
Fyi I tried running the same test using the `midion` opcode instead, but still get the same results; initial note-on message and no subsequent note-on events, and then a load of note-off events when terminating the csound process.

Other apps are able to send/receive midi data over the same IAC bus with no problems.

So it seems to be specific to the PortMidi -Q flag and my machine!

**Comment by boonier** [comment] 2023-11-13 19:40
https://github.com/rakyll/portmidi/issues/43#issuecomment-1109734652 sounds a bit like what I'm experiencing

**Comment by boonier** [comment] 2023-11-14 12:06
https://github.com/PortMidi/portmidi/releases/tag/v2.0.4

> This release adjusts the data rate limit imposed on MIDI through macOS IAC bus to avoid losing data (this is a macOS limitation, not a PortMidi limitation). Apparently, the limit was significantly dropped somewhere around macOS 12.

@vlazzarini are you on macOS Ventura/Sonoma?

**Comment by vlazzarini** [comment] 2023-11-14 12:08
yes, I'm on the latest MacOS.

**Comment by boonier** [comment] 2023-11-14 20:38
OK I might upgrade - I need to anyway - and report back. 

Thanks

**Comment by kunstmusik** [comment] 2024-01-02 20:22
@boonier @vlazzarini Is there anything remaining for this issue or can we close it?

**Comment by vlazzarini** [comment] 2024-01-02 21:25
@kunstmusik it works for me as I reported above, so I can't do much more.

**Comment by kunstmusik** [comment] 2024-01-02 21:33
Thanks @vlazzarini, I think I'll go ahead and close this. 

@boonier if there any new information please let us know and we can reopen to investigate.

**Closed as completed by kunstmusik** 2024-01-02 21:33 UTC

**Comment by boonier** [comment] 2024-01-03 09:42
Thanks @kunstmusik no new info from me. I'm still on Monterey, but I plan to update to Ventura this month. The only relevant info that I found before was relating to Monterey and IAC bus in the PortMidi repo. I'll see if this changes after I update and report back?

**Comment by boonier** [comment] 2024-01-09 11:13
I updated to Ventura 13.6.3 (latest?) and ran the exact same example above. 

Still exhibits the same issues - in Midi Monitor I get 1 `note on` messages, then nothing throughout the duration of the performance, and when I terminate the performance I get a list of all the `note off` messages printed to Midi Monitor.

So: first note in monitor (and holds note on), subsequent notes - no message in monitor and no sound, then on terminating csd, all notes off.

I've attached the exact same example csd for testing. Perhaps I'm misusing the noteondur2 - if so, then I will feel only slightly silly, but if not, then something deeper is going on on my machine. I suspect that it's my machine as the same example is working fine on my Intel Mac (Mojave).

I am running in console with this command: `csound notedur_test.csd -odac3 -Q0`

`-odac3` are the built in speakers
`-Q0` is IAC Bus 1

Can anyone test in macOS Ventura?

Thanks again

[notedur_test.csd.zip](https://github.com/csound/csound/files/13872893/notedur_test.csd.zip)

also the log from console

```
boonier:Matrix Seq/ $ csound notedur_test.csd -odac3 -Q0                                                 [11:07:59]
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1)
UnifiedCSD:  notedur_test.csd
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
instr Simple uses instrument number 1
instr MidiNote uses instrument number 2
instr SeqScheduler uses instrument number 3
Elapsed time at end of orchestra compile: real: 0.002s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.002s, CPU: 0.001s
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 750.000, ksmps = 64
0dBFS level = 1.0, A4 tuning = 440.0
WARNING: Seeding from current time 1868556275

0: IAC Driver Bus 1 (portmidi)
1: IAC Driver Bus 2 (portmidi)
PortMIDI: selected output device 0: 'IAC Driver Bus 1' (CoreMIDI)
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19.7.0-devel, revision 147dd722548358763a8b649b3e4b41dfffbcfbb6
   0: dac0 (LG ULTRAWIDE [Core Audio, 0 in, 2 out])
   1: dac1 (BlackHole 16ch [Core Audio, 16 in, 16 out])
   2: dac2 (BlackHole 2ch [Core Audio, 2 in, 2 out])
   3: dac3 (MacBook Pro Speakers [Core Audio, 0 in, 2 out])
   4: dac4 (Pro Tools Audio Bridge 16 [Core Audio, 16 in, 16 out])
   5: dac5 (Pro Tools Audio Bridge 2-A [Core Audio, 2 in, 2 out])
   6: dac6 (Pro Tools Audio Bridge 2-B [Core Audio, 2 in, 2 out])
   7: dac7 (Pro Tools Audio Bridge 32 [Core Audio, 32 in, 32 out])
   8: dac8 (Pro Tools Audio Bridge 64 [Core Audio, 64 in, 64 out])
   9: dac9 (Pro Tools Audio Bridge 6 [Core Audio, 6 in, 6 out])
  10: dac10 (Pro Tools Aggregate I/O [Core Audio, 1 in, 2 out])
  11: dac11 (ZoomAudioDevice [Core Audio, 2 in, 2 out])
  12: dac12 (Built-in + Blackhole [Core Audio, 17 in, 18 out])
  13: dac13 (Aggregate Device [Core Audio, 16 in, 16 out])
  14: dac14 (Headphones + Blackhole [Core Audio, 16 in, 16 out])
  15: dac15 (UMC404HD + Blackhole [Core Audio, 16 in, 16 out])
  16: dac16 (Multi-Output Device [Core Audio, 0 in, 2 out])
PortAudio: selected output device 'MacBook Pro Speakers'
writing 2048 sample blks of 64-bit floats to dac3
SECTION 1:
new alloc for instr SeqScheduler:
SeqScheduler
  rtevent:	   T  0.001 TT  0.001 M:  0.00000  0.00000
new alloc for instr MidiNote:
instr 2:  idur = 0.250
  rtevent:	   T  1.003 TT  1.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  2.003 TT  2.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  3.003 TT  3.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  4.003 TT  4.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
^C
csound command: Interrupt
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000  0.00000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 4.173s, CPU: 0.043s
closing device
190 2048 sample blks of 64-bit floats written to dac3```

**Comment by vlazzarini** [comment] 2024-01-09 13:57
the latest is Sonoma and it works here. In fact if I select IAC driver for both input and output Csound instr 1 responds to its own midi scheduling. I added --midi-key=4 and got the sound from both Csound and an external midi program at the same time. I also replace p3  by 0.01 to avoid a 0 decay.

I tested both with portmidi and with CsoundQT's own MIDI handler

```
UnifiedCSD:  /private/var/folders/b7/jgzdh5jj18n92s3vlckfkbmr0000gq/T/csound-tmpiENUztZz.csd
rtaudio: coreaaudio-AuHAL module enabled
rtmidi: PortMIDI module enabled
instr Simple uses instrument number 1
instr MidiNote uses instrument number 2
instr SeqScheduler uses instrument number 3
Elapsed time at end of orchestra compile: real: 0.002s, CPU: 0.002s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.002s, CPU: 0.002s
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
sr = 48000.0, kr = 750.000, ksmps = 64
0dBFS level = 1.0, A4 tuning = 440.0
WARNING: Seeding from current time 2790843869

0: IAC Driver Bus 1 (portmidi)
PortMIDI: Activated input device 0: 'IAC Driver Bus 1' (CoreMIDI)
0: IAC Driver Bus 1 (portmidi)
1: DLSMusicDevice (portmidi)
PortMIDI: selected output device 0: 'IAC Driver Bus 1' (CoreMIDI)
orch now loaded
audio buffered in 128 sample-frame blocks
AuHAL Module: found 7 output device(s):
1: USB Audio CODEC  (2 channels)
2: BlackHole 2ch (2 channels)
3: MacBook Pro Speakers (2 channels)
4: Microsoft Teams Audio (2 channels)
5: ZoomAudioDevice (2 channels)
6: Multi-Output Device (2 channels)
7: Aggregate Device (4 channels)
selected output device: USB Audio CODEC 
***** AuHAL module: output device open with 128 buffer frames
writing 256 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr SeqScheduler:
SeqScheduler
  rtevent:	   T  0.001 TT  0.001 M:  0.00000  0.00000
new alloc for instr MidiNote:
instr 2:  idur = 0.250
  rtevent:	   T  0.005 TT  0.005 M:  0.00000  0.00000
new MIDI alloc for instr Simple:
  midiKey:         pfield:   4  value:  70
  rtevent:	   T  0.253 TT  0.253 M:  0.30000  0.30000
  rtevent:	   T  1.003 TT  1.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  1.005 TT  1.005 M:  0.00000  0.00000
  midiKey:         pfield:   4  value:  68
  rtevent:	   T  1.253 TT  1.253 M:  0.30000  0.30000
  rtevent:	   T  2.003 TT  2.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  2.005 TT  2.005 M:  0.00000  0.00000
  midiKey:         pfield:   4  value:  62
  rtevent:	   T  2.253 TT  2.253 M:  0.30000  0.30000
  rtevent:	   T  3.003 TT  3.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  3.005 TT  3.005 M:  0.00000  0.00000
  midiKey:         pfield:   4  value:  68
  rtevent:	   T  3.253 TT  3.253 M:  0.30000  0.30000
  rtevent:	   T  4.003 TT  4.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  4.005 TT  4.005 M:  0.00000  0.00000
  midiKey:         pfield:   4  value:  67
  rtevent:	   T  4.253 TT  4.253 M:  0.30000  0.30000
  rtevent:	   T  5.003 TT  5.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  5.005 TT  5.005 M:  0.00000  0.00000
  midiKey:         pfield:   4  value:  65
  rtevent:	   T  5.253 TT  5.253 M:  0.30000  0.30000
  rtevent:	   T  6.003 TT  6.003 M:  0.00000  0.00000
instr 2:  idur = 0.250
  rtevent:	   T  6.005 TT  6.005 M:  0.00000  0.00000
  midiKey:         pfield:   4  value:  70
  rtevent:	   T  6.253 TT  6.253 M:  0.30000  0.30000
inactive allocs returned to freespace
end of score.		   overall amps:  0.30000  0.30000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 6.792s, CPU: 7.002s
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
AuHAL module: device closed
2529 256 sample blks of 64-bit floats written to dac
```

**Comment by boonier** [comment] 2024-01-09 15:07
Hi, thanks for checking. Were all tests from CsoundQT? Or are some of the results running from Terminal?

I can confirm both cases working as expected in CsoundQT - using portmidi (Csound MIDI module checked) or Internal  (Csound MIDI module un-checked).

But when I use the "Run in Terminal" option, I get the same result above that I've been experiencing. So something seems to be broken when running directly in Terminal (for me)

**Comment by vlazzarini** [comment] 2024-01-09 15:48
yes, running from the terminal in CsoundQT and also from the terminal outside CsoundQT. 

```
victor@firebird debug % /usr/local/bin/csound notedur_test.csd 
UnifiedCSD:  notedur_test.csd
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
instr Simple uses instrument number 1
instr MidiNote uses instrument number 2
instr SeqScheduler uses instrument number 3
Elapsed time at end of orchestra compile: real: 0.003s, CPU: 0.003s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.003s, CPU: 0.003s
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
```

**Comment by boonier** [comment] 2024-01-09 22:24
Thank again for checking. This topic issue is getting quite long and cyclical!

OK not really sure what else to do here, other than use a front-end, which is no biggie I guess. 

Btw I found this on the csound-users archives, it sounds pretty similar https://listserv.heanet.ie/cgi-bin/wa?A2=ind2208&L=CSOUND&P=78329

**Comment by vlazzarini** [comment] 2024-01-09 22:39
It might not have been working then, but it is now. 
I find it strange that it works on CsoundQT but not on the terminal, it's the same code, the same portmidi library. Would it be a permissions thing?

**Comment by gogins** [comment] 2024-01-09 23:06
Are there two installations of Csound on the computer, one from the user,
and one from the Qt installer?

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by boonier** [comment] 2024-01-10 10:07
Here's what I have (CsoundQT left/Terminal right)

![image](https://github.com/csound/csound/assets/6206789/812caac1-507f-449e-90f5-74e5a21bd5d2)

Also a system wide search came up with this:

```
MD5 (/usr/local/bin/csound) = fe1910d979db561643e4fab13b5f413a
MD5 (/System/Volumes/Data/usr/local/bin/csound) = fe1910d979db561643e4fab13b5f413a
MD5 (/System/Volumes/Data/Users/boonier/.cargo/registry/index/github.com-1ecc6299db9ec823/.cache/cs/ou/csound) = ceff9e870ae3001d570aa0699957adff
MD5 (/System/Volumes/Data/opt/homebrew/Cellar/csound/6.18.0/bin/csound) = a2fb6d99ba17d3cb7e680062e512b746
MD5 (/System/Volumes/Data/opt/homebrew/Cellar/csound/HEAD-9500783_5/bin/csound) = 20992620ceaf2be9cd22a87e99d6c084
MD5 (/Users/boonier/.cargo/registry/index/github.com-1ecc6299db9ec823/.cache/cs/ou/csound) = ceff9e870ae3001d570aa0699957adff
MD5 (/opt/homebrew/Cellar/csound/6.18.0/bin/csound) = a2fb6d99ba17d3cb7e680062e512b746
MD5 (/opt/homebrew/Cellar/csound/HEAD-9500783_5/bin/csound) = 20992620ceaf2be9cd22a87e99d6c084
```
I can't see any unusual standouts?

**Comment by vlazzarini** [comment] 2024-01-10 13:01
The only odd thing seems to be that Homebrew installation. Maybe that's messing things up.

Check that /usr/local/bin/csound is a file not a link and its dependencies with otool -L

Also check that your opcode directory is in the framework not elsewhere (in /Library/Frameworks)

Also check to see you don't have multiple versions of portmidi.dylib installed.

**Comment by boonier** [comment] 2024-01-10 17:01
I uninstalled/removed the homebrew version.

Should I have two architecture versions here?
```
boonier:~/ $ otool -L /usr/local/bin/csound                                                                                            [16:11:36]
/usr/local/bin/csound (architecture x86_64):
	@rpath/CsoundLib64.framework/Versions/6.0/CsoundLib64 (compatibility version 6.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
/usr/local/bin/csound (architecture arm64):
	@rpath/CsoundLib64.framework/Versions/6.0/CsoundLib64 (compatibility version 6.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

Nothing portmidi* came up in system search.

**Comment by vlazzarini** [comment] 2024-01-10 19:03
yep, that's the binary I build for release, universal.

**Comment by boonier** [comment] 2024-01-10 21:15
ah yes

**Comment by boonier** [comment] 2024-05-15 10:58
Realise this is closed now for some time. But after a hiatus I tried again last night. 

To test PortMidi from Terminal, I even made a tiny C app to generate a chord. Test worked fine. 

I uninstalled everything Csound* (both MacPorts and Homebrew had some Csound related entries), then re-installed. 

Still the same issues - I'm even more stumped!

So...Is it a possible permissions thing? - Csound running from the CLI not allowed to access the IAC bus. But why would one note on message be fired? Surely if it doesn't have sufficient permissions there wouldn't be any activity. Also I wouldn't know where to begin adjusting those permissions @gogins ?

**Comment by gogins** [comment] 2025-08-16 19:52
I am experiencing the same issues on my MacBook Pro 14 M1, macOS Sequoia 15.6, using Csound 6.18.1 from the official installer. I had in the past installed Csound from homebrew, but I removed that and installed the Csound .pkg.

The attached file demonstrates my issue.

<!-- Uploading "senskey_test.txt"... —>

**Comment by gogins** [comment] 2025-08-16 19:56
I didn’t see that my example uploaded, so here it is.
```
<CsoundSynthesizer>
<CsLicense>
Run this .csd after starting your MIDI controlled instrument. I have tested 
this with the standalone Pianoteq.

There is a problem in that all keystroke events are correctly scheduled and 
the MIDI file is correctly recorded for all keystrokes -- but only the first 
keystroke actually makes a sound.

When the Csound performance is ended with Ctrl-C, then the Midiview app 
finally shows events from all keystrokes being turned off. But the initial 
NOTE ON events are never shown (except for the very first).
</CsLicense>
<CsOptions>
-m167 -odac -d -Q2 -+rtmidi=PortMidi --midioutfile="senskey_test.mid"
</CsOptions>
<CsInstruments>
sr = 48000
ksmps = 128
nchnls = 2
0dbfs = 1
gk_channel init 1

instr 1
; The `sensekey` opcode does not return 1 for `k_pressed` as long as the kay 
; is actually held down, then return 0 when the key is released; rather, the 
; opcode 'emulates' this behavior by returning 0 immediately after returning 
; 1. Therefore, `sensekey` cannot provide a duration for key presses without 
; some more elaborate code that 'latches' the keyboard state. Here, we simply 
; send a short fixed duration that represents a struck bell.
k_onset init 0
k_duration init .01
k_velocity init 80
k_key sensekey 
if k_key > 0 then
schedulek 2, k_onset, k_duration, k_key
endif
endin

instr 2
i_channel = 1
i_key = p4
i_velocity init 80
i_duration init .01
noteondur i_channel, i_key, i_velocity, i_duration
prints "MIDI note: channel %9.4f key %9.4f velocity %9.4f duration %9.4f\n", i_channel, i_key, i_velocity, i_duration
endin

</CsInstruments>
<CsScore>
f 0 2000
i 1 0 2000
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment] 2025-08-17 09:59
does it work without writing to a file?
If it does then the file writing function may be clearing the buffer.

**Comment by gogins** [comment] 2025-08-17 10:27
Neither my example nor Hunkins' work without writing to a file.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2025-08-17 10:47
@gogins I tested your code here - on an Intel Mac (15.4.1) (my M1 is out of commission atm), csound 6.18.1, and I have it working with Reaper:

- Using IAC MIDI
- Writing to file

I was always getting MIDI notes on Reaper and could record them. The notes were very  short but that was because you had them set at 10ms duration and the Reaper Reasynth would not make any sound with these.
I increased that to 1s to get a better view and got sound from the recorded track - the MIDI notes were coming in and being recorded and if I select 'monitor input' for the track I would get sound from the synth.

I checked with a MIDI monitor just to be sure This is what I got:

```
11:41:33.117	From IAC Driver Bus 1	Note On	1	G2	80
11:41:34.046	From IAC Driver Bus 1	Note Off	1	G2	80
11:41:37.389	From IAC Driver Bus 1	Note On	1	C♯8	80
11:41:38.318	From IAC Driver Bus 1	Note Off	1	C♯8	80
11:41:38.597	From IAC Driver Bus 1	Note On	1	C♯8	80
11:41:39.526	From IAC Driver Bus 1	Note Off	1	C♯8	80
11:41:40.454	From IAC Driver Bus 1	Note On	1	C♯8	80
11:41:41.383	From IAC Driver Bus 1	Note Off	1	C♯8	80
```

**Comment by gogins** [comment] 2025-08-17 10:56
I increased the duration in my example to 1 second and I got exactly the
same results as before. The first keystroke plays, all keystrokes are saved
in the MIDI file, but only the first keystroke shows up in the MIDI monitor
until the performance is ended with Control-C.

Perhaps on my computer, only the first MIDI on event is actually sent to
the synth. That first note says red on the Pianoteq keyboard until the
performance is ended, and no other notes show up.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment] 2025-08-17 12:01
I'm afraid I can't reproduce it here, as in previous cases. I also tested with csound 7 and I am getting a similar result. To test on the M1, I will have to wait until it's back working, but I suspect I will get the same result as per previous posts. 

The only things I changed from your code was the device number (to 0) and note duration. You can see from the MIDI monitor printout that the notes are being sent.

**Comment by gogins** [comment] 2025-08-17 15:01
Thanks for looking at this. Possibly, since I had built Csound and also
other binaries that depend on PortAudio and PortMidi, the shared libraries
got crossed up. Can I install Csound 7 in a sandbox of some sort to test
with that?

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
