### ISSUE TITLE
T0 on Windows with long argument hangs - Linux does not

### ISSUE THREAD

**Issue by prentrodgers** [csound/csound#567] opened 2015-12-08 21:00 UTC
Long t0 arguments cause hangs in CSound for Windows 7. I have an example that hangs unless I shorten the number of arguments below 22 on Windows, but executes flawlessly on Ubuntu Linux. 
The attached CSD file, called drunka.csd.txt, reads in a sound file and applies volume levels to the file. The input file is called drunk.wav, found in the zip file drunk.zip.

My goal is to be able to change the tempo every measure, which results in manu time arguments to the t0 function. In the past I have been able to use up to 100, but would prefer to be able to have this virtually without limit, with a minimum of 500 different tempi. 

I have uninstalled Csound and reinstalled it, to no avail. 

My System characteristics:
Microsoft Windows 7 Professional    6.1.7601   Service Pack 1
Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
4096MB RAM
Csound version 6.07 beta (double samples) Nov 16 2015
libsndfile-1.0.25

[drunka.csd.txt](https://github.com/csound/csound/files/56021/drunka.csd.txt)

[Drunk.zip](https://github.com/csound/csound/files/56023/Drunk.zip)

**Comment by jpffitch** [comment] 2015-12-08 21:10
Humm,  If it works on Linux then it ought to run on Windows.  Code is not specific as far as I can remember.  Changed 13 Oct last in twarp.c if a windows source is checked

**Comment by kunstmusik** [comment] 2016-01-11 15:31
I'm getting odd hangs once in a while, but not consistently. I am getting this though every time:

WARNING: Division by zero

Win 10, latest from develop branch (64-bit build)

**Comment by jpffitch** [comment] 2016-01-16 20:34
What input are you using Steven?  That message only comes from divkk and divak so wat dividing are you doing?  In the example code there is only 1/p3 and p3 is not zero.  I do not understand

**Comment by gogins** [comment] 2016-05-13 19:58
Running in the WIndows 7 console with develop head built with MSYS2/ming64: No error, but an empty soundfile:

$ csound c:/Users/restore/Downloads/rodgers/drunka.csd
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.07 (double samples) May 11 2016
libsndfile-1.0.26-exp
UnifiedCSD:  c:/Users/restore/Downloads/rodgers/drunka.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
sorting score ...
        ... done
--Csound version 6.07 (double samples) May 11 2016
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 4096 sample-frame blocks
writing 16384-byte blks of shorts to Drunka.wav (WAV)
SECTION 1:
ftable 1:

 PostScript graphs written to file Drunka.eps

ftable 1:       65536 points, scalemax 1.000
''''''''''''''''''''-------'''''--'''''-'''''--------------'''''''''''-_________
new alloc for instr 99:
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.              overall amps:  0.00000  0.00000
           overall samples out of range:        0        0
0 errors in performance
8192 16384 sample blks of shorts written to Drunka.wav (WAV)
csound->FileOpen2("D:\msys64\home\restore\.csound6rc") failed: No such file or directory.
csound->FileOpen2(".csound6rc") failed: No such file or directory.

Running in gdb is different with a SIGTRAP caused by heap overwritte:

$ gdb --args csound c:/Users/restore/Downloads/rodgers/drunka.csd
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from csound...done.
(gdb) run
Starting program: D:\msys64\home\restore\csound\mingw64\csound-mingw64\csound.exe c:/Users/restore/Downloads/rodgers/drunka.csd
[New Thread 8704.0x1efc]
warning: HEAP[csound.exe]:
warning: HEAP: Free Heap block 0000000003E5DE30 modified at 0000000003E5E0B8 after it was freed

Program received signal SIGTRAP, Trace/breakpoint trap.
0x000007f966419e03 in ntdll!WinSqmCheckEscalationSetDWORD ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) cont
Continuing.
warning: HEAP[csound.exe]:
warning: HEAP: Free Heap block 0000000003E418E0 modified at 0000000003E41C08 after it was freed

Program received signal SIGTRAP, Trace/breakpoint trap.
0x000007f966419e03 in ntdll!WinSqmCheckEscalationSetDWORD ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb)

Suggests an aliased pointer is not updated.

:

**Comment by gogins** [comment] 2016-05-13 20:10
With Dr. Memory there are obvious errors:

Dr. Memory version 1.10.0 build 2 built on Mar  7 2016 23:05:08
Dr. Memory results for pid 6952: "csound.exe"
Application cmdline: "csound c:/Users/restore/Downloads/rodgers/drunka.csd"
Recorded 117 suppression(s) from default C:\Program Files (x86)\Dr. Memory\bin64\suppress-default.txt

Error #1: UNADDRESSABLE ACCESS of freed memory: reading 0x0000000005b6c6c0-0x0000000005b6c6c8 8 byte(s)
# 0 csound64.dll!realtset           [D:/msys64/home/restore/csound/Engine/twarp.c:152]
# 1 csound64.dll!twarp              [D:/msys64/home/restore/csound/Engine/twarp.c:53]
# 2 csound64.dll!scsortstr          [D:/msys64/home/restore/csound/Engine/scsort.c:55]
# 3 csound64.dll!csoundYield        [D:/msys64/home/restore/csound/Top/csound.c:2943]
# 4 csound64.dll!csoundCompileArgs  [D:/msys64/home/restore/csound/Top/main.c:302]
# 5 csound64.dll!csoundCompile      [D:/msys64/home/restore/csound/Top/main.c:513]
# 6 main                            [D:/msys64/home/restore/csound/frontends/csound/csound_main.c:316]
Note: @0:00:01.920 in thread 6992
Note: 0x0000000005b6c6c0-0x0000000005b6c6c8 overlaps memory 0x0000000005b6c450-0x0000000005b6c6e0 that was freed here:
Note: # 0 replace_realloc               [d:\drmemory_package\common\alloc_replace.c:2668]
Note: # 1 csound64.dll!__strtod         [C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/gdtoa/strtodnrp.c:48]
Note: # 2 csound64.dll!stof             [D:/msys64/home/restore/csound/Engine/sread.c:1876]
Note: # 3 csound64.dll!mrealloc         [D:/msys64/home/restore/csound/Engine/memalloc.c:207]
Note: # 4 csound64.dll!realtset         [D:/msys64/home/restore/csound/Engine/twarp.c:136]
Note: # 5 csound64.dll!twarp            [D:/msys64/home/restore/csound/Engine/twarp.c:53]
Note: instruction: subsd  (%rdi) %xmm1 -> %xmm1

Error #2: UNADDRESSABLE ACCESS of freed memory: reading 0x0000000005b6c6d0-0x0000000005b6c6d8 8 byte(s)
# 0 csound64.dll!realtset           [D:/msys64/home/restore/csound/Engine/twarp.c:160]
# 1 csound64.dll!twarp              [D:/msys64/home/restore/csound/Engine/twarp.c:53]
# 2 csound64.dll!scsortstr          [D:/msys64/home/restore/csound/Engine/scsort.c:55]
# 3 csound64.dll!csoundYield        [D:/msys64/home/restore/csound/Top/csound.c:2943]
# 4 csound64.dll!csoundCompileArgs  [D:/msys64/home/restore/csound/Top/main.c:302]
# 5 csound64.dll!csoundCompile      [D:/msys64/home/restore/csound/Top/main.c:513]
# 6 main                            [D:/msys64/home/restore/csound/frontends/csound/csound_main.c:316]
Note: @0:00:01.936 in thread 6992
Note: 0x0000000005b6c6d0-0x0000000005b6c6d8 overlaps memory 0x0000000005b6c450-0x0000000005b6c6e0 that was freed here:
Note: # 0 replace_realloc               [d:\drmemory_package\common\alloc_replace.c:2668]
Note: # 1 csound64.dll!__strtod         [C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/gdtoa/strtodnrp.c:48]
Note: # 2 csound64.dll!stof             [D:/msys64/home/restore/csound/Engine/sread.c:1876]
Note: # 3 csound64.dll!mrealloc         [D:/msys64/home/restore/csound/Engine/memalloc.c:207]
Note: # 4 csound64.dll!realtset         [D:/msys64/home/restore/csound/Engine/twarp.c:136]
Note: # 5 csound64.dll!twarp            [D:/msys64/home/restore/csound/Engine/twarp.c:53]
Note: instruction: movsd  0x10(%rdi) -> %xmm3

Error #3: UNADDRESSABLE ACCESS of freed memory: reading 0x0000000005b6c6d8-0x0000000005b6c6e0 8 byte(s)
# 0 csound64.dll!realtset           [D:/msys64/home/restore/csound/Engine/twarp.c:161]
# 1 csound64.dll!twarp              [D:/msys64/home/restore/csound/Engine/twarp.c:53]
# 2 csound64.dll!scsortstr          [D:/msys64/home/restore/csound/Engine/scsort.c:55]
# 3 csound64.dll!csoundYield        [D:/msys64/home/restore/csound/Top/csound.c:2943]
# 4 csound64.dll!csoundCompileArgs  [D:/msys64/home/restore/csound/Top/main.c:302]
# 5 csound64.dll!csoundCompile      [D:/msys64/home/restore/csound/Top/main.c:513]
# 6 main                            [D:/msys64/home/restore/csound/frontends/csound/csound_main.c:316]
Note: @0:00:01.937 in thread 6992
Note: 0x0000000005b6c6d8-0x0000000005b6c6e0 overlaps memory 0x0000000005b6c450-0x0000000005b6c6e0 that was freed here:
Note: # 0 replace_realloc               [d:\drmemory_package\common\alloc_replace.c:2668]
Note: # 1 csound64.dll!__strtod         [C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/gdtoa/strtodnrp.c:48]
Note: # 2 csound64.dll!stof             [D:/msys64/home/restore/csound/Engine/sread.c:1876]
Note: # 3 csound64.dll!mrealloc         [D:/msys64/home/restore/csound/Engine/memalloc.c:207]
Note: # 4 csound64.dll!realtset         [D:/msys64/home/restore/csound/Engine/twarp.c:136]
Note: # 5 csound64.dll!twarp            [D:/msys64/home/restore/csound/Engine/twarp.c:53]
Note: instruction: addsd  0x18(%rdi) %xmm2 -> %xmm2

And more...

**Comment by jpffitch** [comment] 2016-05-13 20:26
I see similar in valgrind.  Removed the Windows label as this is clearly my fault with errors in score sort at least

**Comment by gogins** [comment] 2016-05-13 21:15
The problem appears to be reading memory in realtset that has been reallocated, that is, reading from a now invalid pointer.

**Comment by jpffitch** [comment] 2016-05-13 21:34
Thanks; I will read more careflly now as I see valgrind rrors

**Comment by jpffitch** [comment] 2016-05-14 14:08
Found a place where the relocation was wrong; fixed in git I think

**Comment by gogins** [comment] 2016-05-14 15:08
Dr. Memory clean on Windows x64 now. Rodgers' piece runs without error and produces a soundfile with content, although there is a loud tail in the file.

Note: there were also bad characters in the Windows csd that I had to clean up to get it to run.

**Closed by gogins** 2016-05-14 15:08 UTC
Labels: bug

**Comment by prentrodgers** [comment] 2016-05-14 15:11
Thank you for following up on this problem. I was really frustrated with
not being able to change tempos as often as I wanted. I appreciate your
attention to my issue.

Prent Rodgers
On Sat, May 14, 2016 at 8:09 AM Michael Gogins <notifications@github.com>
wrote:

> Dr. Memory clean on Windows x64 now. Rodgers' piece runs without error and
> produces a soundfile with content, although there is a loud tail in the
> file.
>
> Note: there were also bad characters in the Windows csd that I had to
> clean up to get it to run.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/csound/csound/issues/567#issuecomment-219225360>
>
-- 
Prent Rodgers
