### ISSUE TITLE
Array index out of range

### ISSUE THREAD

**Issue by Ebmtranceboy** [csound/csound#554] opened 2015-11-07 04:26 UTC
Some combinations of array lengths, p2 and p3 raise PERF ERRORs due to array indices out of range.
See for example the following program where array length, initially 338 for a first note, becomes 319 for the next consecutive note:

<pre>
&lt;CsoundSynthesizer>
&lt;CsOptions>
-odac
&lt;/CsOptions>

&lt;CsInstruments>
sr = 44100
ksmps = 10
nchnls = 1
0dbfs = 1

	instr 1
	
icps 	= 	cpspch(p4)
ain 	poscil 	1,icps
  
ilen 	= 	int(sr/icps)+1
	print 	ilen

kbuf[] 	init 	ilen
kidx 	init 	0
kval 	init 	0

aout 	= 	0
ksmp 	= 	0

while ksmp &lt; ksmps do
    kin vaget ksmp, ain
    kbuf[kidx % ilen] = kval + kin
    
    kval = kbuf[(kidx + 6) % ilen]
    vaset kval, ksmp, aout

    kidx += 1
    kidx = kidx % ilen
    ksmp += 1
    od

	out aout/30

	endin

&lt;/CsInstruments>

&lt;CsScore>
i1 0 2 7.00
i1 2 2 7.01
e
&lt;/CsScore>
&lt;/CsoundSynthesizer>
</pre>

**Comment by vlazzarini** [comment] 2015-11-07 09:13
the array length has changed because p4 has changed. Do you mean to say that internally, the array length hasn't changed and then there is a problem?

**Comment by vlazzarini** [comment] 2015-11-07 16:33
Ok, I had a look at this. I think this is to do with initialisation of synthetic k-rate vars.
If I replace the line

kval = kbuf[(kidx + 6) % ilen]

with

kn = (kidx + 6) % ilen
kval = kbuf[kn]

and initialise kn to 0 at the top, the warning goes away.

kn init 0

If I remove the init line, the warning is back. So the synthetic var is not being initialised to 0. Not sure
whether it should or not (what is the expected behaviour?).

**Comment by kunstmusik** [comment] 2015-11-07 16:39
Interesting, I wonder if array_get is working at init-time, and the synthetic var's value is leftover from the previous instrument instance that is getting reused.

**Comment by Ebmtranceboy** [comment] 2015-11-07 16:40
Ok thank you Victor. What troubles me is that the warning (which is a PERF ERROR on my ubuntu system) refers to an index which can't logically be reached thanks to the modulo operator.

**Comment by vlazzarini** [comment] 2015-11-07 16:53
Here it is a warning, maybe because the version I am using might be different to yours.
I think that's probably because the synthetic variable contains garbage, since the expression
is only computed at perf-time.

**Comment by Ebmtranceboy** [comment] 2015-11-07 17:08
oh OK, so, knowing that, I should probably add another auxiliary variable for the kdix%ilen expression and initialise it to 0 too at the top for precaution. 
This default behaviour seems OK to me (now).
Thanks again.
Tell me when you (and Steven) want me to close the issue.

**Comment by vlazzarini** [comment] 2015-11-07 17:10
I'd leave it open until we can figure out it's not a bug.

**Comment by jpffitch** [comment] 2015-11-09 11:40
I think this is a bug; tere should be no ativity at init time for temporary variables.  I think this is a result of te array semantics

**Comment by jpffitch** [comment] 2015-11-09 15:13
I see an asymmetry between array get and array set

birtwistle:~/Sourceforge/csound/New/csound6>        Search ##array_set.k0
./Opcodes/arrays.c:    { "##array_set.k0", sizeof(ARRAY_SET), 0, 2, "", "k[]kz",
birtwistle:~/Sourceforge/csound/New/csound6> Search ##array_get.k0
./Opcodes/arrays.c:    { "##array_get.k0", sizeof(ARRAY_GET), 0, 3, "k", "k[]z",

so get runs at i anf k rate, but set only at k
One of these is wrong!

**Comment by kunstmusik** [comment] 2015-11-09 15:28
This looks to be a result of something I implemented for Issue #254.  This is all very tricky as sometimes users will want to access array's at k-time but give a constant or i-rate sig as an index.

**Comment by jpffitch** [comment] 2015-11-09 15:43
I could test my fix against your  earlier issue if I had a test program

**Comment by kunstmusik** [comment] 2015-11-09 20:01
@jpffitch There's a test CSD posted in the Nabble mailing list archive here:

http://csound.1045644.n5.nabble.com/csound6-getting-i-value-of-a-kArray-member-td5729623.html

**Comment by jpffitch** [comment] 2015-11-09 20:19
OK; my patch breaks the older issue.

I still think it odd that kk=0 does not run at i-time but kkk[0]=0 does

**Comment by jpffitch** [comment] 2016-10-10 11:19
Believed fixed in 6.08 with new array rate computation

**Closed by jpffitch** 2016-10-10 11:19 UTC
Labels: bug
