### ISSUE TITLE
CsoundQt HELP!!

### ISSUE THREAD

**Issue by superikonta** [csound/csound#688] opened 2016-08-08 03:11 UTC
I just started. Please help. I've tried to run a very short file  on CsoundQt
with windows 10. I play 2 notes after each other and then together. The
together part is just a strange buss. I get it on audio and in the wav file. What am I doing wrong? Thanks for any help.

```
<CsoundSynthesizer>
<CsOptions>

</CsOptions>

<CsInstruments>

sr = 44100
ksmps = 100
nchnls = 1
0dbfs = 1

giSine ftgen 1, 0, 16384, 10, 1

instr 1
aout oscil 0.6, p5, giSine
out aout
endin


</CsInstruments>

<CsScore>

;Instr  Sta     Dur     Amp     Freq
i1      0       1       65      400
i1      1       1       .       600
i1      2       1       .       400
i1      2       1       .       600
i1      3       1       .       400
i1      4       1       .       560
i1      5       1       .       400
i1      5       1       .       560
i1      6       1       .       400
i1      7       1       .       488.9
i1      8       1       .       400
i1      8       1       .       488.9
i1      9       1       .       400
i1      10      1       .       472.7
i1      11      1       .       400
i1      11      1       .       472.7

</CsScore>
</CsoundSynthesizer>
```

**Comment by kunstmusik** [comment] 2016-08-08 03:16
This is not a bug in Csound so this message should probably go to the Csound user's mailing list, Stackoverflow, or other forum.  

That said, the problem is that you have a fixed amplitude of 0.65 in your oscil line.  When two instrument instances play, they sum to 1.3, which is greater than 1.0 which you have set for 0dbfs.  

Since this is not a bug, I will close this issue now.  For further questions about Csound usage, please try the mailing list or other forum.

**Closed by kunstmusik** 2016-08-08 03:16 UTC
