### ISSUE TITLE
Csound for Android in background crash/killed

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#865] opened 2017-10-26 11:37 UTC
The Csound for Android app stops if left running in the background (i.e., if the GUI isn't visible).
Sorry I can't post specific code to demonstrate this. Nor can I supply a log file (the app doesn't save them).
However the test I did to confirm the behaviour was by Live-coding using Emacs to send UDP packets to the running app. When the Csound app is in the background (thus not visible), Csound will eventually stop -usually after 10 - 20 minutes. It seems to depend on how hard Csound is working. The GUI app is still alive, however sound stops, and the Message console is black. The Stop button does nothing, and the app must be manually closed. 
Of note however, I tested live-coding from a different machine, sending code via a local network to the Android device. This allowed me to keep the Csound app visible (not in the background). In this scenario Csound remained running. I was unable to crash/kill/stop Csound.
I would speculate that perhaps Android has some memory/cpu app-killing policy for apps running in the background. I don't know Android well enough to know if there's a way around this.

**Comment by hlolli** [comment] 2017-10-28 11:09
Out of curiousity, could you share your emacs udp functions. I'm in the process of changeing to udp for my csound repl in my csound emacs package csound-mode. Could be a potential timesaver :)

**Comment by ErrorThink** [comment] 2017-10-28 16:18
The key lines to get things going:
(setq *CsoundProcess* (make-network-process :name "Csound" :type 'datagram :buffer "*Csound*" :family 'ipv4 :host "127.0.0.1" :service "8099" :sentinel 'listen-sentinel :filter 'listen-filter))))
then...
(process-send-string *CsoundProcess* (string-to-unibyte "csound code here"))
I'm happy to share files, but I'm not sure how much time it would save you... it's part of a larger library. It's also a bit messy and undocumented. That being said... I tried it in your csound-mode and it seemed to work OK. If you feel like a challenge I can email you direct or via the list.  Just let me know. Thorin.

**Comment by kunstmusik** [comment] 2018-01-15 19:02
@ErrorThink Is this still an issue with the latest Csound Android?

**Comment by gogins** [comment] 2018-01-15 21:34
The Android operating system will kill any background (not visible, in
other words) activity if some other activity that becomes visible needs the
first activity's resources (memory, CPU cycles, etc.). The activity
lifecycle is here: https://developer.android.com/reference/android/
app/Activity.html#ActivityLifecycle. So this behavior is by design of
Android.

I think that in the Csound app, we can create a Service that will keep
Android from killing Csound when it's not visible. This could be
configurable ("Run as background service").

I will assign this issue to myself and see if I can do that.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment] 2018-01-15 21:34
By design, Android kills Activities that are pushed to the background when the user starts new Activities.

I will try to add the ability for the Csound for Android app to start a Service which should prevent this from happening.

https://developer.android.com/reference/android/app/Service.html

**Comment by gogins** [comment] 2018-05-24 16:36
The whole problem is that Services don't have user interfaces (except for notifications), but Csound needs a user interface. Is it possible to transfer the activity to a service?

**Comment by gogins** [comment] 2018-05-24 17:03
I'm going to create an app-specific foreground service and see if that does the job.

**Comment by gogins** [comment] 2018-05-24 19:36
I create a dummy foreground service that just sleeps. This keeps Csound running even when the GUI is not visible. Actually closing the GUI stops the service also and Csound exits properly. The Csound icon shows in the notification bar as long as Csound is running.

Please note: this is fixed not in this repository, but in the csound-extended repository.

**Closed by gogins** 2018-05-24 19:36 UTC
Labels: android, enhancement
