### ISSUE TITLE
csound api java wrapper fails on OSX

### ISSUE THREAD

**Issue by peimankhosravi** [csound/csound#497] opened 2015-07-01 10:23 UTC
On OS X  10.9.5 I'm unable to load csound in java. This is the error I get after running a simple code:

++++++++++++++JAVA CODE+++++++++++++
import csnd6.*;
public class csoundtest {
    public static void main(String[] args) {
		Csound c = new Csound();
	} 
}
+++++++++++++END OF JAVA CODE+++++++++

++++++++++++ERROR+++++++++++++
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011b9c3875, pid=2747, tid=3335
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libawt_lwawt.dylib+0x44875]  JNI_OnLoad+0x91
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/peimankhosravi/hs_err_pid2747.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/bin/sh: line 1:  2747 Abort trap: 6           java "csoundtest"
[Finished in 1.6s with exit code 134]
++++++++++++++++++END OF ERROR+++++++++++++++++++++++++++

NOTE: the same code seems to work in 32-bit MaxMSP. But not 64-bit...

**Comment by peimankhosravi** [comment] 2015-07-02 08:07
Note: that when I install csound 6.03.2 the problem disapears. 
Note: I can confirm the same problem in Yosemite.

**Comment by vlazzarini** [comment] 2015-07-02 08:26
This is not what is happening in my system. I got your code, compiled with 
```
$ javac csoundtest.java
```
and run

```
ligeti-3:debug victor$ java csoundtest
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.05 (double samples) Jun  2 2015
libsndfile-1.0.25
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.256s, CPU: 0.001s
```
To make sure it's 64bit: 

```
ligeti-3:debug victor$ java -D64 csoundtest
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.05 (double samples) Jun  2 2015
libsndfile-1.0.25
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.254s, CPU: 0.002s
```

So I wonder if it is to do with your installation of java

**Comment by peimankhosravi** [comment] 2015-07-02 08:35
Thanks Victor,

I've tried this on two machines. One with a fresh OS upgrade (Yosemite).
And the same thing is happening there.

Could you please check what version of java you have on your machine? And
are you definitely running csound that was installed by the official
installer? Could you for instance delete all traces of csound (including
the files in /Library/Java/Extensions) and reinstall using the latest
installer downloaded from sourceforge?

Many Thanks
P







*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by vlazzarini** [comment] 2015-07-02 08:37
Note that:

```
ligeti-3:debug victor$ otool -L /Library/Java/Extensions/lib_jcsound6.jnilib 
/Library/Java/Extensions/lib_jcsound6.jnilib:
	@rpath/libjawt.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
	CsoundLib64.framework/Versions/6.0/CsoundLib64 (compatibility version 6.0.0, current version 0.0.0)
	@loader_path/../../../../libs/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.25.0)
	libcsnd6.6.0.dylib (compatibility version 6.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 60.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

So the offending library libjawt.dylib is whatever it is provided by your system (uses @rpath)

**Comment by vlazzarini** [comment] 2015-07-02 08:45
and:

```
ls -l /System/Library/Frameworks/JavaVM.framework/Libraries/libjawt.dylib 
-rwxr-xr-x  1 root  wheel  49104 29 May  2014 /System/Library/Frameworks/JavaVM.framework/Libraries/libjawt.dylib
```

**Comment by peimankhosravi** [comment] 2015-07-02 08:47
I've looked for that library and it lives in the java installed
directories. I've just reinstalled java from the latest installer on
http://www.oracle.com and the same error.

Also, I've tried csound 6.03.2, which works.

This is what I get:

Peimans-MacBook-Air:~ peimankhosravi$ otool -L
/Library/Java/Extensions/lib_jcsound6.jnilib
/Library/Java/Extensions/lib_jcsound6.jnilib:
    @rpath/libjawt.dylib (compatibility version 1.0.0, current version
1.0.0)
    @rpath/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
    CsoundLib64.framework/Versions/6.0/CsoundLib64 (compatibility version
6.0.0, current version 0.0.0)
    @loader_path/../../../../libs/libsndfile.1.dylib (compatibility version
2.0.0, current version 2.25.0)
    libcsnd6.6.0.dylib (compatibility version 6.0.0, current version 0.0.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current
version 60.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current
version 1197.1.1)







*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by peimankhosravi** [comment] 2015-07-02 08:47
Peimans-MacBook-Air:~ peimankhosravi$ ls -l
/System/Library/Frameworks/JavaVM.framework/Libraries/libjawt.dylib
-rwxr-xr-x  1 root  wheel  49104  9 Jan  2014
/System/Library/Frameworks/JavaVM.framework/Libraries/libjawt.dylib




*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by vlazzarini** [comment] 2015-07-02 08:52
The dates for libjawt.dylib are different, which might point to a different version. Also in your installed
6.03, the installed name for CsoundLib64 is not a full path (I guess it uses whichever framework it finds first, I don't think this matters).

I don't know enough about java installations to tell what the problem is. All I can say is that it works on my system, which makes it difficult for me to find a solution as I can't reproduce the installation problem.

**Comment by vlazzarini** [comment] 2015-07-02 09:19
Java version here:

```
ligeti-3:debug victor$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```

**Comment by peimankhosravi** [comment] 2015-07-02 16:33
Thanks Victor,

I don't think the verion difference in libjawt.dylib is an issue. I'm
running 'build 1.8.0_45-b14' which I only installed a couple of days ago in
the hope that it might fix this issue. Before that I was using 1.7.0_45.

Maybe Steven has an idea.




*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by peimankhosravi** [comment] 2015-07-02 16:36
We're not running the same csound build. That's the difference in our
systems I think. I've got:

Csound version 6.05 (double samples) Jun  8 2015
libsndfile-1.0.25





*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by vlazzarini** [comment] 2015-07-02 16:59
yes, I am also running 6.05 from June 8

**Comment by peimankhosravi** [comment] 2015-07-02 17:38
Sorry I was looking at the terminal printout that you sent this morning:

ligeti-3:debug victor$ java csoundtest
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.05 (double samples) Jun  2 2015
libsndfile-1.0.25
end of score.          overall amps:      0.0
       overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.256s, CPU: 0.001s






*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by kunstmusik** [comment] 2015-07-02 17:42
I'm wondering if the problem isn't this:

    @loader_path/../../../../libs/libsndfile.1.dylib (compatibility version
2.0.0, current version 2.25.0)

It seems like too many ..'s no?  

Peimain, could you try this command:

install_name_tool -change @loader_path/../../../../libs/libsndfile.1.dylib @loader_path/../../libs/libsndfile.1.dylib /Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound.jnilib


I think the installer script was updated to modify the loader_path on opcode plugins, but they are not being updated in the interface libraries.

**Comment by vlazzarini** [comment] 2015-07-02 20:08
but it works here. I think the path is correct:

```
ligeti-3:Java victor$ cd /Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Java
ligeti-3:Java victor$ ls ../../../../libs/libsndfile.1.dylib 
../../../../libs/libsndfile.1.dylib
```

**Comment by kunstmusik** [comment] 2015-07-02 22:25
Ah yes, you're right of course.  I misread the paths when I was checking
and forgot that the top-level Resources folder was a symlink.

**Comment by vlazzarini** [comment] 2015-07-03 06:19
does it work for you, @kunstmusik?

**Comment by peimankhosravi** [comment] 2015-07-03 06:42
Hello, sorry for the delay.

If it still helps, this is what I get after running the command.

peimans-air:Java peimankhosravi$ install_name_tool -change
@loader_path/../../../../libs/libsndfile.1.dylib
@loader_path/../../libs/libsndfile.1.dylib
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't
open input file:
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib
for writing (Permission denied)
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't
lseek to offset: 4096 in file:
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib
for writing (Bad file descriptor)
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't
write new headers in file:
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib
(Bad file descriptor)
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't
lseek to offset: 290816 in file:
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib
for writing (Bad file descriptor)
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't
write new headers in file:
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib
(Bad file descriptor)
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't
close written on input file:
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib
(Bad file descriptor)
peimans-air:Java peimankhosravi$








*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by vlazzarini** [comment] 2015-07-03 07:00
don't worry about that, it is not relevant.

**Comment by peimankhosravi** [comment] 2015-07-03 07:21
Since Blue seems to be working, I wonder if it's not just the jar file
that's causing this...




*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by peimankhosravi** [comment] 2015-07-03 07:36
Just a note that after the installation there was an alias to
"/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib"
in "/Library/Java/Extensions/". But no "csnd6.jar" in
"/Library/Java/Extensions/". When I place "csnd6.jar" in "Java/Extensions/"
I get this error:

peimans-air:~ peimankhosravi$ javac ./csoundtest.java
peimans-air:~ peimankhosravi$ java csoundtest
_jcsound6 native code library failed to load.
java.lang.UnsatisfiedLinkError:
/Library/Java/Extensions/lib_jcsound6.jnilib:
dlopen(/Library/Java/Extensions/lib_jcsound6.jnilib, 1): no suitable image
found.  Did find:
    /Library/Java/Extensions/lib_jcsound6.jnilib: unknown file type, first
eight bytes: 0x62 0x6F 0x6F 0x6B 0x00 0x00 0x00 0x00
peimans-air:~ peimankhosravi$


Then I delete the alias and put an actual copy of "lib_jcsound6.jnilib" in
"Extensions". After that I get the reported error that you know already.

Mnay Thanks
Peiman




*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by kunstmusik** [comment] 2015-07-03 15:05
It's important that the jnilib in /Library/Java/Extensions be a symlink and
not an actual copy.  Otherwise, the @loader_path will be different and it
won't be able to link to its dependencies.

**Comment by vlazzarini** [comment] 2015-07-03 18:21
yes, you should not move things. Try adding the jar location to your classpath, without changing the installation

**Comment by peimankhosravi** [comment] 2015-07-04 07:48
Thanks,

Steven, could you please sent me a list of the things tat I need to do
after installing Csound in order to add the jar to the classpath?





*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by peimankhosravi** [comment] 2015-07-04 10:21
​Hi there,

So I've deleted lib_jcsound6.jnilib and csnd6.jar from /Library/Java and
made two symlinks in there to
/Library/Frameworks/CsoundLib64.framework/Resources/Java/csnd6.jar and
/Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib.

But the same error:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011c6b0875, pid=1580, tid=3335
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build
1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode
bsd-amd64 compressed oops)
# Problematic frame:
# C  [libawt_lwawt.dylib+0x44875]  JNI_OnLoad+0x91
#
# Failed to write core dump. Core dumps have been disabled. To enable core
dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/peimankhosravi/hs_err_pid1580.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6





*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by peimankhosravi** [comment] 2015-07-04 11:29
I just clear all traces of csound and reinstalled. And the same error I'm
afraid.




*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*

**Comment by vlazzarini** [comment] 2015-07-04 21:04
Ok, I think I am getting somewhere now. I found out I had a ~/Library/Java/Extensions with a JNI library there, which is probably what I was using. Once I got rid of it and copied the csnd6.jar to /Library/Java/Extensions, I got your problem.

Then I went to my build dir, where I had a newer JNI and run the program from there, with no problems. I then checked what libs it was depending on:
```
ligeti-3:debug victor$ otool -L lib_jcsound6.jnilib 
lib_jcsound6.jnilib:
	/System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM (compatibility version 1.0.0, current version 1.0.0)
	/Users/victor/src/csound6/debug/CsoundLib64.framework/Versions/6.0/CsoundLib64 (compatibility version 6.0.0, current version 0.0.0)
	/usr/local/lib/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.25.0)
	/Users/victor/src/csound6/debug/libcsnd6.6.0.dylib (compatibility version 6.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

So it was not linked to liblwawt.dylib at all! The installed one was. @kunstmusik  do you know why the installation ends up linking it to that library? It does not seem to need it. I think once we remove that, we'll be OK.

**Comment by kunstmusik** [comment] 2015-07-04 21:28
That's interesting, my own version reports:

```
Steven-Yis-MacBook-Pro-249:cs6 stevenyi$ otool -L ~/Library/Java/Extensions/lib_jcsound6.jnilib 
/Users/stevenyi/Library/Java/Extensions/lib_jcsound6.jnilib:
        @rpath/libjawt.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/lib/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.25.0)
        libcsnd6.6.0.dylib (compatibility version 6.0.0, current version 0.0.0)
        CsoundLib64.framework/Versions/6.0/CsoundLib64 (compatibility version 6.0.0, current version 0.0.0)
        /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

I checked our build and in interfaces/CMakeLists.txt, we have:

```
            set(swigjava_LIBS ${JNI_LIBRARIES} ${CSOUNDLIB} ${LIBSNDFILE_LIBRARY} libcsnd6)
```

On Linux, we don't use JNI_LIBRARIES at all.  I wonder if we need them?  (Maybe it's an issue on Windows?) 

Note, JNI_LIBRARIES is defined in the FindJNI.cmake module that comes with CMake.  In that file, it shows that it is just the combination of both JAVA_AWT_LIBRARY and JAVA_JVM_LIBRARY. 

Some things we can try:

1. Remove use of JNI_LIBRARIES altogether when compiling on OSX.  We can try that see if it compiles and runs.  If success, let's do that.
2. If that fails, try just adding JAVA_JVM_LIBRARY instead of JNI_LIBRARIES.

**Comment by vlazzarini** [comment] 2015-07-04 21:53
OK, number 1 seems to work. But I think 2. is safer. Tried both, and funnily enough, the dependency list given by otool in both cases is identical.

**Comment by vlazzarini** [comment] 2015-09-16 12:09
This seems to have been solved with option 1. above so I am closing this issue

**Closed by vlazzarini** 2015-09-16 12:09 UTC
Labels: OSX

**Comment by peimankhosravi** [comment] 2015-09-19 17:05
Thanks very much!

P




*www.peimankhosravi.co.uk <http://www.peimankhosravi.co.uk> || RSS Feed
<http://peimankhosravi.co.uk/miscposts.rss> || Concert News
<http://spectralkimia.wordpress.com/>*
