### ISSUE TITLE
ftgenonce with GEN01 ignores the channel parameter 

### ISSUE THREAD

**Issue by yrechab** [csound/csound#1189] opened 2019-09-25 18:46 UTC
hi again, 
in this example the Seashore.wav is played mono and the print statement reports
--Csound version 6.14 (double samples) Sep 25 2019
[commit: baa47b665f987727eb38ecf65de270884520052c]
ftgenonce: created new func: 101
ftgenonce: re-using existing func: 101.000000
instr 1:  itabL = 101.000  itabR = 101.000

instr 1
itabL ftgenonce 0,0,0,1,"Seashore.wav",0,0,1
itabR ftgenonce 0,0,0,1,"Seashore.wav",0,0,2

; itabR ftgenonce 0,0,0,1,"Seashore.wav",0.001,0,2 -- works
; also the variant with ftgen works.

print itabL,itabR
andx phasor sr/ftlen(itabR)
asigL table andx, itabL, 1
asigR table andx, itabR, 1
     outs asigL, asigR
endin

best regards,
Christian

**Comment by jpffitch** [comment] 2019-09-25 20:13
Accordig to the commenrs ftgenonce uses te arguments of te call as a tag 
to ensure that te same file is not loaded twice.  i can onl assume that 
the key is ignoring the last argument.  Code is in C++ so beyond me.

Needs Mike Goins to comment/ficx

==John ff

**Comment by yrechab** [comment] 2019-09-27 12:59
the same problem occurs with other GENs. e.g GEN11 
  itab1 ftgenonce 0, 0, 65536, 11, 30, 1, 0.6 
  itab2 ftgenonce 0, 0, 65536, 11, 30, 1, 0.5 
  itab3 ftgenonce 0, 0, 65536, 11, 30, 1, 0.9 
  itab4 ftgenonce 0, 0, 65536, 11, 30, 1, 1
  itab5 ftgenonce 0, 0, 65536, 11, 30, 1, 0.2 
  itab6 ftgenonce 0, 0, 65536, 11, 30, 1, 0.3 
  itab7 ftgenonce 0, 0, 65536, 11, 30, 1, 0.8 
  itab8 ftgenonce 0, 0, 65536, 11, 30, 1, 0.7 
delivers
instr 60:  itab1 = 101.000  itab2 = 101.000  itab3 = 101.000  itab4 = 101.0 itab5 = 101.000  itab6 = 101.000  itab7 = 101.000  itab8 = 101.000

**Comment by jpffitch** [comment] 2019-09-27 13:18
Not surprised.  It adds to my belief that the hashing does not use all the arguments.

⁣Sent from TypeApp ​

**Comment by yrechab** [comment] 2019-09-27 19:54
ok i found a workarround which works now 
- (this shows that exactly the last parameter is not recognized) 
itab1 ftgenonce 0, 0, 65536, 11, 30, 1, ip1, 1
itab2 ftgenonce 0, 0, 65536, 11, 30, 1, ip2, 2
itab3 ftgenonce 0, 0, 65536, 11, 30, 1, ip3, 3
itab4 ftgenonce 0, 0, 65536, 11, 30, 1, ip4, 4
itab5 ftgenonce 0, 0, 65536, 11, 30, 1, ip5, 5
itab6 ftgenonce 0, 0, 65536, 11, 30, 1, ip6, 6
itab7 ftgenonce 0, 0, 65536, 11, 30, 1, ip7, 7
itab8 ftgenonce 0, 0, 65536, 11, 30, 1, ip8, 8
fortunately the GEN11 does tolerate an extra parameter ....

**Comment by rorywalsh** [comment] 2019-10-11 15:46
Hi @jpffitch I took at look at this and I can't see what the issue is. I'm using a simple:

```
itabL ftgenonce 0,0,0,1,"pianoMood2.wav",0, 0,1
itabR ftgenonce 0,0,0,1,"pianoMood2.wav",0, 0,2
```

As far as I can tell, and I could be way off, but the first time `ftgenonce` is called, function table data gets written to a the sfg_globals->functionTablesForEvtblks map. I've checked, and it looks like all p-fields are being written Ok. The next time ftgenonce is called, it checks to see if the current table data is already stored in the array:

https://github.com/csound/csound/blob/develop/Opcodes/signalflowgraph.cpp#L1393-L1395

The thing is find() seems to return a valid element even when it's not part of sfg_globals->functionTablesForEvtblks? For example here is the output from the first `ftgenonce` event block after it allocates the first table:

```
evtblk = {EVTBLK} 
 scnt = {int} 0
 strarg = {char * | 0x5601b99c61e0} "pianoMood2.wav"
 pinstance = {void * | 0x0} NULL
 opcod = {char} 102 'f'
 pcnt = {int16} 8
 p2orig = {double} 0
 p3orig = {double} 0
 p = {double [1999]} 
  [0] = {double} 0
  [1] = {double} 0
  [2] = {double} 0
  [3] = {double} 0
  [4] = {double} 1
  [5] = {double} nan(0x8000000000000)
  [6] = {double} 0
  [7] = {double} 0
  [8] = {double} 2
  (...)
  c = {union {...}}  
```

And were is the table data that is checked the second time `ftgenonce` is called:

```
evtblk = {EVTBLK} 
 scnt = {int} 0
 strarg = {char * | 0x5601b99c61e0} "pianoMood2.wav"
 pinstance = {void * | 0x0} NULL
 opcod = {char} 102 'f'
 pcnt = {int16} 8
 p2orig = {double} 0
 p3orig = {double} 0
 p = {double [1999]} 
  [0] = {double} 0
  [1] = {double} 0
  [2] = {double} 0
  [3] = {double} 0
  [4] = {double} 1
  [5] = {double} nan(0x8000000000000)
  [6] = {double} 0
  [7] = {double} 0
  [8] = {double} 1
(...)
 c = {union {...}}  
```

As you can see, they are not the same, yet
```
if (sfg_globals->functionTablesForEvtblks.find(eventBlock) !=
      sfg_globals->functionTablesForEvtblks.end()) 
```
returns true? Note I've never used a std::map in my life, so I'm really making quite a few assumptions about how they work...

**Comment by vlazzarini** [comment] 2019-10-11 16:48
@rorywalsh the two seem to differ very little, so I guess the bug is in find()?

**Comment by jpffitch** [comment] 2019-10-11 20:17
My tests suggest that the test to see if it is already loaded has the arg count vwrong by 1 so the original complaint appeared to load the first channel but not the second.  The work round was to add an extra 0 at the end of both and then it worked.  Is that not what you are seeing?  I could not follow the storing of the arguments anywhere but I only understand simple c++.

⁣Sent from TypeApp ​

**Comment by rorywalsh** [comment] 2019-10-11 20:21
So you mean pcnt? It seems to be the same in each one eventBlock no?

**Comment by jpffitch** [comment] 2019-10-11 20:21
Oh I see you have found the cache and it is correct.  Wonder if the Nan causes problems?  I would expect Nan to be not equal to Nan gif test is numerical rather than bitwise.

I assume != is overloaded for this structure?

⁣Sent from TypeApp ​

**Comment by vlazzarini** [comment] 2019-10-11 20:22
it uses the evtBlock struct as the key and does a comparison using the code from line 93, I think. That part might be the problem

**Comment by gogins** [comment] 2019-10-12 00:33
Yes, and NaN would be a problem.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment] 2019-10-12 00:54
Ignore my previous email about ftgenonce.

Unless I'm misunderstanding the discussion, the seashore.wav ftgenonce
will load twice because the parameters are different. Is this
considered to be a problem? If so, then for GEN 1 only, the comparator
at signaflowgraph.cpp:193 can be modified to ignore the channel
number.

Regards,
Mike



-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by rorywalsh** [comment] 2019-10-12 05:56
It's not loading a second table but replacing the first, even though the
parameters are different.

**Comment by vlazzarini** [comment] 2019-10-12 06:03
yes, line 93 is the overloaded op I think

**Comment by rorywalsh** [comment] 2019-10-12 06:18
Setting table numbers is a workaround.

**Comment by vlazzarini** [comment] 2019-10-12 06:32
I don't think it is to do with nan, since GEN11 showed the same bug.

The comparator needs to be looked at. It is missing the final pfield and thinking it's the same.

**Comment by rorywalsh** [comment] 2019-10-12 06:35
All GENs show the same problem, not just 1 and 11.

**Comment by rorywalsh** [comment] 2019-10-12 07:15
Changing the following to loop til `i < n+1` seems to fix it. 
https://github.com/csound/csound/blob/e8eed4cfbdd89b43954047268c88a568a3f228d5/Opcodes/signalflowgraph.cpp#L195

**Comment by vlazzarini** [comment] 2019-10-12 08:14
that was it, final pfield never checked.

**Comment by vlazzarini** [comment] 2019-10-12 08:39
Thanks Rory for the fix, committed.

**Closed by vlazzarini** 2019-10-12 08:39 UTC
Labels: bug

**Comment by gogins** [comment] 2019-10-12 12:01
OK, I'll take a closer look at it.

**Comment by vlazzarini** [comment] 2019-10-12 12:03
this ticket is closed, Rory fixed it.

**Comment by gogins** [comment] 2019-10-12 14:12
OK, thank you Rory.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
