### ISSUE TITLE
Search paths for plugins

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1249] opened 2020-02-04 22:55 UTC
As discussed in the dev list, csound should search for plugins at multiple paths by default. In macos, if csound is installed via installer, plugins are searched in `/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64`, whereas if installed from source plugins are searched at `~/Library/...`. Both paths, and probably a third one, something like `~/Library/Csound/Opcodes64` should be searched by default. In linux, both `/usr/local/lib/csound/plugins64-6.0` and `/usr/lib/csound/plugins64-6.0` and maybe also `~/.local/lib/csound/plugins64-6.0`. There should be at least one location where a user can install plugins without super-user permissions.

**Comment by vlazzarini** [comment] 2020-07-14 16:18
There are new API functions and flags in Csound to allow for this. For users, they can now load all plugins from a given directory via

```
--opcode-dir=DIR        load all plugins from DIR
```

**Comment by gesellkammer** [comment] 2020-07-14 16:27
I would strongly suggest doing the opposite: there should be a default for each platform, and maybe a flag to prevent using that default, for the niche case where a pro user needs to test multiple versions/installations. Supercollider works this way, the pd application has settings to do the same. Without this any package manager for plugins would be very brittle.

**Comment by vlazzarini** [comment] 2020-07-14 16:51
There is a default for each platform already; on OSX it is the framework; elsewhere it is defined by CMAKE_INSTALL_PREFIX.
These can be overridden by OPCODE6DIR64. The code search currently does not look into more than one directory,  but
it can be modified. Last time I looked it appeared more involved than expected, but it can be done.

The flag I added is useful for anyone to load their custom plugins without having to have a separate option for each library.
It is a different use case altogether.

**Comment by gesellkammer** [comment] 2020-07-14 17:01
The request is explicitly to have a default path for plugins at the user level (ie, without admin rights) and without having to touch OPCODE6DIR64. Notice that setting OPCODE6DIR64 to a wrong value will prevent csound from finding its own plugins and rt modules. I can take a look and do a PR, but I need to reassurance that this is a desired feature.

**Comment by vlazzarini** [comment] 2020-07-14 17:06
But OPCODE6DIR64 is user level. Not sure what you are asking? It's a shell variable, no need for admin rights whatsoever.
Users can set it and unset it as they wish. We do not need another feature.

**Comment by gesellkammer** [comment] 2020-07-14 19:47
If that variable points to something other that the default or does not include the default, csound fails to find its own plugins. This is very error prone for inexperienced users and I can't imagine building a package manager which relies on inexperienced users doing complex things.

**Comment by kunstmusik** [comment] 2020-07-14 20:15
I need to catch up here but I'm generally in favor of a default user opcode
library directory in addition to system opcode dir. There may be issues if
copies are found relative to project, user, system directories, but that's
a problem that can be addressed.

**Comment by kunstmusik** [comment] 2020-07-14 20:48
BTW: For reference, python's site package system uses both system and user paths:

https://docs.python.org/3/library/site.html

```syyigmmbps-MacBook-Pro:build syyigmmbp$ python3
Python 3.8.3 (default, Jul  8 2020, 14:25:02) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getusersitepackages()
'/Users/syyigmmbp/Library/Python/3.8/lib/python/site-packages'
>>> site.getsitepackages()
['/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages']
>>>   
```

I think support for multiple paths makes a lot of sense and just dealing with one OPCODE6DIR64 variable would be ideal. Having it:

1. have one system default path
2. have one user default path
3. allow appending or replacing altogether

would cover just about any use case. Number 3 would be particularly useful for host applications that may provide custom opcode libraries or embed csound within them.  

I think also we should support risset as much as possible and this seems like it would do so, so I am all for it.

**Comment by vlazzarini** [comment] 2020-07-14 20:54
1) We have support for multiple paths in the code. That can be used by defaults or by OPCODE6DIR64
2) We have a means of loading individual libraries or a whole set of libraries from the command-line

We can do all of the three things you listed as of now, with no extra features. 

1. and 2. can be defined in CMakeLists.txt (as it is now), we have to agree what they should be for each system.
3. is enabled by OPCODE6DIR64 (replacement) or command-line options (appending).

Inexperienced users need not worry about OPCODE6DIR64, that point is absolutely moot. Setting that variable is just for users who understand what it does.

**Comment by kunstmusik** [comment] 2020-07-14 21:09
If the underlying multiple paths is there, then all that's necessary is, by
default, adding the one user path.  This should maybe be done at runtime
per-user and not baked into the compiled code.  (Imagine a system-installed
csound on a lab computer; each user would need their own user dir so CMake
wouldn't work here.)

**Comment by vlazzarini** [comment] 2020-07-14 21:14
The multiple paths work like PATH, using the `:` or `;` separators. That's for the default -- baked in at compile time -- and
OPCODE6DIR64.  Besides this, there's the new command-line option which can be passed to Csound to load from a given directory IN ADDITION to what's already there. It can be used multiple times for more than one directory.

**Comment by gesellkammer** [comment] 2020-07-14 21:25
So, to be concrete: where should opcodes be installed by default so that:

* opcodes will be loaded by csound by default, without user needing to modify OPCODE6DIR64
* path is accessible without admin rights

**Comment by vlazzarini** [comment] 2020-07-14 21:46
Do you mean opcodes other than the ones that come with Csound?

We could define a user-directory path such as ~/csound/plugins for linux and ~/Library/csound/plugins for MacOS, and something similar for Windows.

That path could be appended to the default opcodedir on CMakeLists.txt. We might need to have to add code to resolve ~ in csmodule.c

But what about a multiuser installation? Would we not want opcodes to also be installed "for all users" under admin rights?

**Comment by gesellkammer** [comment] 2020-07-14 22:04
> Do you mean opcodes other than the ones that come with Csound?
Yes, that is the sole motivation for the request and its discussion

There should be two paths which are always searched by default, one under the users's home directory (no admin rights needed) and one for multiuser installations.

## User path

The proposed user paths for the three main desktop platforms could be:
Linux: ~/.local/share/csound/plugins-6.0
macOS: ~/Library/csound/plugins-6.0
windows: C:\Documents and Settings\<User>\Application Data\csound\plugins-6.0
(following the standard defined,for example, here: https://pypi.org/project/appdirs)

This path needs to be expanded at runtime, as you pointed.

Regarding a global (multiuser) path, the currectly used one can be kept

**Comment by kunstmusik** [comment] 2020-07-14 23:08
Seems like we're on the same page now.  The addition of the user path will only add one additional place and it will need to be resolved at runtime rather than compile time.  System install works as before.  Users (hosts or end-users) can further modify the path by commandline flag or environment variable.  The paths mentioned by @gesellkammer seem good to me and the more modern way to do user paths than $HOME/.csound.  

Note: The only issue we might have is if a user has already defined their own OPCODE6DIR64 environment variable, they may be oblivious to the change to the additional user directory.  I think it's right that if a user defines OPCODE6DIR64 it overrides any defaults.  This should be a small issue we mention in the ChangeLog and in documentation.

**Comment by vlazzarini** [comment] 2020-07-24 09:21
I was wondering whether we would look to implement this for 6.15 or does it need longer testing?

**Comment by vlazzarini** [comment] 2021-04-14 08:07
Any movement on this issue? It's been almost a year.

**Comment by rorywalsh** [comment] 2021-05-26 19:45
It seems that the API function `csoundSetOpcodedir()` no longer works? Does this have anything to do with the changes here by any chance? I think it's important that the API feature a method for setting custom paths. If it has nothing to do with these changes I'll file a new ticket.

**Comment by vlazzarini** [comment] 2021-05-26 20:09
I think I found the issue. Can you try from git?

**Comment by rorywalsh** [comment] 2021-05-26 21:05
I just pulled again now and tested on Linux. It hangs when I test it, and stepping through the code brings to a dead end at: 
https://github.com/csound/csound/blob/develop/Engine/memalloc.c#L83

**Comment by vlazzarini** [comment] 2021-05-26 21:08
yes, but that doesn't help. What is the sequence of the calls from csoundCreate() onwards? I need to see that to diagnose.

**Comment by rorywalsh** [comment] 2021-05-26 21:15
mmalloc memalloc.c:83
cs_strdup csound_orc_semantics.c:70
csoundCreate csound.c:1344
main csound_main.c:323
__libc_start_main 0x00007fd8824acb97
_start 0x000055a19aa0836a

**Comment by vlazzarini** [comment] 2021-05-26 21:16
ok, I think I have an idea. Pushed a fix.

**Comment by vlazzarini** [comment] 2021-05-26 21:26
Ok, I think I got it now. Calling cs_strdup() before csoundReset() seems to be problematic. I've changed the code so it does not do that.

**Comment by rorywalsh** [comment] 2021-05-26 21:35
Thanks Victor. I can confirm this now works on my Linux box. I will grab the latest Windows build tomorrow and test there. Cheers.

**Closed** 2021-05-30 21:31 UTC
Labels: enhancement
