### ISSUE TITLE
Windows installer problems with install dir and environment

### ISSUE THREAD

**Issue by DaveSeidel** [csound/csound#1937] opened 2024-09-09 12:45 UTC
The current Csound 7 (prerelease) installer for windows has two serious problems:

1. Csound is installed in "C:\Program Files\Csound6_x64" instead of "C:\Program Files\Csound7_x64". This makes Csound 6 unusable, nor does Csound 7 work due to there being old DLL files remaining in the plugins64 directory.
2. The installer does not set the environment variable OPCODE7DIR64, which is needed for proper execution.

**Comment by vlazzarini** [comment] 2024-09-09 14:21
@stekyne looks like some simple edits to the installer. I had a quick look and it seems straightforward, but I can't test it myself. Could you have a look? I think the file should also probably be renamed to Csound_x64_github.iss dropping the "6".

**Comment by stekyne** [comment] 2024-09-09 14:59
Yeah I imagine some changes are needed. I'm away on vacation so it'll be another while before I can test but if this is still open I'll do it sure

**Comment by vlazzarini** [comment] 2024-09-09 18:08
thanks, @stekyne. @rorywalsh will do it for us.

**Comment by DaveSeidel** [comment] 2024-09-09 18:13
I will be happy to test it.

**Comment by vlazzarini** [comment] 2024-09-11 08:51
this should be fixed now in develop, thanks @rorywalsh. iF @DaveSeidel  can confirm we can then close this ticket.

**Comment by DaveSeidel** [comment] 2024-09-11 13:34
I will try it, just waiting for the latest build to complete.

**Comment by DaveSeidel** [comment] 2024-09-11 13:41
I just installed build 7.0.0.2719. It is still installing in "C:\Program Files\Csound6_x64" on top of an existing Csound 6 install, and produces a segment violation on execution, I assume because of DLLs from the previous version.

**Comment by DaveSeidel** [comment] 2024-09-11 13:54
I restored Csound 6 on my test system. My criteria for success is that Csound 7 runs, that Csound 6 remains installed and runnable, and that the Csound 7 installer sets OPCODE7DIR64 in the environment.

**Comment by DaveSeidel** [comment] 2024-09-11 17:11
Good progress with build 2722, but the install directory is still defaulting to "C:\Program Files\Csound6_x64". When I manually changed it to "C:\Program Files\Csound7_x64" installation completed successfully, including setting (appending) PATH and OPCODE7DIR64. After I moved the PATH entry for Csound 7 to take precedence over the Csound 6 path, I was able to run xanadu.csd successfully. When I moved the Csound 6 path to take precedence, Csound 6 ran fine (same test).

So as far as I can see, the only remaining issue is to change the default installation directory.

**Comment by vlazzarini** [comment] 2024-09-11 18:35
I thought that had been done already, as per the commit messages. Would there be some sort of name cache involved?

**Comment by DaveSeidel** [comment] 2024-09-11 19:17
Maybe the installer uses the existing path if the previous version is installed, but if so that doesn't seem right to me. I will try uninstalling Csound 6 first and then running the Csound 7 installer. But a new major version should use the correct path even if there's an existing installation of a different major version.

**Comment by DaveSeidel** [comment] 2024-09-11 19:38
On my system with both Csound 6 and 7, I uninstalled 7, and this brought up two other issues:
- the Csound folder with documentation and uninstaller links etc. is gone from the Windows application list in the Start menu
- Csound 6 is no longer listed in Settings/Apps/Installed Apps
 
So now there's no way to properly uninstall Csound 6, unless I reinstall 6 first. And there's no way for a user to see that Csound 6 is even installed when they look at the Start menu. The software is still present on disk and on the path, but that's not enough.

Version 7 needs to install and uninstall cleanly without affecting artifacts installed with v6.

**Comment by DaveSeidel** [comment] 2024-09-11 19:41
Though I haven't tested this scenario, it's seems likely that if I have both versions installed and uninstall v6, it will have the same affect, making v7 "invisible" with no way to uninstall it.

**Comment by rorywalsh** [comment] 2024-09-12 11:07
I just tested the latest installer available from the develop branch on GH
Actions, and the second page of the installer lets you select the install
dir. Perhaps you were testing an earlier version? The ability to select the
install location was only added yesterday after some initial testing.

**Comment by DaveSeidel** [comment] 2024-09-12 11:53
Rory, as I think I said in a previous message, the install dir page does appear, and I was able to change it. The issue is that the v7 installer still defaults to the v6 dir, at least on my system where v6 was already installed. I believe that one of the goals is to allow both versions to coexist, and I think most people will miss the subtle difference and click through, and end up with an installation that doesn't work for either version.

**Comment by DaveSeidel** [comment] 2024-09-12 12:06
OK, I removed v6 from my system, and in that case, the v7 installer defaults to the correct v7 dir. So it is probably looking for something in the registry, and if it finds an existing installation, it's using that dir by default. This is what we can hopefully change. My guess is that we're using "csound" as the identifier (for Start menu items etc), and maybe instead we should start using "csoundN" where N is the major version number.

**Comment by rorywalsh** [comment] 2024-09-12 12:27
I have Csound6 installed here, and when I ran the installer and selected the Csound7 location it installs where I'd expect. I've checked the [script](https://github.com/csound/csound/blob/develop/installer/windows/csound7_x64_github.iss), `{app}` is the var that holds the user selected install location. I can't see how it is picking up a cached value. I'm not an InnoScript expert so I can't say for sure what the problem is. Can you try removing 7, and installing 6 again. Then without removing 6, try installing 7 and see what happens?

**Comment by DaveSeidel** [comment] 2024-09-12 15:06
I just tested it again:

1. removed v7
2. installed v6
3. ran the v7 installer -- it is still displaying "C:\Program Files\Csound6_x64"

This in on a fairly new Win11 laptop.

We probably need someone else to test this as well, to break the tie. :-)

**Comment by rorywalsh** [comment] 2024-09-12 15:20
Thanks for testing this Dave. I'm going to test it later on a fresh Windows machine and see what happens. But so I'm clear, although it defaults to the previous version, you can still change that and install to the a new location? 

[edit] It looks like we should be adding this to the [setup] section:
`DefaultDirName={pf64}\{#AppName}`
I will try it later and see if that does the trick. We can also try clearing the registry, but I'm relucant to do that just yet.. 

[edit 2] I just added that and made a PR. Hopefully this will resolve the issue.

**Comment by DaveSeidel** [comment] 2024-09-12 16:02
Sounds good. Yes, the field is editable, and I can change it.

**Closed as completed** 2024-09-12 16:43 UTC

**Comment by vlazzarini** [comment] 2024-09-13 15:26
@DaveSeidel can you confirm it's now all good?

**Comment by DaveSeidel** [comment] 2024-09-13 15:51
Looking good! I don't know if we consider this an issue, but v6 installs in
Csound6_x64 and v7 installs Csound7 (without the suffix). I did have to
move the PATH entry for v7 above v6 so it would take precedence, but I
think that's fine.

**Comment by rorywalsh** [comment] 2024-09-13 21:13
Now would be the time to change if you think it needs changing. My thinking on this was it's ok to drop the x64 as this is now the defacto for Windows. But maybe it would be better to use Csound7_x64? What say you all?

**Comment by DaveSeidel** [comment] 2024-09-13 22:02
Yeah, I think on Windows it's not needed. It's implicit by being in
ProgramFiles and not ProgramFiles32.

**Comment by kunstmusik** [comment] 2024-09-13 23:06
Well, Windows on Arm is certainly something we have to keep an eye on, but we can just label the installers appropriately and they can installed without the x64 or arm.
