### ISSUE TITLE
Csound~ crashes Max when receiving bypass 1

### ISSUE THREAD

**Issue by unriginal** [csound/csound#489] opened 2015-06-19 06:03 UTC
If I turn on DSP in Max, and then send a "bypass 1" message to Csound~, or if I have DSP off, send a "bypass 1" message, and then turn DSP on in Max, Max crashes. I'm using Max 7.0.3, Csound~ 1.1.3, and OSX 10.10.3.

**Comment by kunstmusik** [comment] 2015-06-27 02:22
I think issue #491 was a duplicate of this. I found the bug and committed a fix (see #491 for more information).  Closing this one out.

**Closed by kunstmusik** 2015-06-27 02:22 UTC
