### ISSUE TITLE
--midifile flag not working when used in .csd <CsOptions> section

### ISSUE THREAD

**Issue by andy-fillebrown** [csound/csound#687] opened 2016-08-07 18:07 UTC
Csound 6.06 on OSX. The --midifile flag in a .csd CsOptions section doesn't work. Csound's output says "*** error opening MIDI file 'xxx.mid': No such file or directory". Using the -F flag works if there's a space between the -F and the midi file, but gives the same error if no space is given between the -F and the midi file. I get the error in both CsoundQt and CsoundUnity.

**Comment by jpffitch** [comment] 2016-08-22 10:42
Does it happen from the command line?
Does it happen with CsOptions and command line?
What is CsoundUnity?
Does it happen on 6.07?
Any chance an example input?

I looked at the code nd it is not obvious what could go wrong

**Comment by jpffitch** [comment] 2016-08-22 12:18
Failed to reproduce in command-line csound with --midifile= on options.

**Comment by andy-fillebrown** [comment] 2016-08-26 23:22
Running the attached .csd and .mid file from the command line with no options will show the error.
Uncomment the other 2 option lines in the .csd for examples of the -F flag working and not working depending on whether or not a space is between the flag and the file name.

[midifile-option-bug.zip](https://github.com/csound/csound/files/440315/midifile-option-bug.zip)

**Comment by kunstmusik** [comment] 2016-08-27 00:58
I tested here on Windows and could reproduce the error.  The issue as it appears to me is the use of quotation marks around the file name.  If I modify the --midifile="test.mid" to --midifile=test.mid it runs. I don't know if the behavior is different when parsing from CsOptions versus terminal, but, if so, that would explain it.  (i.e., if the shell would remove the quotes before passing to Csound).  

argdecode.c looks to just advance the pointer to the next spot after the "=", and this seems to be the case throughout.  Perhaps that area of code needs to do some kind of parsing, or a flag given so that it knows to parse differently from CsOptions rather than command-line.  

I'm not all that familiar with this area of code, so will just leave it here with the commentary above.

**Comment by vlazzarini** [comment] 2016-08-27 09:06
This must be system dependent then. On OSX, and I expect Linux and other "unices" double-quotes are removed and the string is presented without them to the program. So the code is correct to assume it. To confirm I've just run --midifile="/path/to/file.mid" and the filename was passed alright.

**Comment by kunstmusik** [comment] 2016-08-27 10:22
But this big is specifically about CsOptions within a csd. Are you testing
that?

**Comment by andy-fillebrown** [comment] 2016-08-27 13:24
Thanks for looking into this. As Steven says, this issue is specifically for the CsOptions section of .csd files. I have no issue using quotes on the command line so I was surprised when identical usage in CsOptions did not work.

I am on OSX and Steven tested on Windows so it is not OS specific.

If it is a quoting issue then it should not be difficult to fix but I am still curious about why it works with the -F flag when a space is used between the flag and the quoted filename as seen in the second set of options in the example I posted.

**Comment by jpffitch** [comment] 2016-08-27 14:22
Running your example I see

name=0x72d538 "\003test.mid"

Note the \003 character
Now to see from whence it came
==J

**Comment by jpffitch** [comment] 2016-08-27 15:03
I have found where the \003 coes from but not sure wy the code does that. 
May take a while.
==J

**Comment by jpffitch** [comment] 2016-08-27 15:52
I think I havepatched it but there isa problem I do not understand here
==J

**Comment by jpffitch** [comment] 2016-08-28 14:33
Better patc installed so closing isse

**Closed by jpffitch** 2016-08-28 14:33 UTC
