### ISSUE TITLE
Parser generator places generated files in wrong directory for mingw build

### ISSUE THREAD

**Issue by gogins** [csound/csound#650] opened 2016-06-08 19:18 UTC
For the MSYS2/ming64 build for Windows x64, the flex and bison parser generators place generated source code files in csound/mingw64/csouhd-mingw64. However, the build system expects to find these files in csound/.

The build system should be corrected either to place the generated files in csound/ or to compile the generated files from csound/ming64/csound-mingw64.

**Comment by kunstmusik** [comment] 2016-10-23 22:23
@gogins is this an issue?  The build was purposely designed to generate the flex/bison into the CMAKE_CURRENT_BINARY_DIR to keep the source tree tidy when doing out-of-source builds.  This was done long ago and seems to work fine across platforms. The CMakeLists.txt in the root folder correctly uses the location of the generated files:

```
list(APPEND libcsound_SRCS
    ${LEX_OUT} ${YACC_OUT} ${PRELEX_OUT}
```

As far as I can see, this is issue is not a bug and may be closed.  As a further note, I'm building without problems with msys2/mingw64 on Windows x64. Please confirm my analysis is correct or describe what problems you are having there further.

**Comment by gogins** [comment] 2016-10-25 18:17
I'm away from my windows machine tilll the beginning of November. I'll
check it then.

Best,
Mike

**Comment by gogins** [comment] 2016-11-03 18:37
I have checked this by doing a clean mingw64 cmake and build, checking for duplicate files etc. There does not appear to be a problem; Csound built and ran fine.

**Comment by vlazzarini** [comment] 2016-11-03 20:56
ok, closing this one then

**Closed by vlazzarini** 2016-11-03 20:56 UTC
Labels: bug, windows
