### ISSUE TITLE
rezzy explodes above and below certain cutoff frequencies

### ISSUE THREAD

**Issue by tarmoj** [csound/csound#543] opened 2015-10-25 14:27 UTC
rezzy opcode explodes in highpass mode (imode=1) when the cutoff frequency is around 13350 Hz or aobve; likwise in lowpass mode (imode=0) it explodes when the cutoff is below 133 Hz.
Could it be somehow limited safely within the code of the opcode?

Example:
```
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>
sr = 44100 
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
	icutoff = p4
	ires = p5
	imode = p6
	aout rezzy pinkish(0.5), icutoff, ires, imode
	out aout
endin

</CsInstruments>
<CsScore>
;x
i 1 0 1 132 100 0 ; under 133Hz lowpass resonant filter explodes
i 1 0 1 132 1 0 ; and it does not depend on amount of the resonance
s

i 1 0 1 13350 100 1 ; above 13350Hz highpass resonant filter explodes
</CsScore>
</CsoundSynthesizer>

```

**Comment by tgrey1** [comment] 2015-10-26 09:25
I mentioned this on the email list recently too.  The frequency it explodes at depends on the resonance, so try fiddling with that a little... but I agree, the behavior is far too unstable to believe this opcode is working as intended.

Incidentally, even the manual example for rezzy explodes (unless it was updated within the last month).

**Comment by jpffitch** [comment] 2015-11-09 20:56
I have code that checks for unstable parameters. What should it do?  Fail? Report? some kind of fixup?

**Comment by tgrey1** [comment] 2015-11-09 21:12
My experience with this is that the frequency rezzy explodes at is also
dependent on the resonance, so I don't think it's as simple as limiting the
frequency range.  It's been a few weeks since I really played with rezzy
tho, so I don't recall exactly the limits I was running into.

John, my personal opinion is that since it's stability is dependent on
krate / performance time variables, it should probably do it's best to
clean them up.  Otherwise, it interrupts a performance and everything has
to be restarted/reinitialized to get sound out of the filter again.

**Comment by jpffitch** [comment] 2015-11-10 20:39
I found a broken optimisation in the rezzy low-pass code and as far as I can tell the manual example is fine.  Still struggling with the instability checker -- seems to give wrong answers.  More later

**Comment by jpffitch** [comment] 2015-11-12 16:37
I have a version of rezzy that cannot explode.  If a pole of the filter is outside the unit circle it is scaked to a radius of 0.9999, and so the instability is removed. This coupled with the coding fix in lowpass mode makes it complete.  Is that an acceptable solution?

**Comment by tgrey1** [comment] 2015-11-12 17:20
Sounds like it will be perfect to me, can't wait to try it.

**Comment by jpffitch** [comment] 2015-11-12 18:56
Can you build from github?  If so I will commit a non-limited version.

**Comment by jpffitch** [comment] 2015-11-12 20:05
I cannot find an exampe of lowpass explosion.  If you find one I would love to have it.b

**Comment by tarmoj** [comment] 2015-11-13 10:44
Thank you,
I will build and test this evening.
With greatest respect,
tarmo
12.11.2015 18:37 kirjutas kuupäeval "John ffitch" <notifications@github.com

**Comment by tarmoj** [comment] 2015-11-17 08:07
I got now to testing the rezzy improvements.

Results:
lowpass mode (imode=0) works fine under certain limit (around 13000), 
above that gives warning:  rezzy instability corrected (that I think is great 
idea). There are samples out of range though. when resonance is high. 
works with rather low resonance
Lowpass mode works fine now with low frequencies that was problem 
before.


Highpass mode has turned more instable though - 
it works fine with high frequencies (that was problem before), warning rezzy 
instability corrected. No samples out of range.
BUT
low  and also mid frequencies produce a lot of samples out of range. No 
warning. Also with low resonance.


The csound code I used for testing:

------
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>
sr = 44100 
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
	icutoff = p4
	ires = p5
	imode = p6
	;kcutoff line 16,p3,22000
	aout rezzy pinkish(0.5), icutoff, ires, imode
	out aout
endin

</CsInstruments>
<CsScore>
x
i 1 0 1 12000 100 0 ; lowpass. works fine under 12000
i 1 2 1 15000 10 0 ; lowpass. above 12000 gives warning:  rezzy instability 
corrected. Samples out of range though. when resonance is high. works 
with rather low resonance
i 1 3 1 50 100 0 ; works fine now with on low frequencies that was problem 
before
s

i 1 0 1 18000 100 1 ; works fine with high frequencies (above 4000 Hz), 
warning rezzy instability corrected. No samples out of range.
i 1 1 1 500 10 1 ; low  and also mid frequencies produce a lot of samples 
out of range. Now warning. Also with low resonance

</CsScore>
</CsoundSynthesizer>

Thank you!
tarmo


--------


On Thursday 12 November 2015 12:05:44 John ffitch wrote:
> I cannot find an exampe of lowpass explosion.  If you find one I would 
love

**Comment by vlazzarini** [comment] 2015-11-17 08:20
I think samples out of range are inevitable in resonant filter behaviour and strategies (such as using balancing) need to be used to prevent it (it is an instrument design issue, in my opinion). With this report, I would consider the issue fixed (to the extent that it can be).

**Comment by tarmoj** [comment] 2015-11-17 08:29
Otherwise yes, but the highpass mode just crackles with cutofff frequency 
under 4000 Hz (or so), so it is worse than before. Before highpass did not 
work above 13500 Hz and lowpass under 130 Hz that was possible to limit 
out but now highpass mode is practically useless.

I hope it is possible to find the reason, other corrections are really great!

thaks,
tarmo

On Tuesday 17 November 2015 00:20:14 vlazzarini wrote:
> I think samples out of range are inevitable in resonant filter behaviour 
and

**Comment by jpffitch** [comment] 2015-12-08 14:29
Tarmo, I have been away from this for a while so having trouble picking up the threads.  I assume lowpass is now OK but highpass is iffy?  Could you mail me ann example of it going wrong so I can compare with older code?

**Comment by tarmoj** [comment] 2015-12-08 15:35
Thanks for looking into this!

I hope this code helps you to test (also attached):

<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>
sr = 44100 
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
	icutoff = p4
	ires = p5
	imode = p6
	;kcutoff line 16,p3,22000
	aout rezzy pinkish(0.5), icutoff, ires, imode
	out aout
endin

</CsInstruments>
<CsScore>
x
i 1 0 1 12000 100 0 ; lowpass. works fine under 12000
i 1 2 1 15000 10 0 ; lowpass. above 12000 gives warning:  rezzy instability 
corrected. Samples out of range though. when resonance is high. works 
with rather low resonance
i 1 3 1 50 100 0 ; works fine now with on low frequencies that was problem 
before
s

i 1 0 1 18000 100 1 ; works fine with high frequencies (above 4000 Hz), 
warning rezzy instability corrected. No samples out of range.
i 1 1 1 500 10 1 ; low  and also mid frequencies produce a lot of samples 
out of range. Now warning. Also with low resonance

</CsScore>
</CsoundSynthesizer>

tarmo





On Tuesday 08 December 2015 06:29:54 John ffitch wrote:
> Tarmo, I have been away from this for a while so having trouble picking 
up
> the threads.  I assume lowpass is now OK but highpass is iffy?  Could 
you
> mail me ann example of it going wrong so I can compare with older code?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/csound/csound/issues/543#issuecomment-162897800


<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>
sr = 44100 
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
	icutoff = p4
	ires = p5
	imode = p6
	;kcutoff line 16,p3,22000
	aout rezzy pinkish(0.5), icutoff, ires, imode
	out aout
endin

</CsInstruments>
<CsScore>
x
i 1 0 1 12000 100 0 ; lowpass. works fine under 12000
i 1 2 1 15000 10 0 ; lowpass. above 12000 gives warning:  rezzy instability corrected. Samples out of range though. when resonance is high. works with rather low resonance
i 1 3 1 50 100 0 ; works fine now with on low frequencies that was problem before
s

i 1 0 1 18000 100 1 ; works fine with high frequencies (above 4000 Hz), warning rezzy instability corrected. No samples out of range.
i 1 1 1 500 10 1 ; low  and also mid frequencies produce a lot of samples out of range. Now warning. Also with low resonance

</CsScore>
</CsoundSynthesizer>
<bsbPanel>
 <label>Widgets</label>
 <objectName/>
 <x>0</x>
 <y>0</y>
 <width>0</width>
 <height>0</height>
 <visible>true</visible>
 <uuid/>
 <bgcolor mode="nobackground">
  <r>255</r>
  <g>255</g>
  <b>255</b>
 </bgcolor>
</bsbPanel>
<bsbPresets>
</bsbPresets>

**Comment by tgrey1** [comment] 2015-12-08 15:40
John, do you use cabbage?  I have been working on a few instruments that
have selectable filters including rezzy.  It might make it *really* easy to
identify the problems with freq/res since you can tweak the knobs real time.

**Comment by jpffitch** [comment] 2015-12-08 16:11
No -- command-line only here; sorry

**Comment by jpffitch** [comment] 2015-12-08 17:35
I have found a serious anomoly in the highpass code.  Will take a wile to sort out

**Comment by jpffitch** [comment] 2015-12-08 20:01
It was a sign error deep in the biquad.  Seems OK now.  Can be out of limit but a use of balance fixes that
instr 1
        icutoff = p4
        ires = p5
        imode = p6
        ;kcutoff line 16,p3,22000
        a1 pinkish 0.5
        aout rezzy a1, icutoff, ires, imode
        aref oscil 0.5, 440, 1
        aa balance aout, aref
        out aout,aa
endin

Code committed to git

**Comment by tarmoj** [comment] 2015-12-08 21:01
I tested, works perfectly!

Thanks a lot!

tarmo

**Closed** 2015-12-08 21:04 UTC
Labels: bug
