### ISSUE TITLE
Csound breaks init-time of K opcode outputs between 6.14 and 6.18

### ISSUE THREAD

**Issue by hartmans** [csound/csound#1707] opened 2023-04-24 13:33 UTC
Hi.  I upgraded to Debian's csound 6.18.1 and my orchestra broke.  After a bit of diagnosis, I came up with a fairly simple reproducing test case.
My understanding of the opcode docs is that a K output parameter should be initialized both at i-time and at k-time.
So I ought to be able to do
```
sr=44100
opcode inittest,K,0
kinit init 1
xout kinit
endop
instr 1
kinit inittest
if i(kinit) != 1 then
prints "fail\n"
prints "kinit is %d\n", i(kinit)
endif
endin
```
With a score liuke
```
i 1 0 0.1
```
and not see it print failed.
That's what I get with csound 6.14:
```
root@07e5e53f388e:/# csound -onull /tmp/init.orc /tmp/init.sco
0dBFS level = 32768.0
--Csound version 6.14 (double samples) 2020-11-20
[commit: none]
libsndfile-1.0.31
orchname:  /tmp/init.orc
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 256 sample-frame blocks
writing 512-byte blks of shorts to null (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  0.100 T  0.100 TT  0.100 M:      0.0
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.              overall amps:      0.0
           overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s
256 512 sample blks of shorts written to null (WAV)
```
But with 6.18.1:
```
orchname:  /tmp/init.orc
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
--Csound version 6.18 (double samples) 2022-11-24
[commit: none]
libsndfile-1.2.0
graphics suppressed, ascii substituted
sr = 44100.0, kr = 4410.000, ksmps = 10
0dBFS level = 32768.0, A4 tuning = 440.0
orch now loaded
audio buffered in 256 sample-frame blocks
ALSA output: total buffer size: 1024, period size: 256
writing 256 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:
fail
kinit is 0
B  0.000 ..  0.100 T  0.100 TT  0.100 M:      0.0
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.              overall amps:      0.0
           overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.091s, CPU: 0.006s
18 256 sample blks of 64-bit floats written to dac

```

**Comment by vlazzarini** [comment] 2023-04-24 14:00
I think the problem is that the opcode is putting out values at i-time because if we force it 

```
opcode inittest,K,0
kinit init 1
xout i(kinit)
endop
```

then it works. Could you tell us what was the last version it worked so we can trace any changes? I do not think we touched that part of the code recently. @kunstmusik may have some ideas too.

**Comment by vlazzarini** [comment] 2023-04-24 14:23
Ok, I found the source of this in the following issue

https://github.com/csound/csound/issues/1000

With the changes in Csound 6, there is no way to discern whether k or K is being used at output, the type is always set to 'k' or 'i' ('K' is not a Csound type). Before the fix for the issue above, k-vars were always copied, but that was not deemed to be the right thing. After this change (3 years ago it seems), no k-variable can be copied, only i-vars are copied at init time.

https://github.com/csound/csound/blob/2e324328d0bf8b446b6c20082224de311982c4bb/Engine/insert.c#L1635

We may require some way of communicating that this is a k- and i-time variable.

**Comment by kunstmusik** [comment] 2023-04-24 16:33
> I've got it working by introducing a new K type. I need to check it before committing.

I think we might need to be careful with add a new type for this. I'm unsure but I would suspect the code that checks if types match might fail around the codebase as K and k won't match. If we could get a reference to the specified types and check for K when CS_VAR_TYPE_K is found, I think it'll isolate the code change to where it needs to be in xoutset.

**Comment by vlazzarini** [comment] 2023-04-24 17:32
Adding a new type worked, but thinking about it now, it may not be needed. I think I have a simpler fix, which I will try tomorrow.

**Comment by kunstmusik** [comment] 2023-04-24 18:03
Sounds good, I tried interrogating the intypes and outtypes but oddly
they seemed corrupted by the time they got to xoutset. Will wait to
hear from you on tomorrow.

**Comment by vlazzarini** [comment] 2023-04-25 08:18
Ok this is done now, without a new type.

**Comment by hartmans** [comment] 2023-04-30 04:41
Shouldn't the check for required[0] go before confirming that required and found are non-null?
```
+
+     if(required[0] == 'K' && found[0] == 'k'){
+      return 1;
+     }
+    
     if (UNLIKELY(found == NULL || required == NULL)) {
       return 0;
     }

```
I.E. reverse those two hunks?
And in the next function in the patch as well.

**Comment by vlazzarini** [comment] 2023-04-30 09:14
yes, thanks. Checks for null first.

**Comment by hartmans** [comment] 2023-04-30 14:10
Hi.  Can I get you to confirm that with the patch applied, my test case at the top of this issue actually works?
For me, it does not, but I am not currently doing a build from the tip of the csoundy6 branch, but instead am doing a build from Debian's sources with the specific patch applied.
If it's working for you I'll figure out how to get all the build dependencies in a non-packaging environment and do a build to see what's going wrong.
I've also noticed that check_in_args fails to account for several situations.
I'd assume with a K type in-arg, I ought to be able to pass in an ivariable or even a constant.  Which is to say that poly_in_types and friends need to be accounted for.
I have what I think is a fix at https://github.com/hartmans/csound/commit/d4f03d0cf5c4f3883aacfb1b87dc2f000e7c124f
as well as a fix earlier on that branch for the null pointer comparison.
The null pointer fix is required in order to get the orchestra semantics tests to pass.

**Comment by vlazzarini** [comment] 2023-04-30 16:50
yes your code works here. I'll still have to change the null check but that doesn't affect the particular fix.

**Comment by vlazzarini** [comment] 2023-04-30 18:17
@kunstmusik maybe you might have some ideas where to look. I reverted to before my fix to check and I see a memory overwriting issue.

Here's the problem:

- the string  useropcdset outtypes of the opc->useropinfo carrying the types is being overwritten between symbtab.c:parse_opcode_args()  and being seen at insert.c: useropcset()
- there's a random string appearing there, sometimes even some odd text (like the word "Configuration").
- the memory location of the string is not changed, just the contents.

I wonder where we can check between these two places.

**Comment by vlazzarini** [comment] 2023-04-30 20:01
Ok I've pushed a hack just to see if we can make this work. In symbtab.c, I made a copy of inm->outtypes to a new struct field inm->outtypes_cpy and in insert.c I am checking for this to proceed with copying or not. That works, so the principle is sound, we need to find where inm->outtypes is overwritten.

@hartmans with this commit, your code is back working. It is not the final answer but we'll get there. We seemed to have uncovered an unrelated hidden bug.

**Comment by hartmans** [comment] 2023-04-30 20:18
I've found hardware watch points can be a great debugging tool in situations like this.  Set a breakpoint where you know the data is good, break there, and then set a hardware watchpoint on modifications of that data.
I don't think I have time to do that today; I'm heads down in an unrelated project, but if you haven't found what's going on soon, I will see if I can get somewhere with that approach.

**Comment by vlazzarini** [comment] 2023-04-30 20:40
thanks, any help is very welcome.

**Comment by hartmans** [comment] 2023-05-01 15:43
It looks like this is fairly classic memory corruption.
I want to show first how you can trace things down.  This was taken from a version of the code before the fix.
In add_ud,o_dedfinition I break just after the outtypes is te:
```
#0  add_udo_definition (csound=0x55af7144e2a0, 
    opname=0x55af7157cb40 "inittest", outtypes=0x55af715bb4b0 "K", 
    intypes=0x55af715bb520 "0") at /csound/Engine/symbtab.c:578
578         inm->outtypes = outtypes;

```
I next so that the outtypes is actually set, and then I print the address:
```
(gdb) n
579         inm->in_arg_pool = csoundCreateVarPool(csound);
(gdb) p inm->outtypes
$1 = 0x55af715bb4b0 "K"

```
Then I watch that address.  I watch using gdb history rather than explicitly `watch inm->outtypes` because if I watch `inm` then the watch point will go away whenever `inm` goes out of scope
```
(gdb) p inm->outtypes
$1 = 0x55af715bb4b0 "K"
(gdb) watch *$1
Hardware watchpoint 3: *$1

```
Then I can continue
```
Hardware watchpoint 3: *$1

Old value = 75 'K'
New value = 107 'k'
verify_xin_xout (csound=0x55af7144e2a0, udoTree=0x55af715dbff0, 
    typeTable=0x55af7152b050) at /csound/Engine/csound_orc_semantics.c:1707
1707        for (i = 0; i < strlen(outArgs);i++) {

```
We're in code without the fix, so we expect the change from K to k.
Now we continue
```
Hardware watchpoint 3: *$1

Old value = 107 'k'
New value = 102 'f'
__memcpy_evex_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:298
298     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
```
Oh, that doesn't look so good.  Let's take a look at the backtrace
```
#0  __memcpy_evex_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:298
#1  0x00007f1793b4104e in cs_strdup (csound=0x55af7144e2a0, 
    str=0x55af71620d70 "fail\n") at /csound/Engine/csound_orc_semantics.c:73
#2  0x00007f17939357a4 in printksset_S (csound=0x55af7144e2a0, 
    p=0x7ffdd678b660) at /csound/OOps/ugrw1.c:377
#3  0x00007f17939362a4 in printsset_S (csound=0x55af7144e2a0, p=0x55af7165b530)
    at /csound/OOps/ugrw1.c:630
#4  0x00007f1793869466 in init_pass (csound=0x55af7144e2a0, ip=0x55af7165b210)
    at /csound/Engine/insert.c:117
#5  0x00007f179386afa5 in insert_event (csound=0x55af7144e2a0, insno=1, 
    newevtp=0x55af71453a18) at /csound/Engine/insert.c:482

```
So, If we take a look at cs_strdup, it looks like it's a csound_malloc followed by a strcpy.


I notice that in add_udo_definition, intypes and outtypes are just pointer aliased into inm.
That is, they don't appear to be strdupped or copied.  So we're taking memory from the caller and effectively claiming ownership of it.
The caller appears to be from the orchestra  grammar:
```
                add_udo_definition(csound,
                        ((ORCTOKEN *)$3)->lexeme,
                        ((ORCTOKEN *)$7)->lexeme,
                        ((ORCTOKEN *)$10)->lexeme);
```

I don't know how long the lexed orchestra text is expected to stick around.  Is it possible that the orchestra lex state is freed after compilation, and the memory is being reused?
Would it be safer to cs_strdup intypes and outtypes in  add_udo_definition?

**Comment by vlazzarini** [comment] 2023-05-01 19:33
Thanks for this, I think your solution was the right thing. The symptoms are of memory being freed and then reused, accessing it just giving us random garbage. Strduping seems to fix this, at least my tests indicate it.

**Comment by kunstmusik** [comment] 2023-05-02 20:34
Apologies I just saw the mention @vlazzarini, seems like everything is in order now or is there something I should look at?

**Comment by vlazzarini** [comment] 2023-05-02 21:14
@kunstmusik yes, it looks like @hartmans found the root cause of the bug. I applied the fix and it passes my tests

**Comment by kunstmusik** [comment] 2023-05-02 21:52
That's great to hear!

**Comment by vlazzarini** [comment] 2023-10-06 19:31
Looks like there may be a lingering issue @kunstmusik reported a breakage with code he uses.

Maybe we could review this. I see at the top that it is reported to work on 6.14 and not on 6.18. Maybe we could check that bit again?

**Comment by vlazzarini** [comment] 2023-10-06 19:42
@kunstmusik provided the test

opcode test, k, iK
  iv1, kv2 xin
  xout iv1 * kv2
endop

instr 1	

  ksig = test(440, lfo:k(1, 1))

  asig = oscili(0.5, 880 + ksig) 
  out(asig, asig)

endin

**Comment by jpffitch** [comment] 2023-10-07 09:15
Looks like a case for bisection 

⁣​

**Comment by vlazzarini** [comment] 2023-10-07 10:43
Ok, I spotted the issue. There was an inargs check for k that failed because K was found. My fix was to implement a check where the two args are aliased, which is what we would expect to happen at that point.

**Comment by kunstmusik** [comment] 2023-10-07 15:00
I pulled the latest and the small test seems to work but the original file
I was testing still seems to have problems.

**Comment by vlazzarini** [comment] 2023-10-07 17:00
ok, same error? See if -v gives other messages. It was very useful in finding the issue in the first case.


Basically, since that test failed, the opcode did not get added, even though its actual compilation was ok.

**Comment by vlazzarini** [comment] 2023-10-08 10:18
The check was wrong, I was not checking against the relevant opinfo, now it's fixed and your testing.csd code produces sound.

**Comment by kunstmusik** [comment] 2023-10-08 21:01
Did a quick test and both the simplified csd and original test csd ran as expected with the lastest changes. Thanks!

**Comment by vlazzarini** [comment] 2023-10-10 11:21
thanks for confirming. I will close this now and if any further issues arise, we can re-open.

**Closed by vlazzarini** 2023-10-10 11:21 UTC
