### ISSUE TITLE
k1 = (k2 < i1) ? k3 : k4 not initialising 

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1357] opened 2020-07-13 18:22 UTC
this code should set kDir to 1 at init, but it sets kDir to 0: 

instr not_working
 Sfile = "fox.wav"
 iDur = p3
 kTime init 0
 kDir = (kTime<iDur/2) ? k(1) : k(-1)
 printk2 kDir
 aOut diskin Sfile, kDir
 kTime += 1/kr
 out aOut
endin
schedule("not_working",0,4)

this works:

instr works
 Sfile = "fox.wav"
 iDur = p3
 kTime init 0
 if kTime < iDur/2 then
  kDir = 1
 else
  kDir = -1
 endif
 printk2 kDir
 aOut diskin Sfile, kDir
 kTime += 1/kr
 out aOut
endin

this is with csound from today's develop:
--Csound version 6.15 (double samples) Jul 13 2020
[commit: 262c76ac0dcb9caf998a79dd031dc9f20b6bdd4b]

**Comment by vlazzarini** [comment] 2020-07-13 20:51
The assignment is at perf-time not init time as per the code semantics, so at init-time kDir is zero unless the instrument instance has been run before, in which case, it is whatever value kDir had before. For a k var to have value at i-time you need to use init, and an i-time expression

k1 init (i1 > i2 ? i1 : i2)

**Comment by joachimheintz** [comment] 2020-07-14 08:41
yes my subject is not correct.  the point is that kDir is not set to 1 
but remains 0.  when you try the example code you will see the printout.

i don't need kDir to be something at init-time, but kDir should be 1 
starting from the first k-cycle.  but it is 0 and remains 0 until iDur/2.

**Comment by vlazzarini** [comment] 2020-07-14 09:55
Replacing the line by

```
kDir = (kTime<iDur/2) ? 1 : -1
```

Fixes this. k(1) is being only evaluated at i-time, and its value is zero.

**Comment by joachimheintz** [comment] 2020-07-14 10:13
and this is also much clearer code!  strange -- i had this version 
first, but it seemed not to switch to -1 after iDur/2, so i thought it 
might need k().  thanks for testing!

two minor remarks:

1. i don't get what you mean by " k(1) is being only evaluated at 
i-time, and its value is zero."  probably you mean i(1) rather than k(1)?

2. i cannot see a reason why the version
	 kDir = (kTime<iDur/2) ? k(1) : k(-1)
   is not supposed to work.  it is cumbersome code, but why it does not 
work, as all values are k?

**Comment by vlazzarini** [comment] 2020-07-14 12:05
So, k() for i-rate is a bit of a legacy code now. We used to need it to tell the parser to use the k-rate instead
of i-time function, e.g. rnd(1) would be i- time and rnd(k(1)) would be k-rate. We have annotations for that
now. Outside this use case, you can just put any i-time variable or constant in a k-rate expression.

In the present case, I am guessing, instead of looking at the code that what happens is
this

1) the true- and false- expressions are evaluated at i-time because there is no k-rate variable there, if
you used k1 instead, these expressions would be run at k-time. At i-time, k(x) is zero because the code
is not run.

2) k() is not doing its job of making sure the expression is run at the correct rate. That in itself might
be a bug in the parser, perhaps @kunstmusik or @jpff can advise.

**Comment by vlazzarini** [comment] 2020-07-14 17:32
a little more background: k(1) uses the k.i opcode which is an init-time opcode that returns a k-variable, so that is the
reason code above then is run at init-time only. However, there must be something funny going on, because the
code should just assign the input to the output, and so I would have expected it to work.

**Comment by jpffitch** [comment] 2020-07-19 19:54
i am getting more confused.  The output I get is

 i1     0.00000
 i1    -1.00000

I cannot understand how this can be; where does zero come from?

The opcode generated are
```
create_instrument: instr name not_working
create_opcode: Found node for opcode =
create_opcode: Found node for opcode =
create_opcode: Found node for opcode init
create_opcode: Found node for opcode ##div
create_opcode: Found node for opcode <
create_opcode: Found node for opcode ckgoto
create_opcode: Found node for opcode k
create_opcode: Found node for opcode =
create_opcode: Found node for opcode goto
create_opcode: Found node for opcode k
create_opcode: Found node for opcode =
create_opcode: Found node for opcode =
create_opcode: Found node for opcode printk2
create_opcode: Found node for opcode ##div
create_opcode: Found node for opcode ##add
instr not_working uses instrument number 1
```
which looks correct.  Not managed to get a full decode yet of the arguments but I am working on it.

**Comment by vlazzarini** [comment] 2020-07-19 20:03
I suspect 0 is what the memory location gets on initialisation, so I presume that's there because nothing replaced it.

**Comment by jpffitch** [comment] 2020-07-19 20:19
Cut down version 

instr not_working
Sfile = "fox.wav"
iDur = p3
kTime init 0
kDir = (kTime<iDur/2) ? k(1) : k(-1)
printk2 kDir,0,1
kTime += 1/kr
endin

compiles to

=.S args:       Sfile   "fox.wav"
=.i args:       iDur    p3
init.k args:    kTime   0
##div.ii args:  #i0     iDur    2
<.0 args:       #B1     kTime   #i0
ckgoto args:    #B1     __synthetic_300:
k.i args:       #k3     -1
=.k args:       #k2     #k3
goto args:      __synthetic_301:
k.i args:       #k4     1
=.k args:       #k2     #k4
=.k args:       kDir    #k2
printk2 args:   kDir    0       0
##div.ii args:  #i5     1       kr
##add.kk args:  kTime   kTime   #i5


which looks right to me.  Needs fresh eyes to see what is wrong; from where comes the zero?

**Comment by kunstmusik** [comment] 2020-07-19 20:24
The ckgoto from the ternary expression is maybe different from what is being generated with the if-then code?

**Comment by jpffitch** [comment] 2020-07-19 20:45
That must be it.  The if/then/ese generates cngoto followed by a kgoto 
while conditional expressions generates ckgoto and a goto.  The first test 
shold be the invese for internal reasons but that suggests it ought to 
generate cgoto and kgoto?

I hate confditioals n csound -- always gettung them wrng

**Comment by vlazzarini** [comment] 2020-07-19 20:49
But note the difference between k(-1) and simply -1. Not completely sure why it gives a different result.

**Comment by kunstmusik** [comment] 2020-07-20 03:42
It's odd, cngoto is thread 3 while kgoto is thread 2. ckgoto is thread 2 while goto is thread 3.  It seems like both have rate mismatches. The code that deals with ternary expressions looks to be create_cond_expression() in Engine/csound_orc_expression.c. I seem to remember some recent changes to ternary expressions and need to review the history and design a little bit to comment further.

**Comment by jpffitch** [comment] 2020-07-20 13:34
I am getting more and more confused. Using gd create_cond_expression does 
not get called!  How is it doing any transformations?

**Comment by jpffitch** [comment] 2020-07-20 15:10
I have adjusted the code now writes 1 followed by -1

Test wit care

**Comment by vlazzarini** [comment] 2020-07-24 21:22
Can we close this now? If it fixes the k() problem, then it's done.

**Comment by jpffitch** [comment] 2020-07-24 21:54
I think it is fixed

⁣Get TypeApp for Android ​

**Comment by vlazzarini** [comment] 2020-08-03 22:20
Reopening this as @kunstmusik detected a regression. We need to check his example,

```
Sout = (ibrackets > 0) ?  "error" : strsub(Spat, istart + 1, indx - 1)
```

**Comment by jpffitch** [comment] 2020-08-04 15:06
The string cases are different code from this issue.  Do we have a complete test for that line?

**Comment by jpffitch** [comment] 2020-08-04 15:34
Found a test.  Ufortunately the if-else version gives the correct answer while  the conditional expression is wrong in two ways, generating an empty string and error

This code has been extensively re-written multiple times recently as earlier the code had the wrong semantics (evaluating both branches).  Problem now is selecting the right gotos

The strategy is

#b = (whatever> 0)
if #b==true GOTO label1
  #S1 = false-case-expression
  GOTO #label2
label1:
  #S1 = true_case_expression
label2:
  #S0 = #S1

**Comment by kunstmusik** [comment] 2020-08-04 15:41
I think maybe the thing to check is what gotos were generated previously
and have the behavior match, since this is a regression. I'm not sure if
that would break with the other changes though.

**Comment by jpffitch** [comment] 2020-08-04 16:11
Aste test is init time and the strings are both i and ktime the GOTOs 
generated are cigoto and igoto in the two GOTO ops.  That seems corrt to 
me.  That still leaves the possiility of being broken for the k-cycle.

The if-else version (which computes the test in the other orde(r generates
cngoto(and I think goto) rather that cigoto/igoto

Isthatenought to explain it?

**Comment by jpffitch** [comment] 2020-08-04 16:52
I think the current github version is OK.  Needs others to test

**Comment by jpffitch** [comment] 2020-08-04 20:47
I was a rate problem in the case of strings.  I have committed a better (maybe correct) version.

**Comment by jpffitch** [comment] 2020-08-05 16:34
Passes tests at i-rate and k-rate so i think it is fixed

**Comment by jpffitch** [comment] 2020-08-05 19:37
Closing now as confirmed

**Closed** 2020-08-05 19:50 UTC
Labels: bug
