### ISSUE TITLE
Realtime concurrency bug on Linux

### ISSUE THREAD

**Issue by hlolli** [csound/csound#772] opened 2017-04-03 19:57 UTC
The backstory to discovering this bug can be found here https://github.com/nwhetsell/csound-api/issues/7 but there seems to be a strange difference between the behaviour of Mac and Linux (and probably Windows too?) on how accurate rt-events reach the main csound thread from a different thread. A reproduceable example would be this c-program which roughly (or very accurately) simulates how a thread sends concurrent messages to Csound from the nodejs api.

```c
#include <csound/csound.h>
#include <assert.h>

uintptr_t perform(void *data)
{
    return csoundPerform((CSOUND *)data);
}

int main(int argc, char *argv[])
{
    CSOUND *Csound = csoundCreate(NULL);
    assert(csoundSetOption(Csound, "--output=dac") == CSOUND_SUCCESS);
    char *orchestra =
        "0dbfs = 1\n"
        "ksmps = 1\n"
        "// ksmps = 64\n"
        "alwayson 1\n"
        "instr 1\n"
        "    outc 0.5 * expon:a(1, 0.1, 0.0001) * (poscil(162, 0.2) + poscil(80, 0.2))\n"
        "endin\n";
    assert(csoundCompileOrc(Csound, orchestra) == CSOUND_SUCCESS);
    assert(csoundStart(Csound) == CSOUND_SUCCESS);

    void *threadID = csoundCreateThread(perform, (void *)Csound);

    size_t timeInterval = 100;
    size_t maxTime = 10000;
    for (unsigned int i = 0; i < maxTime / timeInterval; i++) {
        csoundSleep(timeInterval);
        csoundInputMessage(Csound, "i 1 0 1");
    }

    csoundStop(Csound);
    assert(csoundJoinThread(threadID) == 0);
    csoundDestroy(Csound);

    return 0;
}
```

If played on linux, note the how the accuracy dramatically worsens when ksmps is changed from 1 to 64, and compare that to how infinitely less difference this makes when running this same program with different ksmps rates on MacOsX. I tested this on MacOsX with csound 6.07. It made no difference if I compiled older versions of Csound on Linux (down to 6.06). So this could be an old bug. On linux, I tried it both with NixOs and Fedora 25 with same result.

**Comment by vlazzarini** [comment] 2017-04-03 20:41
why would this be a Csound bug? There is no guarantee to synchronise the two threads. Csound can race ahead to produce a buffer full of samples and then wait until the audio card consumes it,
especially if the buffer size is not small. The difference with OSX is in how the backend works, if
it makes csound loop more or less at regular intervals, or if 'bunches' up. 

if you need that level of synchronisation between threads, you will need to program it. There is no guarantee to happen automatically. In a tight realtime situation, it might work OK, but you will need small buffers for jack or alsa.

Running at ksmps=1 slows it down to make it work, but at 64, Csound processing is fast enough for several kcycles to be bunched up.

**Comment by hlolli** [comment] 2017-04-03 21:25
Not sure how low level I need to dig, on Mac I sent csound trough Soundflower and auhal and neither caused a delay. On Linux I've used rt-kernel and non-rt-kernel with jack/pa_bl/pa_cb/alsa with different -B and -b values, I can understand that ~50ms inaccuracy is to be expected for 1024 sample buffers on 44,1KHz. But 700ms (some of the worst case latency) smells more fishy. I know nothing of multithreading programming but for the question why this should be a Csound bug, I don't know, but a chance that some locks and mutex's are being bit too harsh here to external input? Most likely I'm getting a Mac soon anyway so I'm not that stressed about this, but performing live with ksmps=1 is a recipie for buffer-underrun/xruns if not using anything more complex than few oscillators. But on the other hand, some low-level alsa modules could be hacked and I guess that's something I need to research, if given that this is not a Csound bug (and in return can close this).

**Comment by vlazzarini** [comment] 2017-04-03 21:39
I think you need to run this with either alsa or jack with -b 64 -B 256 or 128 - 512. Around that figure. Do you understand what is happening?

Csound runs several kcycles, fills the buffer and then waits for this to be consumed. This causes a timing jitter because your inputMessages do not get evenly distributed amongst successive k-periods. 

You could try getting the time from Csound and launch your events using that as a reference, rather than calling sleep.

**Comment by hlolli** [comment] 2017-04-04 15:02
No sure if I understand so correct me if I'm wrong. Jack/alsa callback is asks csound for frames stacked in buffer. Csound feeds Jack/alsa let's say 512 samples, in a one baked cake. While and even before Jack has completed playing this buffer, csound is already feeding it next buffer and the buffer after next one. As if csound knows what will be played in the future. So either jack needs to slow csound down from feeding so many buffers at once, or csound has to stop filling so many buffers? So this may boil down to how the queue is set up, could it be that we are looking at first in last out buffer queue instead of first in first out? Comparing https://github.com/csound/csound/blob/e8e67765f977a67f8af4624f9d84d2768b0240ff/InOut/rtauhal.c#L707 to https://github.com/csound/csound/blob/e8e67765f977a67f8af4624f9d84d2768b0240ff/InOut/rtjack.c#L834 seems to show how the audio is written to auhal and jack differently, but ignore this comparison if it's out of the blue.

As for the combination of -b64-B256 ksmps=64 on jack/alsa, the audio is still way off, worse than drunk.

I could get score time from csound and work that way, but then as far as I see, still looses realtime nature. If for example I bind the spacebar on my keybord to play a note, and I play it accurately, then it seems that it still needs to go from one thread to another.

Maybe instead of thinking so low level, me or the creator of the nodejs-api @nwhetsell should consider the possibility of single threaded event/performance design. If events can be sent trough a performancethread then this delay wont exist. But nodejs land is bit new to me so I may not know exactly what I'm talking about.

**Comment by vlazzarini** [comment] 2017-04-04 15:17
If you play from the keyboard, the issue reduces to one of latency, but if you are using a clock in one thread, there could be jitter, as there is no sync between the csound clock and the clock your thread.
It's a subtle distintiction, but it's important.

**Comment by nwhetsell** [comment] 2017-04-04 16:54
Here’s the same code with some time profiling:

```c
#include <csound/csound.h>
#include <assert.h>
#include <time.h>

uintptr_t perform(void *data)
{
    return csoundPerform((CSOUND *)data);
}

int main(int argc, char *argv[])
{
    CSOUND *Csound = csoundCreate(NULL);
    assert(csoundSetOption(Csound, "--output=dac") == CSOUND_SUCCESS);
    char *orchestra =
        "0dbfs = 1\n"
        "ksmps = 1\n"
        "// ksmps = 64\n"
        "alwayson 1\n"
        "instr 1\n"
        "    outc 0.5 * expon:a(1, 0.1, 0.0001) * (poscil(162, 0.2) + poscil(80, 0.2))\n"
        "endin\n";
    assert(csoundCompileOrc(Csound, orchestra) == CSOUND_SUCCESS);
    assert(csoundStart(Csound) == CSOUND_SUCCESS);

    void *threadID = csoundCreateThread(perform, (void *)Csound);

    size_t timeInterval = 100;
    size_t maxTime = 10000;
    for (unsigned int i = 0; i < maxTime / timeInterval; i++) {
        struct timespec start;
        assert(clock_gettime(CLOCK_MONOTONIC, &start) == 0);
        
        csoundSleep(timeInterval);
        
        struct timespec end;
        assert(clock_gettime(CLOCK_MONOTONIC, &end) == 0);
        
        struct timespec difference = {end.tv_sec - start.tv_sec, end.tv_nsec - start.tv_nsec};
        if (end.tv_nsec < start.tv_nsec) {
            difference.tv_sec -= 1;
            difference.tv_nsec += 1000000000;
        }
        double elapsedTimeInSeconds = difference.tv_sec + difference.tv_nsec / 1000000000.;
        printf("csoundSleep(%zu) took about %f ms\n", timeInterval, 1000 * elapsedTimeInSeconds);
        
        csoundInputMessage(Csound, "i 1 0 1");
    }

    csoundStop(Csound);
    assert(csoundJoinThread(threadID) == 0);
    csoundDestroy(Csound);

    return 0;
}
```

On macOS and Linux (Debian GNU/Linux 8 (jessie) 64-bit running in VMWare Fusion) `csoundSleep` always takes about 100 ms (as expected). On Linux only, though, the differences in times printed in `rtevent` messages can be considerably more than 100 ms. I haven’t observed a 700 ms gap, but 200 ms is not uncommon. This doesn’t happen on macOS.

**Comment by vlazzarini** [comment] 2017-04-04 21:40
As I said above, csoundInputMessage() will be inserted between calls to perfKsmps(), if these are bunched together, timing jitter could occur. There is no guarantee that the two threads will be synchronised to the same clock.

**Comment by nwhetsell** [comment] 2017-04-04 21:45
> As I said above, csoundInputMessage() will be inserted between calls to perfKsmps()

Sorry, this looks like the first mention of `perfKsmps()` in this issue thread. Is this a Csound function? A [search for “perfKsmps” in the Csound repository](https://github.com/csound/csound/search?q=perfKsmps) currently has no code results.

**Comment by rorywalsh** [comment] 2017-04-04 21:49
I'm pretty sure that's a typo and should be csoundPerformKsmps().

**Comment by vlazzarini** [comment] 2017-04-04 21:55
csoundPerform() calls kperf() (csound.c: 2114). The calls get bunched up. Timing jitters occur.

**Comment by nwhetsell** [comment] 2017-04-05 00:19
Just to make sure I understand: (1) calls to `csoundInputMessage` result in events being queued somehow, (2) these events are queued between performances of a control period (calls of Csound’s `kperf` function), and (3) the events are actually performed in such a way that they can be “bunched up”; the amount of time between actual events may be less than the amount of time between queueing the events.

I may be missing something, but this doesn’t seem to match what Csound outputs. Here is a plot of the differences between event performance times (at least I think they’re event performance times) on Linux for the [code above](https://github.com/csound/csound/issues/772#issue-219043957):

<img width="408" alt="screen shot 2017-04-04 at 8 04 27 pm" src="https://cloud.githubusercontent.com/assets/14102861/24684193/3008e50e-1972-11e7-99e7-af160d41dc70.png">

The vertical axis is the amount of time between events in seconds. The code above calls `csoundInputMessage` every 0.1 s. If events were actually being performed every 0.1 s, I’d expect to see a horizontal line right at 0.1 s.

Instead, events may be performed after 0.1 s or more, but never less. When I think of events being “bunched up”, I would imagine that a delay in performing events should be followed by a, well, bunch of events being performed, with less than 0.1 s in between. This does not seem to happen. Events are delayed, but there are no bunches.

Another oddity – and maybe this is a separate issue – is that the behavior of the code above is rather different on Windows. The amount of delay between events is several _minutes_.

**Comment by vlazzarini** [comment] 2017-04-05 09:06
- On Windows, sleep() is probably different (last time I looked, it had a minimum of 1 sec interval).  
- the events might not be bunched up, they might be simply delayed by different amounts, but this is still caused by the fact that kperf() is not guaranteed to be called in a synchronised way to the other thread. Depending on the audio backend, kperf() will block for different amounts of time in the IO read/write functions.  InputMessage() uses a mutex (see top/threadsafe.c) to prevent simultaneous access to shared data and that would place its calls in between kperf() calls, so it is likely that two calls to InputMessage() will not fall in the same kcycle in this case.
Any level of synchronisation between threads needs to be implemented/managed by the application,
through message queues, shared clocks, etc. Depending on the needs, the host can implement its own audio backend to ensure that things are done in a certain way (e.g. as Cabbage does).

As an aside, I had similar issues when working on Android that I had to deal with. On one project that required Csound performKmsps() to be called regularly, I had to re-implement the backend so that the calls originated from the OpenSL callback, rather than from a Java thread. The Java thread, as we would expect, had a hugely variable timing due to garbage collection (and possibly other things).
A similar clock synchronisation issue was taking place there, which got solved by relying on the IO callback regularity. However, this was also not guaranteed on all devices and depended very much on the actual audio implementation of each particular device. Older devices (even with newer versions of Android) had a lot callback jitter.

**Comment by nwhetsell** [comment] 2017-04-05 10:33
So, this means that `csoundInputMessage` is thread-safe in the sense that it doesn’t cause a data race if it’s used to send a message to a Csound instance performing on another thread. However, if you want to send a score event like `i 1 0 1` to a Csound instance, and you want the event to be performed immediately (or at least not after a 700 ms delay), then you must call `csoundInputMessage` on the Csound instance’s performance thread, which will presumably be a loop that calls `csoundPerformKsmps` repeatedly. Is this right?

If so, it might be a good idea to note this in the Csound API documentation, because while `csoundInputMessage` is thread-safe, then again it isn’t; if it’s not called on Csound’s performance thread, there’s a high risk of a delay between calling that function and actual performance of an event. And I assume that this is also true of `csoundReadScore` and `csoundScoreEvent`.

The argument of [`Sleep` on Windows is in milliseconds](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298.aspx), and [here](https://github.com/csound/csound/blob/ec449752a20b740f49ab81bba86b3ddf7f99471c/Top/threads.c#L630) is the implementation of `csoundSleep` on Windows.

**Comment by nwhetsell** [comment] 2017-04-05 10:53
What’s `csoundPeformanceThread`? A [search for “csoundPeformanceThread” in the Csound repository](https://github.com/csound/csound/search?q=csoundPeformanceThread) has no code results. Or are you saying (1) run `csoundPerformKsmps` in a loop on a background thread, (2) put strings to pass to `csoundInputMessage` on some sort of (thread-safe) queue on the main thread, and (3) pop strings off the queue after each iteration of `csoundPerformKsmps` and pass them to `csoundInputMessage`.

**Comment by vlazzarini** [comment] 2017-04-05 10:59
Look for CsoundPerformanceThread, in interfaces/csPerfThread.hpp.
Yes, what you describe is what I had in mind, but CsoundPerformanceThread should do this for you. It's part of the interfaces library (libcsnd6.dylib in OSX). You can use it, or you can copy what it does in your code. This has been used since csound 5.00 and it seems very robust.

**Comment by nwhetsell** [comment] 2017-04-05 11:05
Ah, [there it is](https://github.com/csound/csound/search?q=CsoundPeformanceThread), thanks! GitHub searches are case-sensitive, evidently.

**Comment by vlazzarini** [comment] 2017-04-05 11:07
Minimal example here:
https://github.com/csound/csoundAPI_examples/blob/master/cpp/csPerfThreadExample.cpp

**Closed** 2017-04-11 09:22 UTC
