### ISSUE TITLE
Csound~ readbuf won't read in correct number of channels

### ISSUE THREAD

**Issue by unriginal** [csound/csound#496] opened 2015-06-29 19:35 UTC
If I load a buffer into an ftable with a readbuf message, it will copy the correct length, but it will not copy the correct amount of channels (it is typically defaulting to 1 channel, even when loading a stereo file). Also, it seems like performance with loscil is inconsistent- sometimes tables loaded in with readbuf will work, and sometimes they won't.
Here is a link that includes an example maxpatch, csd, and some samples:
https://www.dropbox.com/s/v6pd0601a7rxwa6/Readbuf%20Bug.zip?dl=0

I am using csound~ 1.1.3, Max 7.0.4, and OSX 10.10.3

**Comment by kunstmusik** [comment] 2015-06-30 02:02
It looks to me that the code reads in the data but it is not setting the
number of channels on Csound's internal function table data structure.
From first glance, I'm not sure how this could ever work with the code I'm
seeing?

Is this a bug where something used to work but now isn't, or is this an
entirely new bug?

**Comment by unriginal** [comment] 2015-06-30 14:59
This is an entirely new bug. The documentation for csound~ says that by
giving a channel argument of 0 for readbuf, the resulting ftable will have
the same number of channels as the buffer~ that is being copied from. I
realized there was a bug in the csd I uploaded (I thought ftchnls took a
table number, not a constant), and so now the link points to a fixed
version that is fixed.

**Comment by kunstmusik** [comment] 2015-06-30 15:27
Okay, I think this one will take a little time to sort out what to do, as I
think it may require changes to the Csound API.

**Comment by vlazzarini** [comment] 2015-06-30 15:50
I don't understand that, if readbuf behaved like that, then it changed, surely it weren't the API changes from Csound 5 to Csound 6 that caused it. I can't think of any modifications to the API that regressed functionality for hosts.

**Comment by kunstmusik** [comment] 2015-06-30 16:16
@vlazzarini I think the problem is that it never worked as @unriginal intends to use it.  It looks to me the data is being loaded correctly, but the FUNC datastructure has it's nChannels set to the default 1. So the stereo data is load and written into an f-table alright, but I don't see a way to set nChannels to 2.  However, this is an area of Csound code I haven't spent much time with, so if you see something please let me know.

**Comment by vlazzarini** [comment] 2015-06-30 16:35
so it is not a bug, and definitely not a new bug. We should close this ticket and ask for a feature request for the API outlining what it is supposed to do

**Comment by kunstmusik** [comment] 2015-06-30 16:38
I've just marked this as an enhancement rather than bug.  Let's keep this around so we can use it as a test for whatever changes happen for the API.

**Comment by vlazzarini** [comment] 2020-07-24 10:25
Moved: https://github.com/csound/csound_tilde/issues/12

**Closed by vlazzarini** 2020-07-24 10:25 UTC
Labels: csound~ (MaxMSP), enhancement
