### ISSUE TITLE
csoundInitializeCscore does not seem to work in Windows

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#634] opened 2016-04-24 13:27 UTC
`csoundInitializeCscore` (defined in [cscorfns.c](https://github.com/csound/csound/blob/develop/Top/cscorfns.c)) does not seem to work in Windows. Running a console application consisting of

```c
#include <csound/csound.h>
#include "stdafx.h"

#pragma warning(disable:4996) // Compile fopen.

int main()
{
	CSOUND *Csound = csoundCreate(NULL);
	FILE *inputFile = fopen("C:\\Users\\Public\\input.sco", "r");
	printf("Opened inputFile %p\n", inputFile);
	FILE *outputFile = fopen("C:\\Users\\Public\\output.sco", "w");
	printf("Opened outputFile: %p\n", outputFile);
	csoundInitializeCscore(Csound, inputFile, outputFile);
	// Uncomment these lines to close the files.
	//fclose(inputFile);
	//fclose(outputFile);
	return 0;
}
```

in Visual Studio Community 2015 v14.0.25123.00 Update 2 prints non-`NULL` file pointers (input.sco consists of only `e`) and then shows a dialog containing

> Debug Assertion Failed!
>
> Program:
> _[my executable path]_
> File: minkernel\crts\ucrt\src\appcrt\lowia\close.cpp
> Line: 49
>
> Expression: (_osfile(fh) * FOPEN)

Trying to continue execution shows a dialog containing

> Unhandled exception at 0x00007FF9D35E037B (ucrtbased.dll) in _[my executable name]_: An invalid parameter was passed to a function that considers invalid parameters fatal.

This is using Csound 6.07.0rc2 in 64-bit Windows 10.

**Comment by vlazzarini** [comment] 2016-04-24 14:35
Windows developers know more, but my impression is that if you want to use the Csound lib binary, you will need to use the mingwin 64bit toolchain. I don't think you can link to it from the microsoft linker.

**Comment by nwhetsell** [comment] 2016-04-24 14:52
I can use the Visual Studio toolchain to build a Node.js Addon for Csound (https://github.com/nwhetsell/csound-api#on-windows), and all the Addon’s tests pass on Windows. (The Addon’s [test of `csound.InitializeCscore`](https://github.com/nwhetsell/csound-api/blob/5daea1fc31d1a17bd85a37185114aedd53cc2a9c/spec/csound-api-spec.js#L159) passes on Windows only because I’m verifying that function is `undefined` on Windows.) `csoundInitializeCscore` seems to be unique in producing this behavior on Windows.

**Comment by gogins** [comment] 2016-10-01 18:54
Please provide a complete example of HOW this is supposed to work as I have
absolutely no experience with CScore.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by nwhetsell** [comment] 2016-10-01 19:11
I don’t have any experience with Cscore either, and I’m not sure how a complete example of Cscore on Windows would shed light on this issue.

`csoundInitializationCscore` is [documented](https://github.com/csound/csound/blob/7b7367f41af6c9f282116715c8c74c9f8f99e0e8/include/csound.h#L657) as returning “CSOUND_SUCCESS on success and CSOUND_INITIALIZATION or other error code if it fails.” On Windows, the expected behavior does not occur. Instead, execution ends with an unhandled exception.

**Comment by gogins** [comment] 2016-10-01 19:26
Sorry to ask so many questons, but I do not have a Windows compiler where I
am.

So are there files that actually exist that the example is trying to open?
If so, could you please supply these files?

If this a vanilla build of the Csound library (i.e. using mingw64)? I see
that the example is built using the Microsoft compiler. Are the required
runtime libraries for the Csound library in the PATH of the example? That
would probably cause something like this. Another thing that would cause a
problem is if the Csound library is built for 64 bit CPU architecture (as
the 6.07 installer is) and the example is built for 32 bit CPU architecture
(or vice versa).

Does the program advance past  csoundInitializeCscore(Csound, inputFile,
outputFile); ? If so, then the exception occurs when the example program is
exiting. If not, then the exception occurs within the call to
csoundInitializeCscore(Csound, inputFile, outputFile);.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by nwhetsell** [comment] 2016-10-02 02:03
> So are there files that actually exist that the example is trying to open?

The example code opens a file at C:\Users\Public\input.sco for reading. I think I mentioned in the issue description that input.sco consists of only `e`.

> If so, could you please supply these files?

If you really want, I can attach a score with just `e` in it, but you can make your own by entering in Command Prompt

```batch
echo e > C:\Users\Public\input.sco
```

> I[s] this a vanilla build of the Csound library (i.e. using mingw64)?

I installed Csound by running the setup executable at https://github.com/csound/csound/releases/download/6.07.0/Setup_Csound6_x64_6.07.0.exe. I then created a csound64.lib file by opening Command Prompt in C:\\Program Files\\Csound6_x64\\bin and running

```batch
set PATH=%PATH%;%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\bin
echo LIBRARY csound64.dll > csound64.def && echo EXPORTS >> csound64.def
for /F "skip=19 tokens=4" %G in ('dumpbin /exports csound64.dll') do @echo %G >> csound64.def
lib /def:csound64.def /machine:x64
```

> Are the required runtime libraries for the Csound library in the PATH of the example?

I believe so. I’ll come back to this.

> Another thing that would cause a problem is if the Csound library is built for 64 bit CPU architecture (as the 6.07 installer is) and the example is built for 32 bit CPU architecture (or vice versa).

My build configuration is x64.

> Does the program advance past csoundInitializeCscore(Csound, inputFile, outputFile);?

Yes; the exception occurs at exit.

Back to the runtime libraries. I first encountered this issue when I set up AppVeyor for [this Node.js Addon](https://github.com/nwhetsell/csound-api). You can see the most recent builds at https://ci.appveyor.com/project/nwhetsell/csound-api/build/1.0.54. The tests of the most recent build all pass on AppVeyor in Node.js 4.5.0 and 6.6.0. Because of this, I can’t imagine an issue like the Csound library not being found — I’d expect all the tests to fail — but I might be wrong.

That said, the test of `csoundInitializeCscore` on Windows passes only because it’s pretty much skipped. If you want to run these tests, depending on your configuration you might be able to do so by running in Command Prompt something like:

```batch
git clone https://github.com/nwhetsell/csound-api.git
cd csound-api
npm install nan
set CL=/I"C:\path\to\boost"
node-gyp rebuild
npm --global install jasmine
npm install bindings
jasmine
```

where `C:\path\to\boost` is the path to [Boost](http://www.boost.org/) on your computer.

Then, to see this issue, you’ll need to

1. Remove [two `#ifndef _MSC_VER` guards for InitializeCscore](https://github.com/nwhetsell/csound-api/search?q=InitializeCscore+path%3Asrc+filename%3Acsound-api.cc)
2. Remove [a check for the Windows platform in the tests](https://github.com/nwhetsell/csound-api/search?q=win32+path%3Aspec+filename%3Acsound-api-spec.js)
3. Re-run `node-gyp rebuild` and `jasmine`

The tests will stop at `csoundInitializeCscore`.

**Comment by gogins** [comment] 2016-10-02 02:23
That certainly all looks correct, though I thought I had included the
Microsoft import lib in the installer. I'll check this on windows late next
week.

Thanks,
Mike

**Comment by gogins** [comment] 2016-10-04 14:12
The import lib is not mentioned in the installer script, so I will add it when I get back to my Windows computer and try to replicate the bug.

**Comment by nwhetsell** [comment] 2016-10-04 14:39
It’s not installed with Csound 6.07, but issue #651 indicates it will be included with Csound 6.08.

**Comment by gogins** [comment] 2016-10-13 14:13
I have reproduced this error in the VS2015 debugger. The assertion fires in the MIcrosoft runtime library's call to exit().

**Comment by gogins** [comment] 2016-10-13 18:45
OK, narrowing it down just a bit more. I changed the program to print more information. On Windows:

virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.08 (double samples) Oct  6 2016
libsndfile-1.0.26-exp
Opened inputFile: 0000005B534D2530
file_number: 3
Opened outputFile: 0000005B534C6200
Called csoundInitializeCscore().
file_number: 35

**Comment by gogins** [comment] 2016-10-13 18:58
In gdb it seems to be happening in corefile_rewind:

(gdb) print *insco
$9 = {_ptr = 0x0, _cnt = 0,
  _base = 0x200100000000 <error: Cannot access memory at address 0x200100000000>, _flag = 3, _file = 0, _charbuf = 0, _bufsiz = 0, _tmpfname = 0x0}
(gdb) next
833           corfile_rewind(inf);
(gdb) print *insco
$10 = {_ptr = 0x0, _cnt = -1,
  _base = 0x200100000000 <error: Cannot access memory at address 0x200100000000>, _flag = 35, _file = 0, _charbuf = 0, _bufsiz = 0, _tmpfname = 0x0}
(gdb) print _fileno(insco)
$11 = 35

**Comment by gogins** [comment] 2016-10-13 19:50
With my all-mingw64 test program I get:

Breakpoint 1, csoundInitializeCscore (csound=0x430080,
    insco=0x7fde7c3e2a0 <msvcrt!_iob+144>,
    outsco=0x7fde7c3e2d0 <msvcrt!_iob+192>)
    at D:/msys64/home/restore/csound/Top/cscorfns.c:826
826     {
(gdb) print *insco
$1 = {_ptr = 0x0, _cnt = 0, _base = 0x0, _flag = 1, _file = 3, _charbuf = 0,
  _bufsiz = 4096, _tmpfname = 0x0}
(gdb) next
828         if (insco != NULL) {
(gdb)
826     {
(gdb)
828         if (insco != NULL) {
(gdb)
829           CORFIL *inf = corfile_create_w();
(gdb)
832               c = fgetc(insco);
(gdb) print *insco
$2 = {_ptr = 0x0, _cnt = 0, _base = 0x0, _flag = 1, _file = 3, _charbuf = 0,
  _bufsiz = 4096, _tmpfname = 0x0}
(gdb) print c
$3 = <optimized out>
(gdb) next
833               if (c == EOF) {
(gdb) print c
$4 = 101
(gdb) print feof(insco)
$5 = 0
(gdb) next
836                 corfile_putc(c, inf);
(gdb)
832               c = fgetc(insco);
(gdb)
833               if (c == EOF) {
(gdb) print c
$6 = 10
(gdb) print *insco
$7 = {_ptr = 0x3de40f2 "", _cnt = 0, _base = 0x3de40f0 "e\n", _flag = 9,
  _file = 3, _charbuf = 0, _bufsiz = 4096, _tmpfname = 0x0}
(gdb) next
836                 corfile_putc(c, inf);
(gdb)
832               c = fgetc(insco);
(gdb)
833               if (c == EOF) {
(gdb) print c
$8 = -1
(gdb) print feof(insco)
$9 = 16
(gdb) print *insco
$10 = {_ptr = 0x3de40f0 "e\n", _cnt = 0, _base = 0x3de40f0 "e\n", _flag = 25,
  _file = 3, _charbuf = 0, _bufsiz = 4096, _tmpfname = 0x0}
(gdb)

With my hybrid program I get:

Breakpoint 1, csoundInitializeCscore (csound=0x73af570080,
    insco=0x73af4104a0, outsco=0x73af402070)
    at D:/msys64/home/restore/csound/Top/cscorfns.c:826
826     {
(gdb) print *insco
$1 = {_ptr = 0x0, _cnt = 0,
  _base = 0x200100000000 <error: Cannot access memory at address 0x200100000000>, _flag = 3, _file = 0, _charbuf = 0, _bufsiz = 0, _tmpfname = 0x0}
(gdb) next
828         if (insco != NULL) {
(gdb)
826     {
(gdb)
828         if (insco != NULL) {
(gdb)
829           CORFIL *inf = corfile_create_w();
(gdb)
832               c = fgetc(insco);
(gdb)
833               if (c == EOF) {
(gdb) print *insco
$2 = {_ptr = 0x0, _cnt = -1,
  _base = 0x200100000000 <error: Cannot access memory at address 0x200100000000>, _flag = 35, _file = 0, _charbuf = 0, _bufsiz = 0, _tmpfname = 0x0}
(gdb)

Therefore, it is clear that the FILE object created in the Microsoft runtime does not inter-operate with the stdio.h functions in the MinGW runtime. Perhaps this has something to do with the inaccessible _base address.

I can't see how to debug this further. I'm going to do a little googling and if turn something up, I will re-open this issue. In the meantime, I'm closing this as "can't fix". Users of cscore functions on Windows must, in the meantime, compile their programs with the MinGW compiler.

**Closed by gogins** 2016-10-13 19:50 UTC
Labels: windows
