### ISSUE TITLE
Csound::Compile() won't work if non-English characters in path..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#632] opened 2016-04-21 12:59 UTC
Many of my students have non-English characters in their names. Their home directory, which is the base of all their document paths, therefore contains non English characters. When I use these paths with Csound::Compile() I get:

> csound->FileOpen2 failed:: No such file or directory

Below is a simple .cpp file you can test with it. Note that I've only tested this on Windows. I think it's working fine on other platforms. There is no problem when I use the offending path directly with the Csound command line. 

```
#include <stdio.h>
#include "csound.hpp"

int main(int argc, char *argv[])
{
Csound* csound = new Csound();

//doesn't work....
csound->Compile("C:/Users/rory/Desktop/Ádhamh/quickTest.csd");

//works fine....
csound->Compile("C:/Users/rory/Desktop/quickTest.csd");

csound->Start();
csound->Perform();	
delete csound;

return 0;
}
```

**Comment by vlazzarini** [comment] 2016-04-21 13:12
I tried a similar test on OSX

```
csound->Compile("àèù.csd");
```

and it passed.

**Comment by fsateler** [comment] 2016-04-21 13:18
I think the problem is that the string encoding in the source file does not match the encoding used at runtime, thus "special" characters get garbled. @rorywalsh, does the problem persist if you pass the filename via a command line argument to your test program? Also, you can test changing the file encoding to different things (try with utf-8, notepad++ has a `Encoding` menu that can be used to easily switch)

**Comment by rorywalsh** [comment] 2016-04-21 15:53
Thanks Fiipe, passing the filename from the command line does work but encoding my files as utf8 doesn't make any difference. Any other ideas?

**Comment by rorywalsh** [comment] 2016-04-22 09:47
Csound seems to replace the Á with ├ü on Windows? There's hardly a compiler setting I'm overlooking or something?  

> csound->FileOpen2 failed:: No such file or directory
> UnifiedCSD:  C:/Users/rory/Desktop/├üdhamh/quickTest.csd

**Comment by fsateler** [comment] 2016-04-22 11:14
Rory, did you try other encoding options?

Unfortunately, because c strings have 8bit characters, your sources need to
match the system encoding for this to work. More unfortunately, I have no
idea how to determine the system encoding on windows.

**Comment by rorywalsh** [comment] 2016-04-22 12:17
I did Felipe, but none seem to work. I'll keep digging.

**Comment by rorywalsh** [comment] 2016-04-22 14:38
It seems the fopen() on windows at least will not return a valid FILE pointer if non-ascii chars are in the file path. The solution is to use _wfopen() which I think is Windows only. Using _wfopen() instead of fopen in the following code fixes the issue.

https://github.com/csound/csound/blob/develop/Engine/envvar.c#L1011-L1019

But it's obviously Windows only. Would the devs mind implementing this with some if-def blocks?

**Comment by vlazzarini** [comment] 2016-04-22 15:24
that could be done for some files, but I wonder if libsndfile would do this too? Can you try and see
if diskin opens a file with wide characters?

**Comment by jpffitch** [comment] 2016-04-22 15:26
If arguents te sane or near same I would prefer a macro so easy to use all 
over

**Comment by rorywalsh** [comment] 2016-04-22 18:01
@vlazzarini : diskin2 fails with wide characters. In fact, it seems that any strings with wide chars chars on Windows will not be read properly. Include files that use non-ascii paths also return a not found error.  

@jpffitch in those lines I quoted, fullName needs to be a wchar_t*, while params needs to be cast as a wchar_t*. Something like this does it(I say like this because I'm not at the machine I tested it on, but that's more or less what I did):

```
wchar_t* fullNameW = (wchar_t*) name;
      // fullName = (wchar_t*) name;
       if (type == CSFILE_STD) {
         tmp_f = _wfopen(name, (const wchar_t*) param);
         if (tmp_f == NULL) {
           perror(Str("csound->FileOpen2 failed:!"));
           goto err_return;
         }
      }
```

**Comment by vlazzarini** [comment] 2016-04-22 18:12
not sure if we call fopen or we let libsndfile do it for us. If it is the second case, then you'll need to ask Erik.

**Comment by rorywalsh** [comment] 2016-04-22 18:16
Considering Csound can't handle non-ascii characters the diskin issue is not as big one for me. (although it may well confuse some users). Not being able to compile a file with the API that has non-ascii characters in its path concerns me more.

**Comment by vlazzarini** [comment] 2016-04-22 19:44
Ok, I looked and we use libsndfile sf_open etc functions to open soundfile. So that's that. As for standard files, we use fopen, which could be replaced on windows for a more suitable function. It's in envvar.c . You could possibly try it and see if it does anything, then we could look at adding to the sources.

**Comment by rorywalsh** [comment] 2016-04-22 19:51
The solution is the same as the one I posted a few hours ago, we should use _wfopen().

**Comment by vlazzarini** [comment] 2016-04-22 20:07
That may be, but it would be good if you could try and let us know. We're linux-osx people here.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by rorywalsh** [comment] 2016-04-22 20:12
I have tried it. I tested it on Windows just before I posted the solution. That's why I refer to it as a "solution"  ;)  But I'd still rather leave it to you guys to implement it the way you see fit.

**Comment by vlazzarini** [comment] 2016-04-22 20:27
I see. But we need a Windows developer to implement it all, so we are not doing it blindly.

**Comment by rorywalsh** [comment] 2016-04-22 20:47
I'll post some code tomorrow when I'm back in the land of Windoz.

**Comment by rorywalsh** [comment] 2016-04-24 08:05
I think this is sorted now. I've updated my original code snippet with working code. I've tested with simple command line API programs and I've also tested it with Cabbage. I left
`fullName = (char*) name;`
within the if-def block as fullname appears to be used later in that function.

**Comment by jpffitch** [comment] 2016-04-24 14:43
When you say sorted does it need changes to csound sources?

**Comment by rorywalsh** [comment] 2016-04-24 14:44
Yes, if you wouldn't mind. The code is posted above.

**Comment by jpffitch** [comment] 2016-04-24 16:31
In git; did I get it right?
Please check

**Comment by rorywalsh** [comment] 2016-04-24 18:14
There seems to be a stray bracket there. I've attached the fixed version.

**Comment by gogins** [comment] 2016-04-24 19:18
I also found and fixed this.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by jpffitch** [comment] 2016-04-24 20:05
The code is a partial fix at best.    There are other calls to fopen and open in envvar.c that are unmodified
so writing to files differs from reading.  We need a comprehensible fix.  Some sndfile opens are OK as they use the fd from open.

I still cannot see any extra rackets either

**Comment by rorywalsh** [comment] 2016-05-13 08:02
I just ran into an issue with this latest change when using Microsoft's .NET framework. It seems that it doesn't appreciate the call to _wfopen() and produces a problem with msvcrt.dll. It's not easy to fix as there are no debug tools that can help. But reverting the code does make the issue go away. I'm not sure what's the best course of action here. The fix allows us to open files paths with non-English characters on Windows, but causes a problem for anyone using Csound with .NET. What would people think about a new compile method to deal with non-English paths? Would this be appropriate? Users could just call this instead of the normal csoundCompile() on Windows if they wanted it? Or has anyone any other suggestions?

**Comment by jpffitch** [comment] 2016-10-10 12:59
is it possible to detect at runtime that .net is being used?

There are a number of calls to fopen in the sources.  Which do you think should get the _wfopen treatment?

**Comment by rorywalsh** [comment] 2016-10-10 13:52
I'm not sure. I wouldn't suggest any of them get the _wfopen() treatment if it means not being able to use Csound with .net. I don't know how best to proceed.

**Comment by gogins** [comment] 2016-10-10 14:15
Provide a "_w" variant.

Regards,
Mike

**Comment by jpffitch** [comment] 2016-10-10 18:13
I thought the problem was in .net

⁣

Sent from TypeApp

​

**Comment by rorywalsh** [comment] 2016-10-11 09:19
Here's a quick run down of the issue. Csound won't open files that have
non-English characters on Windows unless we use _wfopen(). This is now
added and working as far as I can tell. But after this change was made I
noticed that _wfopen() causes an issue when using DLLImport from C#. I'm
afraid I don't know enough about C# to be able to suggest a fix. But I can
confirm that removing the call to _wfopen() does fix the issue.

**Comment by vlazzarini** [comment] 2016-10-20 20:08
I think this is a won't fix case. Can we have an #ifdef C# or something?

**Comment by jpffitch** [comment] 2016-10-24 10:42
More a cannot fix as Windows does not provide a working fopen.  For now we should just keep this problem in mind

**Closed by jpffitch** 2016-10-24 10:42 UTC
Labels: enhancement, windows, wontfix

**Comment by rorywalsh** [comment] 2016-10-25 18:14
Can we not use some kind of if/def as Victor suggested?

**Comment by rorywalsh** [comment] 2016-10-25 18:20
This sounds like a reasonable solution.
